<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Behavioral insights from choice models | An Introduction to Discrete Choice Analysis</title>
  <meta name="description" content="These notes were created by Antonio Paez as a resource for teaching a graduate discrete choice analysis course (GEOG 738) at McMaster University." />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Behavioral insights from choice models | An Introduction to Discrete Choice Analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="These notes were created by Antonio Paez as a resource for teaching a graduate discrete choice analysis course (GEOG 738) at McMaster University." />
  <meta name="github-repo" content="paezha/Discrete-Choice-Analysis-with-R" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Behavioral insights from choice models | An Introduction to Discrete Choice Analysis" />
  
  <meta name="twitter:description" content="These notes were created by Antonio Paez as a resource for teaching a graduate discrete choice analysis course (GEOG 738) at McMaster University." />
  

<meta name="author" content="Antonio Paez" />


<meta name="date" content="2020-02-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chapter-4.html"/>
<link rel="next" href="chapter-6.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.49.4/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.49.4/plotly-latest.min.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#choices-choices-choices"><i class="fa fa-check"></i>Choices, choices, choices</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#price-mechanisms"><i class="fa fa-check"></i>Price Mechanisms</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#plan"><i class="fa fa-check"></i>Plan</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#audience"><i class="fa fa-check"></i>Audience</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#requisites"><i class="fa fa-check"></i>Requisites</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html"><i class="fa fa-check"></i><b>1</b> Preliminaries: Installing R and RStudio</a><ul>
<li class="chapter" data-level="1.1" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html#introduction"><i class="fa fa-check"></i><b>1.1</b> Introduction</a></li>
<li class="chapter" data-level="1.2" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html#learning-objectives"><i class="fa fa-check"></i><b>1.2</b> Learning Objectives</a></li>
<li class="chapter" data-level="1.3" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html#r-the-open-statistical-computing-project"><i class="fa fa-check"></i><b>1.3</b> R: The Open Statistical Computing Project</a><ul>
<li class="chapter" data-level="1.3.1" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html#what-is-r"><i class="fa fa-check"></i><b>1.3.1</b> What is R?</a></li>
<li class="chapter" data-level="1.3.2" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html#the-rstudio-ide"><i class="fa fa-check"></i><b>1.3.2</b> The RStudio IDE</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html#packages-in-r"><i class="fa fa-check"></i><b>1.4</b> Packages in R</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chapter-1.html"><a href="chapter-1.html"><i class="fa fa-check"></i><b>2</b> Data and stuff</a><ul>
<li class="chapter" data-level="2.1" data-path="chapter-1.html"><a href="chapter-1.html#what-are-models"><i class="fa fa-check"></i><b>2.1</b> What are models?</a></li>
<li class="chapter" data-level="2.2" data-path="chapter-1.html"><a href="chapter-1.html#how-to-use-this-note"><i class="fa fa-check"></i><b>2.2</b> How to use this note</a></li>
<li class="chapter" data-level="2.3" data-path="chapter-1.html"><a href="chapter-1.html#learning-objectives-1"><i class="fa fa-check"></i><b>2.3</b> Learning objectives</a></li>
<li class="chapter" data-level="2.4" data-path="chapter-1.html"><a href="chapter-1.html#suggested-readings"><i class="fa fa-check"></i><b>2.4</b> Suggested readings</a></li>
<li class="chapter" data-level="2.5" data-path="chapter-1.html"><a href="chapter-1.html#ways-of-measuring-stuff"><i class="fa fa-check"></i><b>2.5</b> Ways of measuring stuff</a><ul>
<li class="chapter" data-level="2.5.1" data-path="chapter-1.html"><a href="chapter-1.html#categorical"><i class="fa fa-check"></i><b>2.5.1</b> Categorical</a></li>
<li class="chapter" data-level="2.5.2" data-path="chapter-1.html"><a href="chapter-1.html#quantitative"><i class="fa fa-check"></i><b>2.5.2</b> Quantitative</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="chapter-1.html"><a href="chapter-1.html#importing-data"><i class="fa fa-check"></i><b>2.6</b> Importing data</a></li>
<li class="chapter" data-level="2.7" data-path="chapter-1.html"><a href="chapter-1.html#data-classes-in-r"><i class="fa fa-check"></i><b>2.7</b> Data Classes in <code>R</code></a></li>
<li class="chapter" data-level="2.8" data-path="chapter-1.html"><a href="chapter-1.html#more-on-indexing-and-data-manipulation"><i class="fa fa-check"></i><b>2.8</b> More on indexing and data manipulation</a></li>
<li class="chapter" data-level="2.9" data-path="chapter-1.html"><a href="chapter-1.html#visualization"><i class="fa fa-check"></i><b>2.9</b> Visualization</a></li>
<li class="chapter" data-level="2.10" data-path="chapter-1.html"><a href="chapter-1.html#exercise"><i class="fa fa-check"></i><b>2.10</b> Exercise</a><ul>
<li class="chapter" data-level="2.10.1" data-path="chapter-1.html"><a href="chapter-1.html#questions"><i class="fa fa-check"></i><b>2.10.1</b> Questions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chapter-2.html"><a href="chapter-2.html"><i class="fa fa-check"></i><b>3</b> Fundamental concepts</a><ul>
<li class="chapter" data-level="3.1" data-path="chapter-2.html"><a href="chapter-2.html#why-modelling-choices"><i class="fa fa-check"></i><b>3.1</b> Why modelling choices?</a></li>
<li class="chapter" data-level="3.2" data-path="chapter-2.html"><a href="chapter-2.html#how-to-use-this-note-1"><i class="fa fa-check"></i><b>3.2</b> How to use this note</a></li>
<li class="chapter" data-level="3.3" data-path="chapter-2.html"><a href="chapter-2.html#learning-objectives-2"><i class="fa fa-check"></i><b>3.3</b> Learning objectives</a></li>
<li class="chapter" data-level="3.4" data-path="chapter-2.html"><a href="chapter-2.html#suggested-readings-1"><i class="fa fa-check"></i><b>3.4</b> Suggested readings</a></li>
<li class="chapter" data-level="3.5" data-path="chapter-2.html"><a href="chapter-2.html#preliminaries"><i class="fa fa-check"></i><b>3.5</b> Preliminaries</a></li>
<li class="chapter" data-level="3.6" data-path="chapter-2.html"><a href="chapter-2.html#utility-maximization"><i class="fa fa-check"></i><b>3.6</b> Utility maximization</a><ul>
<li class="chapter" data-level="3.6.1" data-path="chapter-2.html"><a href="chapter-2.html#what-is-utility"><i class="fa fa-check"></i><b>3.6.1</b> What is utility?</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="chapter-2.html"><a href="chapter-2.html#what-about-those-random-terms"><i class="fa fa-check"></i><b>3.7</b> What about those random terms?</a></li>
<li class="chapter" data-level="3.8" data-path="chapter-2.html"><a href="chapter-2.html#probability-distribution-functions-pdfs"><i class="fa fa-check"></i><b>3.8</b> Probability distribution functions (PDFs)</a></li>
<li class="chapter" data-level="3.9" data-path="chapter-2.html"><a href="chapter-2.html#a-simple-random-utility-discrete-choice-model"><i class="fa fa-check"></i><b>3.9</b> A simple random utility discrete choice model</a></li>
<li class="chapter" data-level="3.10" data-path="chapter-2.html"><a href="chapter-2.html#other-choice-mechanisms"><i class="fa fa-check"></i><b>3.10</b> Other choice mechanisms</a></li>
<li class="chapter" data-level="3.11" data-path="chapter-2.html"><a href="chapter-2.html#exercise-1"><i class="fa fa-check"></i><b>3.11</b> Exercise</a><ul>
<li class="chapter" data-level="3.11.1" data-path="chapter-2.html"><a href="chapter-2.html#questions-1"><i class="fa fa-check"></i><b>3.11.1</b> Questions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chapter-3.html"><a href="chapter-3.html"><i class="fa fa-check"></i><b>4</b> Logit</a><ul>
<li class="chapter" data-level="4.1" data-path="chapter-3.html"><a href="chapter-3.html#modelling-choices"><i class="fa fa-check"></i><b>4.1</b> Modelling choices</a></li>
<li class="chapter" data-level="4.2" data-path="chapter-3.html"><a href="chapter-3.html#how-to-use-this-note-2"><i class="fa fa-check"></i><b>4.2</b> How to use this note</a></li>
<li class="chapter" data-level="4.3" data-path="chapter-3.html"><a href="chapter-3.html#learning-objectives-3"><i class="fa fa-check"></i><b>4.3</b> Learning objectives</a></li>
<li class="chapter" data-level="4.4" data-path="chapter-3.html"><a href="chapter-3.html#suggested-readings-2"><i class="fa fa-check"></i><b>4.4</b> Suggested readings</a></li>
<li class="chapter" data-level="4.5" data-path="chapter-3.html"><a href="chapter-3.html#preliminaries-1"><i class="fa fa-check"></i><b>4.5</b> Preliminaries</a></li>
<li class="chapter" data-level="4.6" data-path="chapter-3.html"><a href="chapter-3.html#once-again-those-random-terms"><i class="fa fa-check"></i><b>4.6</b> Once again those random terms</a></li>
<li class="chapter" data-level="4.7" data-path="chapter-3.html"><a href="chapter-3.html#now-about-those-parameters-mu-and-sigma"><i class="fa fa-check"></i><b>4.7</b> Now, about those parameters <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>…</a></li>
<li class="chapter" data-level="4.8" data-path="chapter-3.html"><a href="chapter-3.html#multinomial-logit"><i class="fa fa-check"></i><b>4.8</b> Multinomial logit</a></li>
<li class="chapter" data-level="4.9" data-path="chapter-3.html"><a href="chapter-3.html#properties-of-the-logit-model"><i class="fa fa-check"></i><b>4.9</b> Properties of the logit model</a></li>
<li class="chapter" data-level="4.10" data-path="chapter-3.html"><a href="chapter-3.html#revisiting-the-systematic-utilities"><i class="fa fa-check"></i><b>4.10</b> Revisiting the systematic utilities</a></li>
<li class="chapter" data-level="4.11" data-path="chapter-3.html"><a href="chapter-3.html#exercise-2"><i class="fa fa-check"></i><b>4.11</b> Exercise</a><ul>
<li class="chapter" data-level="4.11.1" data-path="chapter-3.html"><a href="chapter-3.html#questions-2"><i class="fa fa-check"></i><b>4.11.1</b> Questions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chapter-4.html"><a href="chapter-4.html"><i class="fa fa-check"></i><b>5</b> Practical issues in specification and estimation</a><ul>
<li class="chapter" data-level="5.1" data-path="chapter-4.html"><a href="chapter-4.html#theory-and-practice"><i class="fa fa-check"></i><b>5.1</b> Theory and practice</a></li>
<li class="chapter" data-level="5.2" data-path="chapter-4.html"><a href="chapter-4.html#how-to-use-this-note-3"><i class="fa fa-check"></i><b>5.2</b> How to use this note</a></li>
<li class="chapter" data-level="5.3" data-path="chapter-4.html"><a href="chapter-4.html#learning-objectives-4"><i class="fa fa-check"></i><b>5.3</b> Learning objectives</a></li>
<li class="chapter" data-level="5.4" data-path="chapter-4.html"><a href="chapter-4.html#suggested-readings-3"><i class="fa fa-check"></i><b>5.4</b> Suggested readings</a></li>
<li class="chapter" data-level="5.5" data-path="chapter-4.html"><a href="chapter-4.html#preliminaries-2"><i class="fa fa-check"></i><b>5.5</b> Preliminaries</a></li>
<li class="chapter" data-level="5.6" data-path="chapter-4.html"><a href="chapter-4.html#the-anatomy-of-utility-functions"><i class="fa fa-check"></i><b>5.6</b> The anatomy of utility functions</a></li>
<li class="chapter" data-level="5.7" data-path="chapter-4.html"><a href="chapter-4.html#example-specifying-the-utility-functions"><i class="fa fa-check"></i><b>5.7</b> Example: Specifying the utility functions</a></li>
<li class="chapter" data-level="5.8" data-path="chapter-4.html"><a href="chapter-4.html#estimation"><i class="fa fa-check"></i><b>5.8</b> Estimation</a></li>
<li class="chapter" data-level="5.9" data-path="chapter-4.html"><a href="chapter-4.html#example-a-logit-model-of-mode-choice"><i class="fa fa-check"></i><b>5.9</b> Example: A logit model of mode choice</a></li>
<li class="chapter" data-level="5.10" data-path="chapter-4.html"><a href="chapter-4.html#comparing-models-mcfaddens-rho2"><i class="fa fa-check"></i><b>5.10</b> Comparing models: McFadden’s <span class="math inline">\(\rho^2\)</span></a></li>
<li class="chapter" data-level="5.11" data-path="chapter-4.html"><a href="chapter-4.html#comparing-models-the-likelihood-ratio-test"><i class="fa fa-check"></i><b>5.11</b> Comparing models: the likelihood ratio test</a></li>
<li class="chapter" data-level="5.12" data-path="chapter-4.html"><a href="chapter-4.html#exercise-3"><i class="fa fa-check"></i><b>5.12</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chapter-5.html"><a href="chapter-5.html"><i class="fa fa-check"></i><b>6</b> Behavioral insights from choice models</a><ul>
<li class="chapter" data-level="6.1" data-path="chapter-5.html"><a href="chapter-5.html#inferring-and-forecasting-behavior"><i class="fa fa-check"></i><b>6.1</b> Inferring and forecasting behavior</a></li>
<li class="chapter" data-level="6.2" data-path="chapter-5.html"><a href="chapter-5.html#how-to-use-this-note-4"><i class="fa fa-check"></i><b>6.2</b> How to use this note</a></li>
<li class="chapter" data-level="6.3" data-path="chapter-5.html"><a href="chapter-5.html#learning-objectives-5"><i class="fa fa-check"></i><b>6.3</b> Learning objectives</a></li>
<li class="chapter" data-level="6.4" data-path="chapter-5.html"><a href="chapter-5.html#suggested-readings-4"><i class="fa fa-check"></i><b>6.4</b> Suggested readings</a></li>
<li class="chapter" data-level="6.5" data-path="chapter-5.html"><a href="chapter-5.html#preliminaries-3"><i class="fa fa-check"></i><b>6.5</b> Preliminaries</a></li>
<li class="chapter" data-level="6.6" data-path="chapter-5.html"><a href="chapter-5.html#the-meaning-of-the-coefficients"><i class="fa fa-check"></i><b>6.6</b> The meaning of the coefficients</a></li>
<li class="chapter" data-level="6.7" data-path="chapter-5.html"><a href="chapter-5.html#marginal-effects"><i class="fa fa-check"></i><b>6.7</b> Marginal effects</a><ul>
<li class="chapter" data-level="6.7.1" data-path="chapter-5.html"><a href="chapter-5.html#direct-marginal-effects"><i class="fa fa-check"></i><b>6.7.1</b> Direct marginal effects</a></li>
<li class="chapter" data-level="6.7.2" data-path="chapter-5.html"><a href="chapter-5.html#cross-marginal-effects"><i class="fa fa-check"></i><b>6.7.2</b> Cross-marginal effects</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="chapter-5.html"><a href="chapter-5.html#elasticity"><i class="fa fa-check"></i><b>6.8</b> Elasticity</a><ul>
<li class="chapter" data-level="6.8.1" data-path="chapter-5.html"><a href="chapter-5.html#direct-point-elasticity"><i class="fa fa-check"></i><b>6.8.1</b> Direct-point elasticity</a></li>
<li class="chapter" data-level="6.8.2" data-path="chapter-5.html"><a href="chapter-5.html#cross-point-elasticity"><i class="fa fa-check"></i><b>6.8.2</b> Cross-point elasticity</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="chapter-5.html"><a href="chapter-5.html#calculating-elasticities-based-on-an-mlogit-model"><i class="fa fa-check"></i><b>6.9</b> Calculating elasticities based on an <code>mlogit</code> model</a><ul>
<li class="chapter" data-level="6.9.1" data-path="chapter-5.html"><a href="chapter-5.html#computing-the-marginal-effects"><i class="fa fa-check"></i><b>6.9.1</b> Computing the marginal effects</a></li>
<li class="chapter" data-level="6.9.2" data-path="chapter-5.html"><a href="chapter-5.html#computing-the-elasticities"><i class="fa fa-check"></i><b>6.9.2</b> Computing the elasticities</a></li>
</ul></li>
<li class="chapter" data-level="6.10" data-path="chapter-5.html"><a href="chapter-5.html#a-note-about-attributes-in-dummy-format"><i class="fa fa-check"></i><b>6.10</b> A note about attributes in dummy format</a></li>
<li class="chapter" data-level="6.11" data-path="chapter-5.html"><a href="chapter-5.html#willingness-to-pay-and-discount-rate"><i class="fa fa-check"></i><b>6.11</b> Willingness to pay and discount rate</a></li>
<li class="chapter" data-level="6.12" data-path="chapter-5.html"><a href="chapter-5.html#simulating-market-changes"><i class="fa fa-check"></i><b>6.12</b> Simulating market changes</a><ul>
<li class="chapter" data-level="6.12.1" data-path="chapter-5.html"><a href="chapter-5.html#incentives"><i class="fa fa-check"></i><b>6.12.1</b> Incentives</a></li>
<li class="chapter" data-level="6.12.2" data-path="chapter-5.html"><a href="chapter-5.html#introduction-of-a-new-system"><i class="fa fa-check"></i><b>6.12.2</b> Introduction of a new system</a></li>
</ul></li>
<li class="chapter" data-level="6.13" data-path="chapter-5.html"><a href="chapter-5.html#exercise-4"><i class="fa fa-check"></i><b>6.13</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chapter-6.html"><a href="chapter-6.html"><i class="fa fa-check"></i><b>7</b> Non-Proportional Substitution Patterns I: Generalized Extreme Value Models</a><ul>
<li class="chapter" data-level="7.1" data-path="chapter-6.html"><a href="chapter-6.html#preliminaries-4"><i class="fa fa-check"></i><b>7.1</b> Preliminaries</a></li>
<li class="chapter" data-level="7.2" data-path="chapter-6.html"><a href="chapter-6.html#the-limits-of-perfection"><i class="fa fa-check"></i><b>7.2</b> The limits of perfection</a></li>
<li class="chapter" data-level="7.3" data-path="chapter-6.html"><a href="chapter-6.html#how-to-use-this-note-5"><i class="fa fa-check"></i><b>7.3</b> How to use this note</a></li>
<li class="chapter" data-level="7.4" data-path="chapter-6.html"><a href="chapter-6.html#learning-objectives-6"><i class="fa fa-check"></i><b>7.4</b> Learning objectives</a></li>
<li class="chapter" data-level="7.5" data-path="chapter-6.html"><a href="chapter-6.html#suggested-readings-5"><i class="fa fa-check"></i><b>7.5</b> Suggested readings</a></li>
<li class="chapter" data-level="7.6" data-path="chapter-6.html"><a href="chapter-6.html#generalized-extreme-value-models-a-recipe-for-deriving-discrete-choice-models"><i class="fa fa-check"></i><b>7.6</b> Generalized Extreme Value models: a recipe for deriving discrete choice models</a></li>
<li class="chapter" data-level="7.7" data-path="chapter-6.html"><a href="chapter-6.html#nested-logit-model"><i class="fa fa-check"></i><b>7.7</b> Nested Logit model</a></li>
<li class="chapter" data-level="7.8" data-path="chapter-6.html"><a href="chapter-6.html#properties-of-the-nested-logit-model"><i class="fa fa-check"></i><b>7.8</b> Properties of the nested logit model</a></li>
<li class="chapter" data-level="7.9" data-path="chapter-6.html"><a href="chapter-6.html#estimation-of-the-nested-logit-model"><i class="fa fa-check"></i><b>7.9</b> Estimation of the nested logit model</a></li>
<li class="chapter" data-level="7.10" data-path="chapter-6.html"><a href="chapter-6.html#substitution-patterns-with-the-nested-logit-model"><i class="fa fa-check"></i><b>7.10</b> Substitution patterns with the nested logit model</a></li>
<li class="chapter" data-level="7.11" data-path="chapter-6.html"><a href="chapter-6.html#elasticities-of-the-nested-logit-model"><i class="fa fa-check"></i><b>7.11</b> Elasticities of the nested logit model</a></li>
<li class="chapter" data-level="7.12" data-path="chapter-6.html"><a href="chapter-6.html#exercise-5"><i class="fa fa-check"></i><b>7.12</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chapter-7.html"><a href="chapter-7.html"><i class="fa fa-check"></i><b>8</b> Non-Proportional Substitution Patterns I: The Probit Model</a><ul>
<li class="chapter" data-level="8.1" data-path="chapter-7.html"><a href="chapter-7.html#preliminaries-5"><i class="fa fa-check"></i><b>8.1</b> Preliminaries</a></li>
<li class="chapter" data-level="8.2" data-path="chapter-7.html"><a href="chapter-7.html#more-flexible-substitution-patterns"><i class="fa fa-check"></i><b>8.2</b> More flexible substitution patterns</a></li>
<li class="chapter" data-level="8.3" data-path="chapter-7.html"><a href="chapter-7.html#how-to-use-this-note-6"><i class="fa fa-check"></i><b>8.3</b> How to use this note</a></li>
<li class="chapter" data-level="8.4" data-path="chapter-7.html"><a href="chapter-7.html#learning-objectives-7"><i class="fa fa-check"></i><b>8.4</b> Learning objectives</a></li>
<li class="chapter" data-level="8.5" data-path="chapter-7.html"><a href="chapter-7.html#suggested-readings-6"><i class="fa fa-check"></i><b>8.5</b> Suggested readings</a></li>
<li class="chapter" data-level="8.6" data-path="chapter-7.html"><a href="chapter-7.html#probit-model"><i class="fa fa-check"></i><b>8.6</b> Probit model</a></li>
<li class="chapter" data-level="8.7" data-path="chapter-7.html"><a href="chapter-7.html#exercise-6"><i class="fa fa-check"></i><b>8.7</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chapter-8.html"><a href="chapter-8.html"><i class="fa fa-check"></i><b>9</b> Dealing with Heterogeneity I: The Mixed Logit Model</a><ul>
<li class="chapter" data-level="9.1" data-path="chapter-8.html"><a href="chapter-8.html#preliminaries-6"><i class="fa fa-check"></i><b>9.1</b> Preliminaries</a></li>
<li class="chapter" data-level="9.2" data-path="chapter-8.html"><a href="chapter-8.html#taste-variations-in-the-population"><i class="fa fa-check"></i><b>9.2</b> Taste variations in the population</a></li>
<li class="chapter" data-level="9.3" data-path="chapter-8.html"><a href="chapter-8.html#how-to-use-this-note-7"><i class="fa fa-check"></i><b>9.3</b> How to use this note</a></li>
<li class="chapter" data-level="9.4" data-path="chapter-8.html"><a href="chapter-8.html#learning-objectives-8"><i class="fa fa-check"></i><b>9.4</b> Learning objectives</a></li>
<li class="chapter" data-level="9.5" data-path="chapter-8.html"><a href="chapter-8.html#suggested-readings-7"><i class="fa fa-check"></i><b>9.5</b> Suggested readings</a></li>
<li class="chapter" data-level="9.6" data-path="chapter-8.html"><a href="chapter-8.html#mixed-logit"><i class="fa fa-check"></i><b>9.6</b> Mixed logit</a></li>
<li class="chapter" data-level="9.7" data-path="chapter-8.html"><a href="chapter-8.html#estimation-1"><i class="fa fa-check"></i><b>9.7</b> Estimation</a></li>
<li class="chapter" data-level="9.8" data-path="chapter-8.html"><a href="chapter-8.html#practical-example"><i class="fa fa-check"></i><b>9.8</b> Practical example</a></li>
<li class="chapter" data-level="9.9" data-path="chapter-8.html"><a href="chapter-8.html#behavioral-insights-from-the-mixed-logit-model"><i class="fa fa-check"></i><b>9.9</b> Behavioral insights from the mixed logit model</a><ul>
<li class="chapter" data-level="9.9.1" data-path="chapter-8.html"><a href="chapter-8.html#unconditional-distribution-of-a-random-parameter"><i class="fa fa-check"></i><b>9.9.1</b> Unconditional distribution of a random parameter</a></li>
<li class="chapter" data-level="9.9.2" data-path="chapter-8.html"><a href="chapter-8.html#conditional-distribution-of-the-random-coefficients"><i class="fa fa-check"></i><b>9.9.2</b> Conditional distribution of the random coefficients</a></li>
</ul></li>
<li class="chapter" data-level="9.10" data-path="chapter-8.html"><a href="chapter-8.html#using-covariates-to-capture-variations-in-taste"><i class="fa fa-check"></i><b>9.10</b> Using covariates to capture variations in taste</a></li>
<li class="chapter" data-level="9.11" data-path="chapter-8.html"><a href="chapter-8.html#revisiting-the-example"><i class="fa fa-check"></i><b>9.11</b> Revisiting the example</a></li>
<li class="chapter" data-level="9.12" data-path="chapter-8.html"><a href="chapter-8.html#full-covariance-matrix-for-random-components"><i class="fa fa-check"></i><b>9.12</b> Full covariance matrix for random components</a></li>
<li class="chapter" data-level="9.13" data-path="chapter-8.html"><a href="chapter-8.html#final-remarks"><i class="fa fa-check"></i><b>9.13</b> Final remarks</a></li>
<li class="chapter" data-level="9.14" data-path="chapter-8.html"><a href="chapter-8.html#exercise-7"><i class="fa fa-check"></i><b>9.14</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chapter-9.html"><a href="chapter-9.html"><i class="fa fa-check"></i><b>10</b> Dealing with Heterogeneity II: The Latent Class Logit Model</a><ul>
<li class="chapter" data-level="10.1" data-path="chapter-9.html"><a href="chapter-9.html#preliminaries-7"><i class="fa fa-check"></i><b>10.1</b> Preliminaries</a></li>
<li class="chapter" data-level="10.2" data-path="chapter-9.html"><a href="chapter-9.html#more-on-taste-variation"><i class="fa fa-check"></i><b>10.2</b> More on taste variation</a></li>
<li class="chapter" data-level="10.3" data-path="chapter-9.html"><a href="chapter-9.html#how-to-use-this-note-8"><i class="fa fa-check"></i><b>10.3</b> How to use this note</a></li>
<li class="chapter" data-level="10.4" data-path="chapter-9.html"><a href="chapter-9.html#learning-objectives-9"><i class="fa fa-check"></i><b>10.4</b> Learning objectives</a></li>
<li class="chapter" data-level="10.5" data-path="chapter-9.html"><a href="chapter-9.html#suggested-readings-8"><i class="fa fa-check"></i><b>10.5</b> Suggested readings</a></li>
<li class="chapter" data-level="10.6" data-path="chapter-9.html"><a href="chapter-9.html#latent-class-logit"><i class="fa fa-check"></i><b>10.6</b> Latent class logit</a></li>
<li class="chapter" data-level="10.7" data-path="chapter-9.html"><a href="chapter-9.html#estimation-2"><i class="fa fa-check"></i><b>10.7</b> Estimation</a></li>
<li class="chapter" data-level="10.8" data-path="chapter-9.html"><a href="chapter-9.html#properties-of-the-latent-class-logit-model"><i class="fa fa-check"></i><b>10.8</b> Properties of the latent class logit model</a></li>
<li class="chapter" data-level="10.9" data-path="chapter-9.html"><a href="chapter-9.html#empirical-example"><i class="fa fa-check"></i><b>10.9</b> Empirical example</a></li>
<li class="chapter" data-level="10.10" data-path="chapter-9.html"><a href="chapter-9.html#adding-individual-level-attributes"><i class="fa fa-check"></i><b>10.10</b> Adding individual-level attributes</a></li>
<li class="chapter" data-level="10.11" data-path="chapter-9.html"><a href="chapter-9.html#adding-variables-to-the-latent-class-selection-model"><i class="fa fa-check"></i><b>10.11</b> Adding variables to the latent class selection model</a></li>
<li class="chapter" data-level="10.12" data-path="chapter-9.html"><a href="chapter-9.html#exercise-8"><i class="fa fa-check"></i><b>10.12</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chapter-10.html"><a href="chapter-10.html"><i class="fa fa-check"></i><b>11</b> Ordinal and Ranked Responses</a><ul>
<li class="chapter" data-level="11.1" data-path="chapter-10.html"><a href="chapter-10.html#preliminaries-8"><i class="fa fa-check"></i><b>11.1</b> Preliminaries</a></li>
<li class="chapter" data-level="11.2" data-path="chapter-10.html"><a href="chapter-10.html#more-on-taste-variation-1"><i class="fa fa-check"></i><b>11.2</b> More on taste variation</a></li>
<li class="chapter" data-level="11.3" data-path="chapter-10.html"><a href="chapter-10.html#how-to-use-this-note-9"><i class="fa fa-check"></i><b>11.3</b> How to use this note</a></li>
<li class="chapter" data-level="11.4" data-path="chapter-10.html"><a href="chapter-10.html#learning-objectives-10"><i class="fa fa-check"></i><b>11.4</b> Learning objectives</a></li>
<li class="chapter" data-level="11.5" data-path="chapter-10.html"><a href="chapter-10.html#suggested-readings-9"><i class="fa fa-check"></i><b>11.5</b> Suggested readings</a></li>
<li class="chapter" data-level="11.6" data-path="chapter-10.html"><a href="chapter-10.html#latent-class-logit-1"><i class="fa fa-check"></i><b>11.6</b> Latent class logit</a></li>
<li class="chapter" data-level="11.7" data-path="chapter-10.html"><a href="chapter-10.html#estimation-3"><i class="fa fa-check"></i><b>11.7</b> Estimation</a></li>
<li class="chapter" data-level="11.8" data-path="chapter-10.html"><a href="chapter-10.html#properties-of-the-latent-class-logit-model-1"><i class="fa fa-check"></i><b>11.8</b> Properties of the latent class logit model</a></li>
<li class="chapter" data-level="11.9" data-path="chapter-10.html"><a href="chapter-10.html#empirical-example-1"><i class="fa fa-check"></i><b>11.9</b> Empirical example</a></li>
<li class="chapter" data-level="11.10" data-path="chapter-10.html"><a href="chapter-10.html#adding-individual-level-attributes-1"><i class="fa fa-check"></i><b>11.10</b> Adding individual-level attributes</a></li>
<li class="chapter" data-level="11.11" data-path="chapter-10.html"><a href="chapter-10.html#adding-variables-to-the-latent-class-selection-model-1"><i class="fa fa-check"></i><b>11.11</b> Adding variables to the latent class selection model</a></li>
<li class="chapter" data-level="11.12" data-path="chapter-10.html"><a href="chapter-10.html#exercise-9"><i class="fa fa-check"></i><b>11.12</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An Introduction to Discrete Choice Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chapter-5" class="section level1">
<h1><span class="header-section-number">Chapter 6</span> Behavioral insights from choice models</h1>
<blockquote>
<p>“Men’s actions are the best guides to their thoughts.”</p>
<p>— John Locke, An Essay Concerning - Volume I</p>
</blockquote>
<blockquote>
<p>“Prediction is not proof.”</p>
<p>— King and Kraemer, Models, facts, and the policy process: the political ecology of estimated truth</p>
</blockquote>
<blockquote>
<p>“Human behavior is incredibly pliable, plastic.”</p>
<p>— Philip Zimbardo</p>
</blockquote>
<div id="inferring-and-forecasting-behavior" class="section level2">
<h2><span class="header-section-number">6.1</span> Inferring and forecasting behavior</h2>
<p>In Chapter <a href="chapter-5.html#chapter-5">6</a> you learned some important practical aspects needed to estimate the logit model. Many of those aspects transfer to other kinds of discrete choice models as well. Now that you have the practical skills to estimate a model, we can take the opportunity to see how the model can be used to infer behavior.</p>
<p>In the preceding chapters we have made the assumption that an observer/analyst cannot know the state of mind of the decision-maker, and that a model is a way to infer the decision-making mechanisms based on what people do (or say they would do - more on this in a latter chapter.) Once this has been achieved, what is a model good for?</p>
<p>In addition to providing a plausible description of the decision-making mechanism of interest, a model can be used to examine how behavior <em>might</em> change if the conditions of the decision-making situation changed. McFadden, in one of the seminal papers on discrete choice analysis <span class="citation">(see McFadden <a href="#ref-McFadden1974measurement" role="doc-biblioref">1974</a>)</span>, is concerned with travel demand forecasting. The basis for this is a model of mode choice that helps to tease out the factors that influence the choice between car and bus as a mode for commuting to work. Once that this model was estimated, McFadden was interested in the level of demand of a new mode, a rail system called BART (Bay Area Rail Transit). This system had not been built yet, and so obtaining estimates of level of demand was an important part of policy analysis. In other words, McFadden was interested in how behavior <em>might</em> change with the introduction of a new mode of transportation. What would be the demand for the new mode at a certain fare? If fares changed? If waiting times for BART were longer or shorter? And so on.</p>
<p>You will hopefully become familiar with this process:</p>
<ol style="list-style-type: decimal">
<li>Estimate and select a plausible model for the behavior of interest.</li>
<li>Analyze scenarios: what would happen if?</li>
</ol>
<p>This process is valuable in several ways <span class="citation">(King and Kraemer <a href="#ref-King1993models" role="doc-biblioref">1993</a>)</span>. <strong>First</strong>, it helps to clarify issues that are of policy interest (p. 365). Modelers need to document their assumptions, specification choices, and so on, resulting in a systematic approach of simplification (and remember, all models are wrong, but some are useful). <strong>Secondly</strong>, the modeling process and subsequently the use of models, help to enforce discipline in analysis and discourse. The behavior of models is to some extent limited by their mechanics, and the results should reflect this. For example, incremental changes in the inputs should result in plausible changes in the predictions. Making predictions outside of the calibration range of the model (beyond the range of values of variables used to estimate the model) will likely result in predictions that are implausibly out of bounds. As King and Kraemer note <span class="citation">(<a href="#ref-King1993models" role="doc-biblioref">1993</a>)</span> “the results of radical changes are unlikely to be predicted accurately by models based on the performance under the status quo” (p. 365).And models when used to analyze scenarios, provide cautionary advice on <em>what not to do</em> by revealing the possible consequences of a bad policy. In this way, models can help inform policy-makers about the range of possible outcomes and whether these outcomes are in a sense in some “acceptable range” <span class="citation">(King and Kraemer <a href="#ref-King1993models" role="doc-biblioref">1993</a>, 365–66)</span>. In other words, models help to probe the limits of the plasticity of human behavior.</p>
<p>We will explore the preceding issues in this chapter, looking at different ways to derive behavioral insights based on models of choices.</p>
</div>
<div id="how-to-use-this-note-4" class="section level2">
<h2><span class="header-section-number">6.2</span> How to use this note</h2>
<p>Remember that the source for the document you are reading is an R Notebook. Throughout the notes, you will find examples of code in segments of text called <em>chunks</em>. This is an example of a chunk:</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb130-1" title="1"><span class="kw">print</span>(<span class="st">&quot;Are these the shadows of the things that Will be, or are they shadows of the things that May be only?&quot;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;Are these the shadows of the things that Will be, or are they shadows of the things that May be only?&quot;</code></pre>
<p>If you are working with the Notebook version of the document, you can run the code by clicking the ‘play’ icon on the top right corner of the chunk. If you are reading the web-book version of the document, you will often see that the code has already been executed. You can still try it by copying and pasting into your R or RStudio console.</p>
</div>
<div id="learning-objectives-5" class="section level2">
<h2><span class="header-section-number">6.3</span> Learning objectives</h2>
<p>In this practice, you will learn about:</p>
<ol style="list-style-type: decimal">
<li>The meaning of the coefficients of a model.</li>
<li>The concept of marginal effects.</li>
<li>The concept of elasticity.</li>
<li>The concept of willingness to pay.</li>
<li>How to simulate outcomes.</li>
</ol>
</div>
<div id="suggested-readings-4" class="section level2">
<h2><span class="header-section-number">6.4</span> Suggested readings</h2>
<ul>
<li>Ben-Akiva, M. Lerman, <span class="citation">(<a href="#ref-Benakiva1985discrete" role="doc-biblioref">1985</a>)</span> Discrete Choice Analysis: Theory and Applications to Travel Demand, <strong>Chapter 5, pp. 111-113</strong>, MIT Press.</li>
<li>Hensher, D.A., Rose, J.M., Greene, W.H <span class="citation">(<a href="#ref-hensher2005applied" role="doc-biblioref">2005</a>)</span> Applied Choice Analysis: A Primer, <strong>Chapter 11</strong>, Cambridge University Press.</li>
<li>King, J.L., Kraemer, K.L. <span class="citation">(<a href="#ref-King1993models" role="doc-biblioref">1993</a>)</span> <a href="https://cloudfront.escholarship.org/dist/prd/content/qt1c31s58g/qt1c31s58g.pdf">Models, facts, and the policy process: the political ecology of estimated truth</a>. In: Environmental Modelling with GIS, Eds. Goodchild, M., Parks, B.O., Stayaert, L.T., Oxford University Press.</li>
<li>Ortuzar JD, Willumsen LG <span class="citation">(<a href="#ref-Ortuzar2011modelling" role="doc-biblioref">2011</a>)</span> Modelling Transport, Fourth Edition, <strong>Chapter 2, pp. 43-44 and </strong>, John Wiley and Sons.</li>
<li>Train <span class="citation">(<a href="#ref-Train2009discrete" role="doc-biblioref">2009</a>)</span> Discrete Choice Methods with Simulation, Second Edition, <strong>Chapter 2, pp. 29-31</strong>, Cambridge University Press.</li>
</ul>
</div>
<div id="preliminaries-3" class="section level2">
<h2><span class="header-section-number">6.5</span> Preliminaries</h2>
<p>Load the packages used in this section:</p>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb132-1" title="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb132-2" title="2"><span class="kw">library</span>(evd)</a>
<a class="sourceLine" id="cb132-3" title="3"><span class="kw">library</span>(mlogit)</a>
<a class="sourceLine" id="cb132-4" title="4"><span class="kw">library</span>(kableExtra)</a></code></pre></div>
<p>Load the dataset used in this section (from the <code>mlogit</code> package):</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb133-1" title="1"><span class="kw">data</span>(<span class="st">&quot;Heating&quot;</span>)</a></code></pre></div>
<p>This dataset includes choices by a sample of consumers in California with respect to different heating systems. In-depth analysis of this dataset was conducted by Train and Croissant <span class="citation">(<a href="#ref-Train2012mlogit" role="doc-biblioref">2012</a>)</span> in a document available <a href="http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.224.6569&amp;rep=rep1&amp;type=pdf">here</a>.</p>
<p>Five heating systems are considered in this choice problem:</p>
<ul>
<li>Gas Central (gc)</li>
<li>Gas Room (gr)</li>
<li>Electric Central (ec)</li>
<li>Electric Room (er)</li>
<li>Heat Pump (hp)</li>
</ul>
<p>These heating systems differ in terms of their installation cost (ic) and annual operation cost (oc). See the following table with the median installation cost, annual operation costs, and proportion of choices in sample:</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb134-1" title="1">Proportion &lt;-<span class="st"> </span>Heating <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb134-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(depvar) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb134-3" title="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">no_rows =</span> <span class="kw">length</span>(depvar))</a>
<a class="sourceLine" id="cb134-4" title="4"></a>
<a class="sourceLine" id="cb134-5" title="5">df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">System =</span> <span class="kw">c</span>(<span class="st">&quot;Gas Central&quot;</span>, <span class="st">&quot;Gas Room&quot;</span>, <span class="st">&quot;Electric Central&quot;</span>, <span class="st">&quot;Electric Room&quot;</span>, <span class="st">&quot;Heat Pump&quot;</span>),</a>
<a class="sourceLine" id="cb134-6" title="6">                 <span class="dt">Installation =</span> <span class="kw">c</span>(<span class="kw">median</span>(Heating<span class="op">$</span>ic.gc), <span class="kw">median</span>(Heating<span class="op">$</span>ic.gr), <span class="kw">median</span>(Heating<span class="op">$</span>ic.ec), <span class="kw">median</span>(Heating<span class="op">$</span>ic.er), <span class="kw">median</span>(Heating<span class="op">$</span>ic.hp)),</a>
<a class="sourceLine" id="cb134-7" title="7">                 <span class="dt">Operation =</span> <span class="kw">c</span>(<span class="kw">median</span>(Heating<span class="op">$</span>oc.gc), <span class="kw">median</span>(Heating<span class="op">$</span>oc.gr), <span class="kw">median</span>(Heating<span class="op">$</span>oc.ec), <span class="kw">median</span>(Heating<span class="op">$</span>oc.er), <span class="kw">median</span>(Heating<span class="op">$</span>oc.hp)),</a>
<a class="sourceLine" id="cb134-8" title="8">                 <span class="dt">Proportion =</span> Proportion<span class="op">$</span>no_rows<span class="op">/</span><span class="dv">900</span></a>
<a class="sourceLine" id="cb134-9" title="9">                 )</a>
<a class="sourceLine" id="cb134-10" title="10">df <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb134-11" title="11"><span class="st">  </span><span class="kw">kable</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb134-12" title="12"><span class="st">  </span><span class="kw">kable_styling</span>()</a></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
System
</th>
<th style="text-align:right;">
Installation
</th>
<th style="text-align:right;">
Operation
</th>
<th style="text-align:right;">
Proportion
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Gas Central
</td>
<td style="text-align:right;">
778.505
</td>
<td style="text-align:right;">
172.105
</td>
<td style="text-align:right;">
0.6366667
</td>
</tr>
<tr>
<td style="text-align:left;">
Gas Room
</td>
<td style="text-align:right;">
924.305
</td>
<td style="text-align:right;">
154.110
</td>
<td style="text-align:right;">
0.1433333
</td>
</tr>
<tr>
<td style="text-align:left;">
Electric Central
</td>
<td style="text-align:right;">
824.840
</td>
<td style="text-align:right;">
480.055
</td>
<td style="text-align:right;">
0.0711111
</td>
</tr>
<tr>
<td style="text-align:left;">
Electric Room
</td>
<td style="text-align:right;">
989.700
</td>
<td style="text-align:right;">
430.665
</td>
<td style="text-align:right;">
0.0933333
</td>
</tr>
<tr>
<td style="text-align:left;">
Heat Pump
</td>
<td style="text-align:right;">
1046.550
</td>
<td style="text-align:right;">
220.845
</td>
<td style="text-align:right;">
0.0555556
</td>
</tr>
</tbody>
</table>
<p>In addition, the dataset also includes some information about the consumers, including income, age of household head, number of rooms in the house, and region in California:</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb135-1" title="1"><span class="kw">summary</span>(Heating[,<span class="dv">13</span><span class="op">:</span><span class="dv">16</span>]) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb135-2" title="2"><span class="st">  </span><span class="kw">kable</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb135-3" title="3"><span class="st">  </span><span class="kw">kable_styling</span>()</a></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
income
</th>
<th style="text-align:left;">
agehed
</th>
<th style="text-align:left;">
rooms
</th>
<th style="text-align:left;">
region
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
Min. :2.000
</td>
<td style="text-align:left;">
Min. :20.00
</td>
<td style="text-align:left;">
Min. :2.000
</td>
<td style="text-align:left;">
valley:177
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
1st Qu.:3.000
</td>
<td style="text-align:left;">
1st Qu.:30.00
</td>
<td style="text-align:left;">
1st Qu.:3.000
</td>
<td style="text-align:left;">
scostl:361
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
Median :5.000
</td>
<td style="text-align:left;">
Median :45.00
</td>
<td style="text-align:left;">
Median :4.000
</td>
<td style="text-align:left;">
mountn:102
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
Mean :4.641
</td>
<td style="text-align:left;">
Mean :42.94
</td>
<td style="text-align:left;">
Mean :4.424
</td>
<td style="text-align:left;">
ncostl:260
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
3rd Qu.:6.000
</td>
<td style="text-align:left;">
3rd Qu.:55.00
</td>
<td style="text-align:left;">
3rd Qu.:6.000
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
Max. :7.000
</td>
<td style="text-align:left;">
Max. :65.00
</td>
<td style="text-align:left;">
Max. :7.000
</td>
<td style="text-align:left;">
NA
</td>
</tr>
</tbody>
</table>
<p>The dataset is in “wide” form, which means that there is one record per decision making unit (i.e. per household). The package <code>mlogit</code> works with data in “long” format, and fortunately (since changing the format of the dataset is a tedious if fairly elementary process), there is a function for changing the format:</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb136-1" title="1">H &lt;-<span class="st"> </span><span class="kw">mlogit.data</span>(Heating, <span class="dt">shape =</span> <span class="st">&quot;wide&quot;</span>, <span class="dt">choice =</span> <span class="st">&quot;depvar&quot;</span>, <span class="dt">varying =</span> <span class="kw">c</span>(<span class="dv">3</span><span class="op">:</span><span class="dv">12</span>))</a></code></pre></div>
<p>The argument <code>varying</code> lets the function know that the variables in the columns 3 through 13 in the dataframe are alternative-specific, and therefore vary across utility functions. Once that the format of the table has been changed from “wide” to “long”, the number of rows changes from <span class="math inline">\(900\)</span> (the number of decision makers) to <span class="math inline">\(4500\)</span>: this is the number of decision makers (<span class="math inline">\(900\)</span>) times the number of alternatives (<span class="math inline">\(5\)</span>).</p>
<p>Before estimating an initial model, we need to define the utility functions that we wish to estimate. Since there are five alternatives, we define the following five functions (with heat pump as the reference level):
<span class="math display">\[
\begin{array}{ccc}
V_{\text{ec}} = &amp; 0 &amp; + \beta_1\text{ic.ec}\\
V_{\text{er}} = &amp; \beta_{er} &amp; + \beta_1\text{ic.er}\\
V_{\text{gc}} = &amp; \beta_{gc} &amp; + \beta_1\text{ic.gc}\\
V_{\text{gr}} = &amp; \beta_{gr} &amp; + \beta_1\text{ic.gr}\\
V_{\text{hp}} = &amp; \beta_{hp} &amp; + \beta_1\text{ic.hp}\\
\end{array}
\]</span></p>
<p>These functions include only the instalation cost of the systems (ic). The <code>mlogit</code> function can be used to estimate this model (call this Model 1), using the electric central system (“ec”) as the reference level:</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb137-1" title="1">mod1 &lt;-<span class="st"> </span><span class="kw">mlogit</span>(depvar <span class="op">~</span><span class="st"> </span>ic, H, <span class="dt">reflevel =</span> <span class="st">&quot;ec&quot;</span>)</a>
<a class="sourceLine" id="cb137-2" title="2"><span class="kw">summary</span>(mod1)</a></code></pre></div>
<pre><code>## 
## Call:
## mlogit(formula = depvar ~ ic, data = H, reflevel = &quot;ec&quot;, method = &quot;nr&quot;)
## 
## Frequencies of alternatives:
##       ec       er       gc       gr       hp 
## 0.071111 0.093333 0.636667 0.143333 0.055556 
## 
## nr method
## 6 iterations, 0h:0m:0s 
## g&#39;(-H)^-1g = 1.02E-05 
## successive function values within tolerance limits 
## 
## Coefficients :
##                   Estimate  Std. Error z-value  Pr(&gt;|z|)    
## er:(intercept)  0.53681271  0.19194838  2.7967  0.005164 ** 
## gc:(intercept)  2.11877361  0.13413083 15.7963 &lt; 2.2e-16 ***
## gr:(intercept)  0.86420949  0.16435236  5.2583 1.454e-07 ***
## hp:(intercept)  0.12259544  0.23188795  0.5287  0.597025    
## ic             -0.00168108  0.00061843 -2.7183  0.006561 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Log-Likelihood: -1018.5
## McFadden R^2:  0.0036292 
## Likelihood ratio test : chisq = 7.4197 (p.value = 0.0064514)</code></pre>
</div>
<div id="the-meaning-of-the-coefficients" class="section level2">
<h2><span class="header-section-number">6.6</span> The meaning of the coefficients</h2>
<p>The coefficients of a discrete choice model are informative because they modulate the effect of various variables on the probabilities of selecting alternatives. In addition, they also can be used to understand how decision-makers trade-off different attributes.</p>
<p>The first thing to note is the sign of the coefficients. In the case of the binomial and multinomial logit model, the signs of the coefficients are informative because they tell us something about how the utility is affected by an attribute (either of the alternatives or the decision-maker). A positive sign indicates that the utility increases as the attribute increases. For instance, when considering mobile phones, we would expect speed to increase the utility of the alternatives. On the other hand, we would expect the price of the mobile phones to decrease their utility: the higher the cost, the lower the utility derived from an alternative. In this case, the expected sign of the coefficient for price would be negative.</p>
<p>Inspecting the results of Model 0, we notice that the sign of the coefficient for installation costs is negative; this implies that the utility of a system tends to decrease as the installation cost increases. Not surprisingly, since central gas systems have the lowest installation costs, they are also the most popular, whereas heat pumps, with the highest installation costs, are the least popular.</p>
<p>Alas, beyond this qualitative assessment of the signs of the coefficients, their magnitudes are not directly interpretable.</p>
<p>Recall that underlying the logit models is a sigmoid relationship between the probabilities and the <em>differences in attributes</em> among utility functions. As discussed in Chapter <a href="chapter-3.html#chapter-3">4</a>, the effect on the probability of choosing an alternative, given a change on some attribute, is not constant along the logit probability curve, and in fact depends on the initial value of the variable, as seen in Figure <a href="chapter-3.html#fig:fig-logistic-shape-implication">4.5</a>) below.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb139-1" title="1"><span class="co"># Create a data frame for plotting</span></a>
<a class="sourceLine" id="cb139-2" title="2">df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">x =</span><span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">-5</span>, <span class="dt">to =</span> <span class="dv">5</span>, <span class="dt">by =</span> <span class="fl">0.01</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">y =</span> <span class="kw">plogis</span>(x))</a>
<a class="sourceLine" id="cb139-3" title="3"></a>
<a class="sourceLine" id="cb139-4" title="4"><span class="co"># Plot</span></a>
<a class="sourceLine" id="cb139-5" title="5">logit_plot &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">data =</span> df, <span class="kw">aes</span>(x, y)) <span class="op">+</span></a>
<a class="sourceLine" id="cb139-6" title="6"><span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="op">+</span><span class="st">  </span><span class="co"># Plot cumulative distribution function</span></a>
<a class="sourceLine" id="cb139-7" title="7"><span class="st">  </span><span class="kw">ylim</span>(<span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="op">+</span><span class="st"> </span><span class="co"># Set the limits of the y axis</span></a>
<a class="sourceLine" id="cb139-8" title="8"><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>) <span class="op">+</span><span class="st"> </span><span class="co"># Add y axis</span></a>
<a class="sourceLine" id="cb139-9" title="9"><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="dv">0</span>) <span class="co"># Add x axis</span></a>
<a class="sourceLine" id="cb139-10" title="10"></a>
<a class="sourceLine" id="cb139-11" title="11">logit_plot <span class="op">+</span></a>
<a class="sourceLine" id="cb139-12" title="12"><span class="st">  </span><span class="kw">xlab</span>(<span class="kw">expression</span>(<span class="kw">paste</span>(V[j], <span class="st">&quot; - &quot;</span>, V[i], <span class="dt">sep=</span><span class="st">&quot;&quot;</span>))) <span class="op">+</span><span class="st"> </span><span class="co"># Label the x axis</span></a>
<a class="sourceLine" id="cb139-13" title="13"><span class="st">  </span><span class="kw">ylab</span>(<span class="kw">expression</span>(<span class="kw">paste</span>(P[j]))) <span class="op">+</span><span class="st"> </span><span class="co"># Label the y axis</span></a>
<a class="sourceLine" id="cb139-14" title="14"><span class="st">  </span><span class="kw">annotate</span>(<span class="st">&quot;segment&quot;</span>, <span class="dt">x =</span> <span class="fl">-3.75</span>, <span class="dt">xend =</span> <span class="fl">-2.5</span>, <span class="dt">y =</span> <span class="fl">0.024</span>, <span class="dt">yend =</span> <span class="fl">0.024</span>, <span class="dt">colour =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">linetype =</span> <span class="st">&quot;solid&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb139-15" title="15"><span class="st">  </span><span class="kw">annotate</span>(<span class="st">&quot;segment&quot;</span>, <span class="dt">x =</span> <span class="fl">-2.5</span>, <span class="dt">xend =</span> <span class="fl">-2.5</span>, <span class="dt">y =</span> <span class="fl">0.024</span>, <span class="dt">yend =</span> <span class="fl">0.075</span>, <span class="dt">colour =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">linetype =</span> <span class="st">&quot;solid&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb139-16" title="16"><span class="st">  </span><span class="kw">annotate</span>(<span class="st">&quot;segment&quot;</span>, <span class="dt">x =</span> <span class="dv">0</span>, <span class="dt">xend =</span> <span class="fl">1.25</span>, <span class="dt">y =</span> <span class="fl">0.5</span>, <span class="dt">yend =</span> <span class="fl">0.5</span>, <span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb139-17" title="17"><span class="st">  </span><span class="kw">annotate</span>(<span class="st">&quot;segment&quot;</span>, <span class="dt">x =</span> <span class="fl">1.25</span>, <span class="dt">xend =</span> <span class="fl">1.25</span>, <span class="dt">y =</span> <span class="fl">0.5</span>, <span class="dt">yend =</span> <span class="fl">0.77</span>, <span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">linetype =</span> <span class="st">&quot;dashed&quot;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:fig-logistic-non-linear"></span>
<img src="bookdown-demo_files/figure-html/fig-logistic-non-linear-1.png" alt="\label{fig:fig-logistic-non-linear}The logit probability is not linear on the variables" width="672" />
<p class="caption">
Figure 6.1: The logit probability is not linear on the variables
</p>
</div>
<p>A number of different techniques are available instead to assess the behavioral implications of changes in some of the attributes. We will cover some relevant techniques next.</p>
</div>
<div id="marginal-effects" class="section level2">
<h2><span class="header-section-number">6.7</span> Marginal effects</h2>
<p>A marginal effect is a summary measure of the amount of change in a dependent variable <span class="math inline">\(y\)</span> when an independent variable <span class="math inline">\(x_k\)</span> changes by one unit:</p>
<p><span class="math display">\[
M^y_{x_k}=\frac{\partial y}{\partial x_k}
\]</span></p>
<p>In the case of discrete choice models, the dependent variable that we are interested in is the probability of choosing alternative $j. Louviere et al. <span class="citation">(<a href="#ref-Louviere2000stated" role="doc-biblioref">2000</a>, 58–59)</span> show that, given a discrete choice model, the marginal effect is:</p>
<p><span class="math display">\[
M^{P_{in}}_{x_{jnk}} = \beta_{k}(\delta_{ij}-P_{jn})
\]</span>
where <span class="math inline">\(P_{jn}\)</span> is the probability of decision-maker <span class="math inline">\(n\)</span> selecting alternative <span class="math inline">\(j\)</span> and <span class="math inline">\(\beta_{jk}\)</span> is the coefficient that corresponds to variable <span class="math inline">\(x_{jnk}\)</span>. This measures the change in probability as a result of a one-unit change in the units of <span class="math inline">\(x_{jnk}\)</span>.</p>
<p>Two cases result from this expression:</p>
<p><span class="math display">\[
\begin{array}{c}
\text{1. When }i = j\text{ then }\delta_{ii} = 1 \text{ (this is called a direct marginal effect)}\\
\text{2. When }i \ne j\text{ then }\delta_{ij} = 0 \text{ (this is called a cross-marginal effect)}\\
\end{array} 
\]</span></p>
<p>We discuss these cases next, but first, to continue to work with an example, we need to estimate the probability of choosing different systems at different levels of the installation costs. We use different levels of the installation cost because the effects will not be the same at different starting points in the logit curve!.</p>
<p>To simulate this situation, we begin by copying the input dataframe. Here the first 20 rows are copied so that we can modify the data for 5 different systems (and their cost) and 4 regions:</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb140-1" title="1">ic_min &lt;-<span class="st"> </span>H[<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>,]</a>
<a class="sourceLine" id="cb140-2" title="2">ic_mean &lt;-<span class="st"> </span>H[<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>,]</a>
<a class="sourceLine" id="cb140-3" title="3">ic_max &lt;-<span class="st"> </span>H[<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>,]</a></code></pre></div>
<p>Next, we define the following vectors to retrieve the minimum, mean, and maximum installation costs for each heating system:</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb141-1" title="1">min_cost &lt;-<span class="st"> </span><span class="kw">with</span>(H, <span class="kw">data.frame</span>(<span class="dt">ic =</span> <span class="kw">tapply</span>(ic, <span class="kw">index</span>(mod1)<span class="op">$</span>alt, min)))</a>
<a class="sourceLine" id="cb141-2" title="2">mean_cost &lt;-<span class="st"> </span><span class="kw">with</span>(H, <span class="kw">data.frame</span>(<span class="dt">ic =</span> <span class="kw">tapply</span>(ic, <span class="kw">index</span>(mod1)<span class="op">$</span>alt, mean)))</a>
<a class="sourceLine" id="cb141-3" title="3">max_cost &lt;-<span class="st"> </span><span class="kw">with</span>(H, <span class="kw">data.frame</span>(<span class="dt">ic =</span> <span class="kw">tapply</span>(ic, <span class="kw">index</span>(mod1)<span class="op">$</span>alt, max)))</a></code></pre></div>
<p>We now replace the cost of installation with these vectors. Since each vector contains five values (for five heating systems) we need to repeat the vector 4 times (for 4 regions):</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb142-1" title="1">ic_min<span class="op">$</span>ic &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="kw">t</span>(min_cost), <span class="dt">times =</span> <span class="dv">4</span>)</a>
<a class="sourceLine" id="cb142-2" title="2">ic_mean<span class="op">$</span>ic &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="kw">t</span>(mean_cost), <span class="dt">times =</span> <span class="dv">4</span>)</a>
<a class="sourceLine" id="cb142-3" title="3">ic_max<span class="op">$</span>ic &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="kw">t</span>(max_cost), <span class="dt">times =</span> <span class="dv">4</span>)</a></code></pre></div>
<p>And finally, we replace the regions:</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb143-1" title="1">ic_min<span class="op">$</span>region &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;valley&quot;</span>, <span class="st">&quot;scostl&quot;</span>, <span class="st">&quot;mountn&quot;</span>, <span class="st">&quot;ncostl&quot;</span>), <span class="dt">each =</span> <span class="dv">5</span>)</a>
<a class="sourceLine" id="cb143-2" title="2">ic_mean<span class="op">$</span>region &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;valley&quot;</span>, <span class="st">&quot;scostl&quot;</span>, <span class="st">&quot;mountn&quot;</span>, <span class="st">&quot;ncostl&quot;</span>), <span class="dt">each =</span> <span class="dv">5</span>)</a>
<a class="sourceLine" id="cb143-3" title="3">ic_max<span class="op">$</span>region &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;valley&quot;</span>, <span class="st">&quot;scostl&quot;</span>, <span class="st">&quot;mountn&quot;</span>, <span class="st">&quot;ncostl&quot;</span>), <span class="dt">each =</span> <span class="dv">5</span>)</a></code></pre></div>
<p>If we quickly examine the dataframe with the minimum installation costs:</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb144-1" title="1"><span class="kw">head</span>(ic_min, <span class="dv">10</span>)</a></code></pre></div>
<pre><code>##      idcase depvar income agehed rooms region alt     ic     oc chid
## 1.ec      1  FALSE      7     25     6 valley  ec 469.61 553.34    1
## 1.er      1  FALSE      7     25     6 valley  er 546.82 505.60    1
## 1.gc      1   TRUE      7     25     6 valley  gc 431.83 199.69    1
## 1.gr      1  FALSE      7     25     6 valley  gr 574.94 151.72    1
## 1.hp      1  FALSE      7     25     6 valley  hp 532.32 237.88    1
## 2.ec      2  FALSE      5     60     5 scostl  ec 469.61 520.24    2
## 2.er      2  FALSE      5     60     5 scostl  er 546.82 486.49    2
## 2.gc      2   TRUE      5     60     5 scostl  gc 431.83 168.66    2
## 2.gr      2  FALSE      5     60     5 scostl  gr 574.94 168.66    2
## 2.hp      2  FALSE      5     60     5 scostl  hp 532.32 199.19    2</code></pre>
<p>We can see that we have simulated a dataset that includes the minimum installation cost of every system for each of four regions. We did not modify any of the other variables the age, income</p>
<p>Given the different values of installation cost (at min, mean, and max), we can predict the probabilities as follows:</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb146-1" title="1">p_mod1_ic_min &lt;-<span class="st"> </span><span class="kw">predict</span>(mod1, <span class="dt">newdata =</span> ic_min)</a>
<a class="sourceLine" id="cb146-2" title="2">p_mod1_ic_mean &lt;-<span class="st"> </span><span class="kw">predict</span>(mod1, <span class="dt">newdata =</span> ic_mean)</a>
<a class="sourceLine" id="cb146-3" title="3">p_mod1_ic_max &lt;-<span class="st"> </span><span class="kw">predict</span>(mod1, <span class="dt">newdata =</span> ic_max)</a></code></pre></div>
<p>The probabilities at their corresponding costs are summarized below (since “region” was not a covariate we can pick any region - they are all the same):</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb147-1" title="1"><span class="kw">data.frame</span>(<span class="dt">System =</span> <span class="kw">c</span>(<span class="st">&quot;Electric Central&quot;</span>, <span class="st">&quot;Electric Room&quot;</span>, <span class="st">&quot;Gas Central&quot;</span>, <span class="st">&quot;Gas Room&quot;</span>, <span class="st">&quot;Heat Pump&quot;</span>),</a>
<a class="sourceLine" id="cb147-2" title="2">           <span class="dt">Cost_min =</span> ic_min<span class="op">$</span>ic[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>],</a>
<a class="sourceLine" id="cb147-3" title="3">           <span class="dt">Prob_min =</span> p_mod1_ic_min[<span class="dv">1</span>,],</a>
<a class="sourceLine" id="cb147-4" title="4">           <span class="dt">Cost_mean =</span> ic_mean<span class="op">$</span>ic[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>],</a>
<a class="sourceLine" id="cb147-5" title="5">           <span class="dt">Prob_mean =</span> p_mod1_ic_mean[<span class="dv">1</span>,],</a>
<a class="sourceLine" id="cb147-6" title="6">           <span class="dt">Cost_max =</span> ic_max<span class="op">$</span>ic[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>],</a>
<a class="sourceLine" id="cb147-7" title="7">           <span class="dt">Prob_max =</span> p_mod1_ic_max[<span class="dv">1</span>,]) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb147-8" title="8"><span class="st">  </span><span class="kw">kable</span>(<span class="dt">col.names =</span> <span class="kw">c</span>(<span class="st">&quot;System&quot;</span>,</a>
<a class="sourceLine" id="cb147-9" title="9">                      <span class="st">&quot;Cost&quot;</span>,</a>
<a class="sourceLine" id="cb147-10" title="10">                      <span class="st">&quot;Probability&quot;</span>,</a>
<a class="sourceLine" id="cb147-11" title="11">                      <span class="st">&quot;Cost&quot;</span>,</a>
<a class="sourceLine" id="cb147-12" title="12">                      <span class="st">&quot;Probability&quot;</span>,</a>
<a class="sourceLine" id="cb147-13" title="13">                      <span class="st">&quot;Cost&quot;</span>,</a>
<a class="sourceLine" id="cb147-14" title="14">                      <span class="st">&quot;Probability&quot;</span>),</a>
<a class="sourceLine" id="cb147-15" title="15">        <span class="dt">digits =</span> <span class="dv">3</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb147-16" title="16"><span class="st">  </span><span class="kw">kable_styling</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb147-17" title="17"><span class="st">  </span><span class="kw">add_header_above</span>(<span class="kw">c</span>(<span class="st">&quot; &quot;</span> =<span class="st"> </span><span class="dv">2</span>, <span class="st">&quot;Minimum Cost&quot;</span> =<span class="st"> </span><span class="dv">2</span>, <span class="st">&quot;Mean Cost&quot;</span> =<span class="st"> </span><span class="dv">2</span>, <span class="st">&quot;Maximum Cost&quot;</span> =<span class="st"> </span><span class="dv">2</span>))</a></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="border-bottom:hidden" colspan="2">
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Minimum Cost
</div>
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Mean Cost
</div>
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Maximum Cost
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
System
</th>
<th style="text-align:right;">
Cost
</th>
<th style="text-align:right;">
Probability
</th>
<th style="text-align:right;">
Cost
</th>
<th style="text-align:right;">
Probability
</th>
<th style="text-align:right;">
Cost
</th>
<th style="text-align:right;">
Probability
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1.ec
</td>
<td style="text-align:left;">
Electric Central
</td>
<td style="text-align:right;">
469.61
</td>
<td style="text-align:right;">
0.070
</td>
<td style="text-align:right;">
824.543
</td>
<td style="text-align:right;">
0.071
</td>
<td style="text-align:right;">
1230.5
</td>
<td style="text-align:right;">
0.072
</td>
</tr>
<tr>
<td style="text-align:left;">
1.er
</td>
<td style="text-align:left;">
Electric Room
</td>
<td style="text-align:right;">
546.82
</td>
<td style="text-align:right;">
0.105
</td>
<td style="text-align:right;">
983.928
</td>
<td style="text-align:right;">
0.093
</td>
<td style="text-align:right;">
1496.3
</td>
<td style="text-align:right;">
0.078
</td>
</tr>
<tr>
<td style="text-align:left;">
1.gc
</td>
<td style="text-align:left;">
Gas Central
</td>
<td style="text-align:right;">
431.83
</td>
<td style="text-align:right;">
0.617
</td>
<td style="text-align:right;">
776.827
</td>
<td style="text-align:right;">
0.639
</td>
<td style="text-align:right;">
1158.9
</td>
<td style="text-align:right;">
0.672
</td>
</tr>
<tr>
<td style="text-align:left;">
1.gr
</td>
<td style="text-align:left;">
Gas Room
</td>
<td style="text-align:right;">
574.94
</td>
<td style="text-align:right;">
0.138
</td>
<td style="text-align:right;">
921.770
</td>
<td style="text-align:right;">
0.143
</td>
<td style="text-align:right;">
1344.0
</td>
<td style="text-align:right;">
0.140
</td>
</tr>
<tr>
<td style="text-align:left;">
1.hp
</td>
<td style="text-align:left;">
Heat Pump
</td>
<td style="text-align:right;">
532.32
</td>
<td style="text-align:right;">
0.071
</td>
<td style="text-align:right;">
1046.481
</td>
<td style="text-align:right;">
0.055
</td>
<td style="text-align:right;">
1679.8
</td>
<td style="text-align:right;">
0.038
</td>
</tr>
</tbody>
</table>
<div id="direct-marginal-effects" class="section level3">
<h3><span class="header-section-number">6.7.1</span> Direct marginal effects</h3>
<p>The direct marginal effect is defined as follows:</p>
<p><span class="math display">\[
M^{P_{in}}_{x_{ink}} = \beta_{k}(1-P_{in})
\]</span></p>
<p>This measure is useful to answer the question:</p>
<blockquote>
<p>“How much would the probability of choosing alternative <span class="math inline">\(i\)</span> change if its attribute <span class="math inline">\(k\)</span> changed by one unit?”</p>
</blockquote>
<p>Or, alternatively, in terms of the present example:</p>
<blockquote>
<p>“How much would the probability of choosing heating system <span class="math inline">\(i\)</span> change if its installation cost changed by one unit?”</p>
</blockquote>
<p>Based on the values summarized above, we can calculate the direct marginal effect of the gas central system at the min, mean, max installation costs as:</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb148-1" title="1"><span class="fl">-0.00168108</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="fl">0.617</span>)</a></code></pre></div>
<pre><code>## [1] -0.0006438536</code></pre>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb150-1" title="1"><span class="fl">-0.00168108</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="fl">0.639</span>)</a></code></pre></div>
<pre><code>## [1] -0.0006068699</code></pre>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb152-1" title="1"><span class="fl">-0.00168108</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="fl">0.672</span>)</a></code></pre></div>
<pre><code>## [1] -0.0005513942</code></pre>
<p>The values above indicate that the probabilities of choosing an electric central system would decrease by approximately <span class="math inline">\(0.00064\)</span>%, <span class="math inline">\(0.00061\)</span>%, <span class="math inline">\(0.00055\)</span>% if the installation cost increased by one dollar from the minimum, mean, and maximum installation cost, respectively.</p>
</div>
<div id="cross-marginal-effects" class="section level3">
<h3><span class="header-section-number">6.7.2</span> Cross-marginal effects</h3>
<p>The cross-marginal effect is defined as follows:</p>
<p><span class="math display">\[
M^{P_{in}}_{x_{jnk}} = -\beta_{jk}P_{jn}
\]</span></p>
<p>This measure is useful to answer the question:</p>
<blockquote>
<p>“How much would the probability of choosing alternative <span class="math inline">\(i\)</span> change if attribute <span class="math inline">\(k\)</span> of alternative <span class="math inline">\(j\)</span> changed by one unit?”</p>
</blockquote>
<p>Or, alternatively, in terms of the present example:</p>
<blockquote>
<p>“How much would the probability of choosing an electric central heating system change if the installation cost of the gas central heating system changed by one percent?”</p>
</blockquote>
<p>Based on the values summarized above, we can calculate the cross-marginal effect of the gas central system at the min, mean, max installation costs as:</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb154-1" title="1"><span class="op">-</span>(<span class="op">-</span><span class="fl">0.00168108</span> <span class="op">*</span><span class="st"> </span><span class="fl">0.617</span>)</a></code></pre></div>
<pre><code>## [1] 0.001037226</code></pre>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb156-1" title="1"><span class="op">-</span>(<span class="op">-</span><span class="fl">0.00168108</span> <span class="op">*</span><span class="st"> </span><span class="fl">0.639</span>)</a></code></pre></div>
<pre><code>## [1] 0.00107421</code></pre>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb158-1" title="1"><span class="op">-</span>(<span class="op">-</span><span class="fl">0.00168108</span> <span class="op">*</span><span class="st"> </span><span class="fl">0.672</span>)</a></code></pre></div>
<pre><code>## [1] 0.001129686</code></pre>
<p>The values above indicate that the probabilities of choosing an electric central system would <em>increase</em> by approximately <span class="math inline">\(0.0010\)</span>%, <span class="math inline">\(0.0011\)</span>%, <span class="math inline">\(0.0011\)</span>% if the cost of installing a gas central heating system increased by one dollar from the minimum, mean, and maximum installation cost, respectively.</p>
</div>
</div>
<div id="elasticity" class="section level2">
<h2><span class="header-section-number">6.8</span> Elasticity</h2>
<p>An alternative way to explore the way a variable responds to changes in another variable is by means of the elasticity. The elasticity is a concept from economics that is useful to summarize the way a dependent variable <span class="math inline">\(y\)</span> changes in response to changes in an independent variable <span class="math inline">\(x_k\)</span>. This is defined as follows:</p>
<p><span class="math display">\[
E^y_{x_k}=\frac{\partial y}{\partial x_k}\frac{x_k}{y}
\]</span></p>
<p>It can be seen that the elasticity takes the marginal effect and makes it relative to the values of <span class="math inline">\(y\)</span> and <span class="math inline">\(x_k\)</span>, in effect producing a unit-less summary measure that is interpreted as the percentage change in <span class="math inline">\(y\)</span> when attribute <span class="math inline">\(x_i\)</span> changes by <span class="math inline">\(1\)</span>%.</p>
<p>Following a similar logic as above, there are two cases of the elasticity, direct-point elasticity and cross-point elasticity. These will be discussed next.</p>
<div id="direct-point-elasticity" class="section level3">
<h3><span class="header-section-number">6.8.1</span> Direct-point elasticity</h3>
<p>Direct-point elasticity is calculated at a point value of <span class="math inline">\(x_ink\)</span> (attribute <span class="math inline">\(k\)</span> of alternative <span class="math inline">\(i\)</span> of decision-maker <span class="math inline">\(k\)</span>) with respect to the probability of selecting alternative <span class="math inline">\(i\)</span>. This elasticity is useful to ask the question:</p>
<blockquote>
<p>“How much would the probability of choosing alternative <span class="math inline">\(i\)</span> change if its attribute <span class="math inline">\(k\)</span> changed by one percent?”</p>
</blockquote>
<p>In terms of the present example:</p>
<blockquote>
<p>“How much would the probability of choosing heating system <span class="math inline">\(i\)</span> change if its installation cost changed by one percent?”</p>
</blockquote>
<p>The direct-point elasticity for a discrete choice model is given by:</p>
<p><span class="math display">\[
E^{P_{in}}_{x_{ink}} = \beta_{ik}x_{ink}(1-P_{in})
\]</span>
where <span class="math inline">\(P_{in}\)</span> is the probability of decision-maker <span class="math inline">\(n\)</span> selecting alternative <span class="math inline">\(i\)</span>, given a variable <span class="math inline">\(x_{ink}\)</span> and its corresponding coefficient <span class="math inline">\(\beta_{ik}\)</span>.</p>
<p>Based on the values summarized above, we can calculate the direct-point elasticity of the gas central system at the min, mean, max installation costs as:</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb160-1" title="1"><span class="fl">-0.00168108</span> <span class="op">*</span><span class="st"> </span><span class="fl">431.830</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="fl">0.617</span>)</a></code></pre></div>
<pre><code>## [1] -0.2780353</code></pre>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb162-1" title="1"><span class="fl">-0.00168108</span> <span class="op">*</span><span class="st"> </span><span class="fl">776.827</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="fl">0.639</span>)</a></code></pre></div>
<pre><code>## [1] -0.4714329</code></pre>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb164-1" title="1"><span class="fl">-0.00168108</span> <span class="op">*</span><span class="st"> </span><span class="fl">1158.90</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="fl">0.672</span>)</a></code></pre></div>
<pre><code>## [1] -0.6390108</code></pre>
<p>These values indicate that the probability of choosing the electric central system with the lowest installation cost declines by approximately <span class="math inline">\(0.31\)</span>% when the installation cost increases by <span class="math inline">\(1\)</span>%. When the installation cost is the mean and the max, the probability of selecting the electric central system declines by approximately <span class="math inline">\(0.47\)</span>% and <span class="math inline">\(0.64\)</span>% respectively when the cost of installation increases by <span class="math inline">\(1\)</span>%.</p>
<p>Notice that the elasticity tends to give greater values than the marginal effect. This is because a one-percent change in installation costs represents a much larger amount of change in the variable than a one dollar change.</p>
</div>
<div id="cross-point-elasticity" class="section level3">
<h3><span class="header-section-number">6.8.2</span> Cross-point elasticity</h3>
<p>Another useful measure of elasticity is the <em>cross-point elasticity</em>. This is useful to ask the question:</p>
<blockquote>
<p>“How much would the probability of choosing alternative <span class="math inline">\(i\)</span> change if attribute <span class="math inline">\(k\)</span> of alternative <span class="math inline">\(j\)</span> changed by one percent?”</p>
</blockquote>
<p>Or, for example:</p>
<blockquote>
<p>“How much would the probability of choosing an electric central heating system change if the installation cost of the gas central heating system changed by one percent?”</p>
</blockquote>
<p>Again, Louviere et al. <span class="citation">(<a href="#ref-Louviere2000stated" role="doc-biblioref">2000</a>, 58–59)</span> show that, given a discrete choice model, the cross-point elasticity is given by:
<span class="math display">\[
E^{P_{in}}_{x_{ink}} = -\beta_{jk}x_{jnk}P_{jn}
\]</span>
where <span class="math inline">\(P_{jn}\)</span> is the probability of decision-maker <span class="math inline">\(n\)</span> selecting alternative <span class="math inline">\(j\)</span>, given a variable <span class="math inline">\(x_{jnk}\)</span> and its corresponding coefficient <span class="math inline">\(\beta_jk\)</span>.</p>
<p>The cross-point elasticities of gas central heating at the min, mean, and max values of installation cost are:</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb166-1" title="1"><span class="op">-</span>(<span class="op">-</span><span class="fl">0.00168108</span> <span class="op">*</span><span class="st"> </span><span class="fl">431.830</span> <span class="op">*</span><span class="st"> </span><span class="fl">0.617</span>)</a></code></pre></div>
<pre><code>## [1] 0.4479055</code></pre>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb168-1" title="1"><span class="op">-</span>(<span class="op">-</span><span class="fl">0.00168108</span> <span class="op">*</span><span class="st"> </span><span class="fl">776.827</span> <span class="op">*</span><span class="st">  </span><span class="fl">0.639</span>)</a></code></pre></div>
<pre><code>## [1] 0.8344754</code></pre>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb170-1" title="1"><span class="op">-</span>(<span class="op">-</span><span class="fl">0.00168108</span> <span class="op">*</span><span class="st"> </span><span class="fl">1158.90</span> <span class="op">*</span><span class="st"> </span><span class="fl">0.672</span>)</a></code></pre></div>
<pre><code>## [1] 1.309193</code></pre>
<p>In other words, the probability of choosing a system other than gas central system increases by approximately <span class="math inline">\(0.45\)</span>%, <span class="math inline">\(0.83\)</span>%, <span class="math inline">\(1.31\)</span>% when the cost of installing a gas central system goes up by <span class="math inline">\(1\)</span>% from the min, mean, and max base installation costs.</p>
</div>
</div>
<div id="calculating-elasticities-based-on-an-mlogit-model" class="section level2">
<h2><span class="header-section-number">6.9</span> Calculating elasticities based on an <code>mlogit</code> model</h2>
<p>Fortunately, all the effects discussed above can be easily calculated once that a model has been estimated using the <code>mlogit</code> function for <code>effects</code>. This is illustrated next.</p>
<div id="computing-the-marginal-effects" class="section level3">
<h3><span class="header-section-number">6.9.1</span> Computing the marginal effects</h3>
<p>The marginal effects can be computed by means of the <code>effects</code> function. This function takes four arguments, as follows: an <code>mlogit</code> model, the name of the covariate (or attribute) that we wish to examine, the type of effect, and the data for calculating the effects.</p>
<p>For the marginal effects, the “type” of the effect is “(r)elative” for the probability and “(a)bsolute”" for the covariate. In the case of the marginal effects at the minimum values of cost we use <code>mod0</code> (our <code>mlogit</code> model object), indicate the covariate of interest (<code>ic</code> for installation cost), the type of effect (“ra”), and the input data:</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb172-1" title="1"><span class="kw">effects</span>(mod1, <span class="dt">covariate =</span> <span class="st">&quot;ic&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;ra&quot;</span>, <span class="dt">data =</span> ic_min[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>,])</a></code></pre></div>
<pre><code>##               ec            er            gc            gr            hp
## ec -0.0015641293  0.0001169511  0.0001169511  0.0001169511  0.0001169511
## er  0.0001756990 -0.0015053814  0.0001756990  0.0001756990  0.0001756990
## gc  0.0010369517  0.0010369517 -0.0006441287  0.0010369517  0.0010369517
## gr  0.0002325016  0.0002325016  0.0002325016 -0.0014485788  0.0002325016
## hp  0.0001189771  0.0001189771  0.0001189771  0.0001189770 -0.0015621033</code></pre>
<p>The values on the diagonal of the table above are the direct marginal effects, whereas other values are the cross-marginal effects.</p>
<p>The marginal effects at the mean values (sometimes called <em>MEM</em>, i.e., marginal effects at the mean) are:</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb174-1" title="1"><span class="kw">effects</span>(mod1, <span class="dt">covariate =</span> <span class="st">&quot;ic&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;ra&quot;</span>, <span class="dt">data =</span> ic_mean[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>,])</a></code></pre></div>
<pre><code>##               ec            er            gc            gr            hp
## ec -1.562008e-03  1.190728e-04  1.190728e-04  1.190728e-04  0.0001190728
## er  1.558057e-04 -1.525275e-03  1.558056e-04  1.558056e-04  0.0001558056
## gc  1.073548e-03  1.073548e-03 -6.075323e-04  1.073548e-03  0.0010735481
## gr  2.399663e-04  2.399663e-04  2.399663e-04 -1.441114e-03  0.0002399663
## hp  9.268762e-05  9.268762e-05  9.268762e-05  9.268762e-05 -0.0015883927</code></pre>
<p>And the marginal effects at the maximum values are:</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb176-1" title="1"><span class="kw">effects</span>(mod1, <span class="dt">covariate =</span> <span class="st">&quot;ic&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;ra&quot;</span>, <span class="dt">data =</span> ic_max[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>,])</a></code></pre></div>
<pre><code>##               ec            er            gc            gr            hp
## ec -1.560758e-03  1.203225e-04  1.203225e-04  0.0001203225  0.0001203225
## er  1.316513e-04 -1.549429e-03  1.316514e-04  0.0001316513  0.0001316514
## gc  1.129256e-03  1.129256e-03 -5.518241e-04  0.0011292563  0.0011292563
## gr  2.359411e-04  2.359411e-04  2.359412e-04 -0.0014451392  0.0002359412
## hp  6.390908e-05  6.390909e-05  6.390909e-05  0.0000639091 -0.0016171713</code></pre>
<p>You can verify that, with some small rounding error, they correspond to the values calculated previously.</p>
</div>
<div id="computing-the-elasticities" class="section level3">
<h3><span class="header-section-number">6.9.2</span> Computing the elasticities</h3>
<p>As well, the direct-point and cross-point elasticities can be calculated using the <code>effects</code> function, however in this case the type of the effects is <em>relative</em> both for the probability and for the covariate.</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb178-1" title="1"><span class="kw">effects</span>(mod1, <span class="dt">covariate =</span> <span class="st">&quot;ic&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;rr&quot;</span>, <span class="dt">data =</span> ic_min[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>,])</a></code></pre></div>
<pre><code>##             ec          er          gc          gr          hp
## ec -0.73453075  0.05492140  0.05492140  0.05492140  0.05492140
## er  0.09607572 -0.82317265  0.09607573  0.09607572  0.09607572
## gc  0.44778685  0.44778685 -0.27815410  0.44778684  0.44778685
## gr  0.13367447  0.13367447  0.13367448 -0.83284588  0.13367448
## hp  0.06333387  0.06333387  0.06333387  0.06333386 -0.83153884</code></pre>
<p>The values on the diagonal of the table above are the direct-point elasticities, whereas other values are the cross-point elasticities.</p>
<p>The effects can be calculated at various levels of the covariate of interest, for instance the mean and max:</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb180-1" title="1"><span class="kw">effects</span>(mod1, <span class="dt">covariate =</span> <span class="st">&quot;ic&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;rr&quot;</span>, <span class="dt">data =</span> ic_mean[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>,])</a></code></pre></div>
<pre><code>##             ec          er          gc          gr          hp
## ec -1.28794317  0.09818068  0.09818067  0.09818069  0.09818068
## er  0.15330155 -1.50076056  0.15330153  0.15330154  0.15330154
## gc  0.83396070  0.83396069 -0.47194728  0.83396070  0.83396070
## gr  0.22119376  0.22119375  0.22119375 -1.32837610  0.22119376
## hp  0.09699586  0.09699586  0.09699586  0.09699586 -1.66222324</code></pre>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb182-1" title="1"><span class="kw">effects</span>(mod1, <span class="dt">covariate =</span> <span class="st">&quot;ic&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;rr&quot;</span>, <span class="dt">data =</span> ic_max[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>,])</a></code></pre></div>
<pre><code>##            ec         er         gc         gr         hp
## ec -1.9205126  0.1480568  0.1480568  0.1480568  0.1480568
## er  0.1969899 -2.3184107  0.1969899  0.1969899  0.1969899
## gc  1.3086951  1.3086951 -0.6395089  1.3086951  1.3086951
## gr  0.3171049  0.3171049  0.3171049 -1.9422671  0.3171049
## hp  0.1073545  0.1073545  0.1073545  0.1073545 -2.7165243</code></pre>
</div>
</div>
<div id="a-note-about-attributes-in-dummy-format" class="section level2">
<h2><span class="header-section-number">6.10</span> A note about attributes in dummy format</h2>
<p>The attribute used above for the example was installation cost, a continuous variable. In many cases, the attributes of alternatives or decision-makers are continuous variables, but not always. In the dataset about heating systems, for example, there is a dummy variable that indicates the region of residence of the decision-maker:</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb184-1" title="1"><span class="kw">summary</span>(Heating<span class="op">$</span>region)</a></code></pre></div>
<pre><code>## valley scostl mountn ncostl 
##    177    361    102    260</code></pre>
<p>As can be seen, there are four regions. In the sample, <span class="math inline">\(177\)</span> respondents lived in the region labeled as “valley”, <span class="math inline">\(361\)</span> in the south coastal (“scostl”), <span class="math inline">\(102\)</span> in the mountain (“mountn”), and <span class="math inline">\(260\)</span> in north coastal (“ncostl”).</p>
<p>The marginal effects and elasticities discussed above are not appropriate for use when it comes to dummy variables. The reason for this is that marginal changes are not meaningful (e.g., what does it mean to increase region “mountain” by one unit of by 1%?)</p>
<p>When variable <span class="math inline">\(x_{ink}\)</span> is a dummy variable, the marginal effect must be calculated as follows:
<span class="math display">\[
M^{P_{in}}_{x_{ink}} = P_{in}(x_{ink} = 1) - P_{in}(x_{ink} = 0)
\]</span></p>
<p>In other words, the marginal effect is the difference in the probability of choosing <span class="math inline">\(i\)</span> when the dummy variable is <span class="math inline">\(1\)</span> versus when it is <span class="math inline">\(0\)</span>.</p>
<p>Let estimate a second model that uses the regions variable to illustrate this (call this Model 2):</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb186-1" title="1">mod2 &lt;-<span class="st"> </span><span class="kw">mlogit</span>(depvar <span class="op">~</span><span class="st"> </span>ic <span class="op">|</span><span class="st"> </span>region, H)</a>
<a class="sourceLine" id="cb186-2" title="2"><span class="kw">summary</span>(mod2)</a></code></pre></div>
<pre><code>## 
## Call:
## mlogit(formula = depvar ~ ic | region, data = H, method = &quot;nr&quot;)
## 
## Frequencies of alternatives:
##       ec       er       gc       gr       hp 
## 0.071111 0.093333 0.636667 0.143333 0.055556 
## 
## nr method
## 6 iterations, 0h:0m:0s 
## g&#39;(-H)^-1g = 0.000192 
## successive function values within tolerance limits 
## 
## Coefficients :
##                    Estimate  Std. Error z-value  Pr(&gt;|z|)    
## er:(intercept)   0.60026296  0.37803680  1.5878  0.112322    
## gc:(intercept)   2.03028891  0.29516076  6.8786 6.045e-12 ***
## gr:(intercept)   0.89557390  0.34321429  2.6094  0.009071 ** 
## hp:(intercept)   0.28142118  0.42207287  0.6668  0.504926    
## ic              -0.00166573  0.00062007 -2.6864  0.007223 ** 
## er:regionscostl  0.04953858  0.44699277  0.1108  0.911754    
## gc:regionscostl  0.07371855  0.36192685  0.2037  0.838601    
## gr:regionscostl  0.10263835  0.41405948  0.2479  0.804225    
## hp:regionscostl -0.14496763  0.50052467 -0.2896  0.772098    
## er:regionmountn -0.02228435  0.59062797 -0.0377  0.969903    
## gc:regionmountn -0.08617193  0.47825549 -0.1802  0.857012    
## gr:regionmountn  0.03599409  0.54612045  0.0659  0.947451    
## hp:regionmountn -0.03937414  0.65470562 -0.0601  0.952044    
## er:regionncostl -0.33843774  0.49386054 -0.6853  0.493161    
## gc:regionncostl  0.23183246  0.38396435  0.6038  0.545986    
## gr:regionncostl -0.32954624  0.45479104 -0.7246  0.468691    
## hp:regionncostl -0.39942540  0.55412324 -0.7208  0.471018    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Log-Likelihood: -1012.5
## McFadden R^2:  0.0094891 
## Likelihood ratio test : chisq = 19.4 (p.value = 0.11122)</code></pre>
<p>Notice that none of the regional coefficients is significant, so we would likely not include these variables in the model. However, for the sake of the example, lets calculate the marginal effect of the dummy variables at the mean of installation cost.</p>
<p>We had already created a matrix with the mean of the installation cost at various regions.</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb188-1" title="1">p_region_ic_mean &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Region =</span> <span class="kw">c</span>(<span class="st">&quot;valley&quot;</span>, <span class="st">&quot;scostl&quot;</span>, <span class="st">&quot;mountn&quot;</span>, <span class="st">&quot;ncostl&quot;</span>),</a>
<a class="sourceLine" id="cb188-2" title="2">                               <span class="kw">predict</span>(mod2, <span class="dt">newdata =</span> ic_mean, <span class="dt">outcome =</span> <span class="ot">FALSE</span>))</a>
<a class="sourceLine" id="cb188-3" title="3">p_region_ic_mean</a></code></pre></div>
<pre><code>##   Region         ec         er        gc        gr         hp
## 1 valley 0.06893601 0.06868371 0.7167905 0.1032603 0.04232956
## 2 scostl 0.07709246 0.10537150 0.5832442 0.1664375 0.06785436
## 3 mountn 0.07330246 0.10244901 0.6044788 0.1526602 0.06710956
## 4 ncostl 0.06922558 0.10166470 0.6145323 0.1597530 0.05482440</code></pre>
<p>The first row contains the probabilities of the different systems for valley (the reference region), and then for each of the three other regions.</p>
<p>The marginal effects of changing from the valley to other regions are:</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb190-1" title="1"><span class="kw">data.frame</span> (<span class="dt">Effect =</span> <span class="kw">c</span>(<span class="st">&quot;valley to scostl&quot;</span>, <span class="st">&quot;valley to mountn&quot;</span>, <span class="st">&quot;valley to ncostl&quot;</span>),</a>
<a class="sourceLine" id="cb190-2" title="2">            <span class="kw">rbind</span> (p_region_ic_mean[<span class="dv">2</span>, <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>] <span class="op">-</span><span class="st"> </span>p_region_ic_mean[<span class="dv">1</span>, <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>],</a>
<a class="sourceLine" id="cb190-3" title="3">                   p_region_ic_mean[<span class="dv">3</span>, <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>] <span class="op">-</span><span class="st"> </span>p_region_ic_mean[<span class="dv">1</span>, <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>],</a>
<a class="sourceLine" id="cb190-4" title="4">                   p_region_ic_mean[<span class="dv">4</span>, <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>] <span class="op">-</span><span class="st"> </span>p_region_ic_mean[<span class="dv">1</span>, <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>]))</a></code></pre></div>
<pre><code>##             Effect           ec         er         gc         gr         hp
## 2 valley to scostl 0.0081564496 0.03668779 -0.1335463 0.06317722 0.02552480
## 3 valley to mountn 0.0043664503 0.03376531 -0.1123117 0.04939991 0.02478000
## 4 valley to ncostl 0.0002895745 0.03298099 -0.1022582 0.05649277 0.01249484</code></pre>
</div>
<div id="willingness-to-pay-and-discount-rate" class="section level2">
<h2><span class="header-section-number">6.11</span> Willingness to pay and discount rate</h2>
<p>Another interesting question for policy analysis is at what rate are consumers willing to trade-off one attribute for another? In terms of the present example, this question could be:</p>
<blockquote>
<p>“How much are consumers willing to pay in increased installation costs for lower annual operating costs?”</p>
</blockquote>
<p>To answer this question, we first need an appropriate choice model, that is, one that includes both installation <em>and</em> annual operation costs. The following utility functions are one possible model specification (with heat pump as the reference level):
<span class="math display">\[
\begin{array}{ccc}
V_{\text{ec}} = &amp; 0 &amp; + \beta_1\text{ic.ec} + \beta_2\text{oc.ec}\\
V_{\text{er}} = &amp; \beta_{er} &amp; + \beta_1\text{ic.er} + \beta_2\text{oc.er}\\
V_{\text{gc}} = &amp; \beta_{gc} &amp; + \beta_1\text{ic.gc} + \beta_2\text{oc.gc}\\
V_{\text{gr}} = &amp; \beta_{gr} &amp; + \beta_1\text{ic.gr} + \beta_2\text{oc.gr}\\
V_{\text{hp}} = &amp; \beta_{hp} &amp; + \beta_1\text{ic.hp} + \beta_2\text{oc.hp}\\
\end{array}
\]</span></p>
<p>The model can be reestimated using these constants. The option <code>reflevel</code> is used to select the alternative that will work as reference (call this Model 3):</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb192-1" title="1">mod3 &lt;-<span class="st"> </span><span class="kw">mlogit</span>(depvar <span class="op">~</span><span class="st"> </span>ic <span class="op">+</span><span class="st"> </span>oc, H, <span class="dt">reflevel =</span> <span class="st">&quot;ec&quot;</span>)</a>
<a class="sourceLine" id="cb192-2" title="2"><span class="kw">summary</span>(mod3)</a></code></pre></div>
<pre><code>## 
## Call:
## mlogit(formula = depvar ~ ic + oc, data = H, reflevel = &quot;ec&quot;, 
##     method = &quot;nr&quot;)
## 
## Frequencies of alternatives:
##       ec       er       gc       gr       hp 
## 0.071111 0.093333 0.636667 0.143333 0.055556 
## 
## nr method
## 6 iterations, 0h:0m:0s 
## g&#39;(-H)^-1g = 9.58E-06 
## successive function values within tolerance limits 
## 
## Coefficients :
##                   Estimate  Std. Error z-value  Pr(&gt;|z|)    
## er:(intercept)  0.19459102  0.20424212  0.9527 0.3407184    
## gc:(intercept)  0.05213336  0.46598878  0.1119 0.9109210    
## gr:(intercept) -1.35058266  0.50715442 -2.6631 0.0077434 ** 
## hp:(intercept) -1.65884594  0.44841936 -3.6993 0.0002162 ***
## ic             -0.00153315  0.00062086 -2.4694 0.0135333 *  
## oc             -0.00699637  0.00155408 -4.5019 6.734e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Log-Likelihood: -1008.2
## McFadden R^2:  0.013691 
## Likelihood ratio test : chisq = 27.99 (p.value = 8.3572e-07)</code></pre>
<p>So, how is this model used to understand consumer preferences? Recall that the question is at what rate are consumers willing to pay for installation relative to operation.</p>
<p>The coefficients of the model provide useful information. Suppose that we would like to know at what rate consumers would be willing to trade one aspect of the good for another, whithout compromising the utility they derive from it. In effect we would like to know how changes in one attribute relate to changes in the other. In the present case, we want to know how installation costs change with respect to operation costs, while mainting the utility (i.e., the change in utility is zero):</p>
<p><span class="math display">\[
\partial U = 0 = \beta_1\partial ic + \beta_{2}\partial oc
\]</span></p>
<p>It follows then that:</p>
<p><span class="math display">\[
-\frac{\partial ic}{\partial oc} = \frac{\beta_2}{\beta_1}
\]</span></p>
<p>The ratio of the coefficients represents the <em>willingness to pay</em>. In this example, since:</p>
<p><span class="math display">\[
-\frac{\partial ic}{\partial oc} = \frac{\beta_2}{\beta_1} = \frac{-0.0069}{-0.0015} = 4.56
\]</span></p>
<p>The willingness to pay is an additional 4.56 dollars in installation costs per every dollar of operation cost per year. The discount rate is:</p>
<p><span class="math display">\[
r = \frac{1}{4.56} = 0.219 = 21.9\%
\]</span></p>
<p>This information can be used to assess the behavior of consumers.</p>
</div>
<div id="simulating-market-changes" class="section level2">
<h2><span class="header-section-number">6.12</span> Simulating market changes</h2>
<p>To the extent that random utility models can capture consumer preferences, they are useful to understand patterns of substitution. Once a model has been estimated simulating market changes involves creating a new data matrix to which the model can be applied. Lets take a look at two examples.</p>
<div id="incentives" class="section level3">
<h3><span class="header-section-number">6.12.1</span> Incentives</h3>
<p>Heat pumps are on average more expensive than other heating systems, but they are also more energy-efficient. Suppose then that the government, which has perhaps carbon emission targets that it wishes to meet, is analyzing a policy to encourage the adoption of heat pumps. The policy is to offer a rebate of 15% on the installation cost of heat pumps. As a consequence of this policy, consumers who install a heat pump and apply for the rebate pay only 85% of the cost of installation.</p>
<p>To simulate this scenario, we begin by copying the input dataframe:</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb194-1" title="1">H_rebate &lt;-<span class="st"> </span>H</a></code></pre></div>
<p>In the new dataframe that will simulate the rebate, replacing the cost of installation as follows:</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb195-1" title="1">H_rebate[H_rebate<span class="op">$</span>alt <span class="op">==</span><span class="st"> &quot;hp&quot;</span>, <span class="st">&quot;ic&quot;</span>] &lt;-<span class="st"> </span><span class="fl">0.85</span> <span class="op">*</span><span class="st"> </span>H_rebate[H_rebate<span class="op">$</span>alt <span class="op">==</span><span class="st"> &quot;hp&quot;</span>, <span class="st">&quot;ic&quot;</span>]</a></code></pre></div>
<p>We can calculate the market shares of the “do nothing” and “rebate” policies and compare their shares (which are the mean values of the predictions):</p>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb196-1" title="1"><span class="kw">data.frame</span>(<span class="dt">Policy =</span> <span class="kw">c</span>(<span class="st">&quot;Do nothing&quot;</span>, <span class="st">&quot;15% rebate&quot;</span>),</a>
<a class="sourceLine" id="cb196-2" title="2">           <span class="kw">rbind</span>(<span class="kw">apply</span>(<span class="kw">predict</span>(mod3, <span class="dt">newdata =</span> H), <span class="dv">2</span>, mean),</a>
<a class="sourceLine" id="cb196-3" title="3">                 <span class="kw">apply</span>(<span class="kw">predict</span>(mod3, <span class="dt">newdata =</span> H_rebate), <span class="dv">2</span>, mean)))</a></code></pre></div>
<pre><code>##       Policy         ec         er        gc        gr         hp
## 1 Do nothing 0.07111111 0.09333333 0.6366667 0.1433333 0.05555556
## 2 15% rebate 0.07009125 0.09199196 0.6272957 0.1412092 0.06941196</code></pre>
</div>
<div id="introduction-of-a-new-system" class="section level3">
<h3><span class="header-section-number">6.12.2</span> Introduction of a new system</h3>
<p>Suppose for example that a more efficient electric system is developed using newer technologies. The cost of installation is more expensive due to the cost of the new technology (cost of installation is $200 dollars higher than the electric central system). On the other hand, the cost of operation is only 75% that of the electric central systems. The preceding analysis suggests that consumers are willing to spend more in installation in exchange for savings in operation costs. What would be the penetration of this new system?</p>
<p>To simulate this situation, we begin by creating a model matrix based on Model 3:</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb198-1" title="1">X &lt;-<span class="st"> </span><span class="kw">model.matrix</span>(mod3)</a></code></pre></div>
<p>Then, we create a new alternative by copying the attributes of electric central:</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb199-1" title="1">alt &lt;-<span class="st"> </span><span class="kw">index</span>(H)<span class="op">$</span>alt</a>
<a class="sourceLine" id="cb199-2" title="2">Xn &lt;-<span class="st"> </span>X[alt <span class="op">==</span><span class="st"> &quot;ec&quot;</span>,]</a></code></pre></div>
<p>Next, we’ll modify the attributes to reflect the attributes of the new system (+$200 to ic and 0.75 of oc):</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb200-1" title="1">Xn[, <span class="st">&quot;ic&quot;</span>] &lt;-<span class="st"> </span>Xn[, <span class="st">&quot;ic&quot;</span>] <span class="op">+</span><span class="st"> </span><span class="dv">200</span></a>
<a class="sourceLine" id="cb200-2" title="2">Xn[, <span class="st">&quot;oc&quot;</span>] &lt;-<span class="st"> </span>Xn[, <span class="st">&quot;oc&quot;</span>] <span class="op">*</span><span class="st"> </span><span class="fl">0.75</span></a></code></pre></div>
<p>We also want to identify the unique choice ids, which we will add as row names to the new systems:</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb201-1" title="1">chid &lt;-<span class="st"> </span><span class="kw">index</span>(H)<span class="op">$</span>chid</a>
<a class="sourceLine" id="cb201-2" title="2">unchid &lt;-<span class="st"> </span><span class="kw">unique</span>(<span class="kw">index</span>(H)<span class="op">$</span>chid)</a>
<a class="sourceLine" id="cb201-3" title="3"><span class="kw">rownames</span>(Xn) &lt;-<span class="st"> </span><span class="kw">paste</span>(unchid, <span class="st">&#39;new&#39;</span>, <span class="dt">sep =</span> <span class="st">&quot;.&quot;</span>)</a>
<a class="sourceLine" id="cb201-4" title="4">chidb &lt;-<span class="st"> </span><span class="kw">c</span>(chid, unchid)</a></code></pre></div>
<p>After this, we can join the new system to the model matrix and sort by choice id:</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb202-1" title="1">X &lt;-<span class="st"> </span><span class="kw">rbind</span>(X, Xn)</a>
<a class="sourceLine" id="cb202-2" title="2">X &lt;-<span class="st"> </span>X[<span class="kw">order</span>(chidb), ]</a></code></pre></div>
<p>This calculates the expression <span class="math inline">\(e^{X\beta}\)</span> and the sum, which are needed to compute the logit probabilities:</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb203-1" title="1">exp_Xb &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(<span class="kw">exp</span>(X <span class="op">%*%</span><span class="st"> </span><span class="kw">coef</span>(mod3)))</a>
<a class="sourceLine" id="cb203-2" title="2">sum_exp_Xb &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(<span class="kw">tapply</span>(exp_Xb, <span class="kw">sort</span>(chidb), sum))</a></code></pre></div>
<p>This is the vector of logit probabilities:</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb204-1" title="1">P &lt;-<span class="st"> </span>exp_Xb <span class="op">/</span><span class="st"> </span>sum_exp_Xb[<span class="kw">sort</span>(chidb)]</a></code></pre></div>
<p>Convert to a matrix of logit probabilities, so that each row is the choice probabilities for a household:</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb205-1" title="1">P &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="kw">matrix</span>(P, <span class="dt">ncol =</span> <span class="dv">6</span>, <span class="dt">byrow =</span> <span class="ot">TRUE</span>))</a>
<a class="sourceLine" id="cb205-2" title="2">P &lt;-<span class="st"> </span><span class="kw">transmute</span>(P, <span class="dt">hp =</span> P[, <span class="dv">5</span>], <span class="dt">ec =</span> P[, <span class="dv">1</span>], <span class="dt">er =</span> P[, <span class="dv">2</span>], <span class="dt">gc =</span> P[, <span class="dv">3</span>], <span class="dt">gr =</span> P[, <span class="dv">4</span>], <span class="dt">new =</span> P[, <span class="dv">6</span>])</a></code></pre></div>
<p>We can verify that the sum of the probabilities for each household is 1:</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb206-1" title="1"><span class="kw">summary</span>(<span class="kw">rowSums</span>(P))</a></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##       1       1       1       1       1       1</code></pre>
<p>The estimated penetration of the new system is the average probability of households choosing this system:</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb208-1" title="1"><span class="kw">apply</span>(P, <span class="dv">2</span>, mean)</a></code></pre></div>
<pre><code>##         hp         ec         er         gc         gr        new 
## 0.04977350 0.06311578 0.08347713 0.57145108 0.12855080 0.10363170</code></pre>
<p>The new technology is estimated to have a penetration rate of approximately <span class="math inline">\(10.4\%\)</span>. Compare to the original proportions of the systems:</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb210-1" title="1"><span class="kw">apply</span>(<span class="kw">fitted</span>(mod3, <span class="dt">outcome =</span> <span class="ot">FALSE</span>), <span class="dv">2</span>, mean)</a></code></pre></div>
<pre><code>##         ec         er         gc         gr         hp 
## 0.07111111 0.09333333 0.63666667 0.14333333 0.05555556</code></pre>
<p>Can you discern the patterns of substitution here? Are these patterns of substitution reasonable?</p>
</div>
</div>
<div id="exercise-4" class="section level2">
<h2><span class="header-section-number">6.13</span> Exercise</h2>
<ol style="list-style-type: decimal">
<li><p>What is the difference between a marginal effect and an elasticity?</p></li>
<li><p>Why is it inappropriate to calculate the elasticity of a dummy variable?</p></li>
<li><p>Use Model 3 in this chapter and calculate the marginal effects and the elasticities for operating cost at the mean of all variables.</p></li>
<li><p>Use Model 3 in this chapter to calculate the rebate needed to reach a 10% penetration rate of heat pumps.</p></li>
</ol>
<p>Estimate a new model that extends Model 3 by introducing the age of the household head. Use the electric room system (“er”) as the reference level.</p>
<ol start="5" style="list-style-type: decimal">
<li><p>Use the likelihood ratio test to compare your new model to Model 3. Discuss the results.</p></li>
<li><p>Is the ratio of the coefficient of installation (or operation) cost to the coefficient of age of household head meaningful? Explain.</p></li>
</ol>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-Benakiva1985discrete">
<p>Ben-Akiva, M., and S. R. Lerman. 1985. <em>Discrete Choice Analysis: Theory and Applications to Travel Demand</em>. Book. Cambridge: The MIT Press.</p>
</div>
<div id="ref-hensher2005applied">
<p>Hensher, David A, John M Rose, and William H Greene. 2005. <em>Applied Choice Analysis: A Primer</em>. Cambridge University Press.</p>
</div>
<div id="ref-King1993models">
<p>King, John L, and Kenneth L Kraemer. 1993. “Models, Facts, and the Policy Process: The Political Ecology of Estimated Truth.” Book Section. In <em>Environmental Modelling with Gis</em>, edited by M. Goodchild, B. O. Parks, and L. T. Steyaert. Oxford: Oxford University Press.</p>
</div>
<div id="ref-Louviere2000stated">
<p>Louviere, Jordan J, David A Hensher, and Joffre D Swait. 2000. <em>Stated Choice Methods: Analysis and Applications</em>. Cambridge University Press.</p>
</div>
<div id="ref-McFadden1974measurement">
<p>McFadden, D. 1974. “The Measurement of Urban Travel Demand.” Journal Article. <em>Journal of Public Economics</em> 3 (4): 303–28.</p>
</div>
<div id="ref-Ortuzar2011modelling">
<p>Ortúzar, J. D., and L. G. Willumsen. 2011. <em>Modelling Transport</em>. Book. Vol. Fourth Edition. New York: Wiley.</p>
</div>
<div id="ref-Train2009discrete">
<p>Train, K. 2009. <em>Discrete Choice Methods with Simulation</em>. Book. 2nd Edition. Cambridge: Cambridge University Press.</p>
</div>
<div id="ref-Train2012mlogit">
<p>Train, K., and Y. Croissant. 2012. “Kenneth Train’s Exercises Using the Mlogit Package for R.” Journal Article. <em>CiteSeerX</em>.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chapter-4.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chapter-6.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/05-Behavioral-Insights.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
