<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 Ordinal and Ranked Responses | An Introduction to Discrete Choice Analysis</title>
  <meta name="description" content="These notes were created by Antonio Paez as a resource for teaching a graduate discrete choice analysis course (GEOG 738) at McMaster University." />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 Ordinal and Ranked Responses | An Introduction to Discrete Choice Analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="These notes were created by Antonio Paez as a resource for teaching a graduate discrete choice analysis course (GEOG 738) at McMaster University." />
  <meta name="github-repo" content="paezha/Discrete-Choice-Analysis-with-R" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 Ordinal and Ranked Responses | An Introduction to Discrete Choice Analysis" />
  
  <meta name="twitter:description" content="These notes were created by Antonio Paez as a resource for teaching a graduate discrete choice analysis course (GEOG 738) at McMaster University." />
  

<meta name="author" content="Antonio Paez" />


<meta name="date" content="2020-02-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chapter-9.html"/>
<link rel="next" href="references.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.9.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.49.4/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.49.4/plotly-latest.min.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#choices-choices-choices"><i class="fa fa-check"></i>Choices, choices, choices</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#price-mechanisms"><i class="fa fa-check"></i>Price Mechanisms</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#plan"><i class="fa fa-check"></i>Plan</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#audience"><i class="fa fa-check"></i>Audience</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#requisites"><i class="fa fa-check"></i>Requisites</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html"><i class="fa fa-check"></i><b>1</b> Preliminaries: Installing R and RStudio</a><ul>
<li class="chapter" data-level="1.1" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html#introduction"><i class="fa fa-check"></i><b>1.1</b> Introduction</a></li>
<li class="chapter" data-level="1.2" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html#learning-objectives"><i class="fa fa-check"></i><b>1.2</b> Learning Objectives</a></li>
<li class="chapter" data-level="1.3" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html#r-the-open-statistical-computing-project"><i class="fa fa-check"></i><b>1.3</b> R: The Open Statistical Computing Project</a><ul>
<li class="chapter" data-level="1.3.1" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html#what-is-r"><i class="fa fa-check"></i><b>1.3.1</b> What is R?</a></li>
<li class="chapter" data-level="1.3.2" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html#the-rstudio-ide"><i class="fa fa-check"></i><b>1.3.2</b> The RStudio IDE</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html#packages-in-r"><i class="fa fa-check"></i><b>1.4</b> Packages in R</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chapter-1.html"><a href="chapter-1.html"><i class="fa fa-check"></i><b>2</b> Data and stuff</a><ul>
<li class="chapter" data-level="2.1" data-path="chapter-1.html"><a href="chapter-1.html#what-are-models"><i class="fa fa-check"></i><b>2.1</b> What are models?</a></li>
<li class="chapter" data-level="2.2" data-path="chapter-1.html"><a href="chapter-1.html#how-to-use-this-note"><i class="fa fa-check"></i><b>2.2</b> How to use this note</a></li>
<li class="chapter" data-level="2.3" data-path="chapter-1.html"><a href="chapter-1.html#learning-objectives-1"><i class="fa fa-check"></i><b>2.3</b> Learning objectives</a></li>
<li class="chapter" data-level="2.4" data-path="chapter-1.html"><a href="chapter-1.html#suggested-readings"><i class="fa fa-check"></i><b>2.4</b> Suggested readings</a></li>
<li class="chapter" data-level="2.5" data-path="chapter-1.html"><a href="chapter-1.html#ways-of-measuring-stuff"><i class="fa fa-check"></i><b>2.5</b> Ways of measuring stuff</a><ul>
<li class="chapter" data-level="2.5.1" data-path="chapter-1.html"><a href="chapter-1.html#categorical"><i class="fa fa-check"></i><b>2.5.1</b> Categorical</a></li>
<li class="chapter" data-level="2.5.2" data-path="chapter-1.html"><a href="chapter-1.html#quantitative"><i class="fa fa-check"></i><b>2.5.2</b> Quantitative</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="chapter-1.html"><a href="chapter-1.html#importing-data"><i class="fa fa-check"></i><b>2.6</b> Importing data</a></li>
<li class="chapter" data-level="2.7" data-path="chapter-1.html"><a href="chapter-1.html#data-classes-in-r"><i class="fa fa-check"></i><b>2.7</b> Data Classes in <code>R</code></a></li>
<li class="chapter" data-level="2.8" data-path="chapter-1.html"><a href="chapter-1.html#more-on-indexing-and-data-manipulation"><i class="fa fa-check"></i><b>2.8</b> More on indexing and data manipulation</a></li>
<li class="chapter" data-level="2.9" data-path="chapter-1.html"><a href="chapter-1.html#visualization"><i class="fa fa-check"></i><b>2.9</b> Visualization</a></li>
<li class="chapter" data-level="2.10" data-path="chapter-1.html"><a href="chapter-1.html#exercise"><i class="fa fa-check"></i><b>2.10</b> Exercise</a><ul>
<li class="chapter" data-level="2.10.1" data-path="chapter-1.html"><a href="chapter-1.html#questions"><i class="fa fa-check"></i><b>2.10.1</b> Questions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chapter-2.html"><a href="chapter-2.html"><i class="fa fa-check"></i><b>3</b> Fundamental concepts</a><ul>
<li class="chapter" data-level="3.1" data-path="chapter-2.html"><a href="chapter-2.html#why-modelling-choices"><i class="fa fa-check"></i><b>3.1</b> Why modelling choices?</a></li>
<li class="chapter" data-level="3.2" data-path="chapter-2.html"><a href="chapter-2.html#how-to-use-this-note-1"><i class="fa fa-check"></i><b>3.2</b> How to use this note</a></li>
<li class="chapter" data-level="3.3" data-path="chapter-2.html"><a href="chapter-2.html#learning-objectives-2"><i class="fa fa-check"></i><b>3.3</b> Learning objectives</a></li>
<li class="chapter" data-level="3.4" data-path="chapter-2.html"><a href="chapter-2.html#suggested-readings-1"><i class="fa fa-check"></i><b>3.4</b> Suggested readings</a></li>
<li class="chapter" data-level="3.5" data-path="chapter-2.html"><a href="chapter-2.html#preliminaries"><i class="fa fa-check"></i><b>3.5</b> Preliminaries</a></li>
<li class="chapter" data-level="3.6" data-path="chapter-2.html"><a href="chapter-2.html#utility-maximization"><i class="fa fa-check"></i><b>3.6</b> Utility maximization</a><ul>
<li class="chapter" data-level="3.6.1" data-path="chapter-2.html"><a href="chapter-2.html#what-is-utility"><i class="fa fa-check"></i><b>3.6.1</b> What is utility?</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="chapter-2.html"><a href="chapter-2.html#what-about-those-random-terms"><i class="fa fa-check"></i><b>3.7</b> What about those random terms?</a></li>
<li class="chapter" data-level="3.8" data-path="chapter-2.html"><a href="chapter-2.html#probability-distribution-functions-pdfs"><i class="fa fa-check"></i><b>3.8</b> Probability distribution functions (PDFs)</a></li>
<li class="chapter" data-level="3.9" data-path="chapter-2.html"><a href="chapter-2.html#a-simple-random-utility-discrete-choice-model"><i class="fa fa-check"></i><b>3.9</b> A simple random utility discrete choice model</a></li>
<li class="chapter" data-level="3.10" data-path="chapter-2.html"><a href="chapter-2.html#other-choice-mechanisms"><i class="fa fa-check"></i><b>3.10</b> Other choice mechanisms</a></li>
<li class="chapter" data-level="3.11" data-path="chapter-2.html"><a href="chapter-2.html#exercise-1"><i class="fa fa-check"></i><b>3.11</b> Exercise</a><ul>
<li class="chapter" data-level="3.11.1" data-path="chapter-2.html"><a href="chapter-2.html#questions-1"><i class="fa fa-check"></i><b>3.11.1</b> Questions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chapter-3.html"><a href="chapter-3.html"><i class="fa fa-check"></i><b>4</b> Logit</a><ul>
<li class="chapter" data-level="4.1" data-path="chapter-3.html"><a href="chapter-3.html#modelling-choices"><i class="fa fa-check"></i><b>4.1</b> Modelling choices</a></li>
<li class="chapter" data-level="4.2" data-path="chapter-3.html"><a href="chapter-3.html#how-to-use-this-note-2"><i class="fa fa-check"></i><b>4.2</b> How to use this note</a></li>
<li class="chapter" data-level="4.3" data-path="chapter-3.html"><a href="chapter-3.html#learning-objectives-3"><i class="fa fa-check"></i><b>4.3</b> Learning objectives</a></li>
<li class="chapter" data-level="4.4" data-path="chapter-3.html"><a href="chapter-3.html#suggested-readings-2"><i class="fa fa-check"></i><b>4.4</b> Suggested readings</a></li>
<li class="chapter" data-level="4.5" data-path="chapter-3.html"><a href="chapter-3.html#preliminaries-1"><i class="fa fa-check"></i><b>4.5</b> Preliminaries</a></li>
<li class="chapter" data-level="4.6" data-path="chapter-3.html"><a href="chapter-3.html#once-again-those-random-terms"><i class="fa fa-check"></i><b>4.6</b> Once again those random terms</a></li>
<li class="chapter" data-level="4.7" data-path="chapter-3.html"><a href="chapter-3.html#now-about-those-parameters-mu-and-sigma"><i class="fa fa-check"></i><b>4.7</b> Now, about those parameters <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>…</a></li>
<li class="chapter" data-level="4.8" data-path="chapter-3.html"><a href="chapter-3.html#multinomial-logit"><i class="fa fa-check"></i><b>4.8</b> Multinomial logit</a></li>
<li class="chapter" data-level="4.9" data-path="chapter-3.html"><a href="chapter-3.html#properties-of-the-logit-model"><i class="fa fa-check"></i><b>4.9</b> Properties of the logit model</a></li>
<li class="chapter" data-level="4.10" data-path="chapter-3.html"><a href="chapter-3.html#revisiting-the-systematic-utilities"><i class="fa fa-check"></i><b>4.10</b> Revisiting the systematic utilities</a></li>
<li class="chapter" data-level="4.11" data-path="chapter-3.html"><a href="chapter-3.html#exercise-2"><i class="fa fa-check"></i><b>4.11</b> Exercise</a><ul>
<li class="chapter" data-level="4.11.1" data-path="chapter-3.html"><a href="chapter-3.html#questions-2"><i class="fa fa-check"></i><b>4.11.1</b> Questions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chapter-4.html"><a href="chapter-4.html"><i class="fa fa-check"></i><b>5</b> Practical issues in specification and estimation</a><ul>
<li class="chapter" data-level="5.1" data-path="chapter-4.html"><a href="chapter-4.html#theory-and-practice"><i class="fa fa-check"></i><b>5.1</b> Theory and practice</a></li>
<li class="chapter" data-level="5.2" data-path="chapter-4.html"><a href="chapter-4.html#how-to-use-this-note-3"><i class="fa fa-check"></i><b>5.2</b> How to use this note</a></li>
<li class="chapter" data-level="5.3" data-path="chapter-4.html"><a href="chapter-4.html#learning-objectives-4"><i class="fa fa-check"></i><b>5.3</b> Learning objectives</a></li>
<li class="chapter" data-level="5.4" data-path="chapter-4.html"><a href="chapter-4.html#suggested-readings-3"><i class="fa fa-check"></i><b>5.4</b> Suggested readings</a></li>
<li class="chapter" data-level="5.5" data-path="chapter-4.html"><a href="chapter-4.html#preliminaries-2"><i class="fa fa-check"></i><b>5.5</b> Preliminaries</a></li>
<li class="chapter" data-level="5.6" data-path="chapter-4.html"><a href="chapter-4.html#the-anatomy-of-utility-functions"><i class="fa fa-check"></i><b>5.6</b> The anatomy of utility functions</a></li>
<li class="chapter" data-level="5.7" data-path="chapter-4.html"><a href="chapter-4.html#example-specifying-the-utility-functions"><i class="fa fa-check"></i><b>5.7</b> Example: Specifying the utility functions</a></li>
<li class="chapter" data-level="5.8" data-path="chapter-4.html"><a href="chapter-4.html#estimation"><i class="fa fa-check"></i><b>5.8</b> Estimation</a></li>
<li class="chapter" data-level="5.9" data-path="chapter-4.html"><a href="chapter-4.html#example-a-logit-model-of-mode-choice"><i class="fa fa-check"></i><b>5.9</b> Example: A logit model of mode choice</a></li>
<li class="chapter" data-level="5.10" data-path="chapter-4.html"><a href="chapter-4.html#comparing-models-mcfaddens-rho2"><i class="fa fa-check"></i><b>5.10</b> Comparing models: McFadden’s <span class="math inline">\(\rho^2\)</span></a></li>
<li class="chapter" data-level="5.11" data-path="chapter-4.html"><a href="chapter-4.html#comparing-models-the-likelihood-ratio-test"><i class="fa fa-check"></i><b>5.11</b> Comparing models: the likelihood ratio test</a></li>
<li class="chapter" data-level="5.12" data-path="chapter-4.html"><a href="chapter-4.html#exercise-3"><i class="fa fa-check"></i><b>5.12</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="chapter-5.html"><a href="chapter-5.html"><i class="fa fa-check"></i><b>6</b> Behavioral insights from choice models</a><ul>
<li class="chapter" data-level="6.1" data-path="chapter-5.html"><a href="chapter-5.html#inferring-and-forecasting-behavior"><i class="fa fa-check"></i><b>6.1</b> Inferring and forecasting behavior</a></li>
<li class="chapter" data-level="6.2" data-path="chapter-5.html"><a href="chapter-5.html#how-to-use-this-note-4"><i class="fa fa-check"></i><b>6.2</b> How to use this note</a></li>
<li class="chapter" data-level="6.3" data-path="chapter-5.html"><a href="chapter-5.html#learning-objectives-5"><i class="fa fa-check"></i><b>6.3</b> Learning objectives</a></li>
<li class="chapter" data-level="6.4" data-path="chapter-5.html"><a href="chapter-5.html#suggested-readings-4"><i class="fa fa-check"></i><b>6.4</b> Suggested readings</a></li>
<li class="chapter" data-level="6.5" data-path="chapter-5.html"><a href="chapter-5.html#preliminaries-3"><i class="fa fa-check"></i><b>6.5</b> Preliminaries</a></li>
<li class="chapter" data-level="6.6" data-path="chapter-5.html"><a href="chapter-5.html#the-meaning-of-the-coefficients"><i class="fa fa-check"></i><b>6.6</b> The meaning of the coefficients</a></li>
<li class="chapter" data-level="6.7" data-path="chapter-5.html"><a href="chapter-5.html#marginal-effects"><i class="fa fa-check"></i><b>6.7</b> Marginal effects</a><ul>
<li class="chapter" data-level="6.7.1" data-path="chapter-5.html"><a href="chapter-5.html#direct-marginal-effects"><i class="fa fa-check"></i><b>6.7.1</b> Direct marginal effects</a></li>
<li class="chapter" data-level="6.7.2" data-path="chapter-5.html"><a href="chapter-5.html#cross-marginal-effects"><i class="fa fa-check"></i><b>6.7.2</b> Cross-marginal effects</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="chapter-5.html"><a href="chapter-5.html#elasticity"><i class="fa fa-check"></i><b>6.8</b> Elasticity</a><ul>
<li class="chapter" data-level="6.8.1" data-path="chapter-5.html"><a href="chapter-5.html#direct-point-elasticity"><i class="fa fa-check"></i><b>6.8.1</b> Direct-point elasticity</a></li>
<li class="chapter" data-level="6.8.2" data-path="chapter-5.html"><a href="chapter-5.html#cross-point-elasticity"><i class="fa fa-check"></i><b>6.8.2</b> Cross-point elasticity</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="chapter-5.html"><a href="chapter-5.html#calculating-elasticities-based-on-an-mlogit-model"><i class="fa fa-check"></i><b>6.9</b> Calculating elasticities based on an <code>mlogit</code> model</a><ul>
<li class="chapter" data-level="6.9.1" data-path="chapter-5.html"><a href="chapter-5.html#computing-the-marginal-effects"><i class="fa fa-check"></i><b>6.9.1</b> Computing the marginal effects</a></li>
<li class="chapter" data-level="6.9.2" data-path="chapter-5.html"><a href="chapter-5.html#computing-the-elasticities"><i class="fa fa-check"></i><b>6.9.2</b> Computing the elasticities</a></li>
</ul></li>
<li class="chapter" data-level="6.10" data-path="chapter-5.html"><a href="chapter-5.html#a-note-about-attributes-in-dummy-format"><i class="fa fa-check"></i><b>6.10</b> A note about attributes in dummy format</a></li>
<li class="chapter" data-level="6.11" data-path="chapter-5.html"><a href="chapter-5.html#willingness-to-pay-and-discount-rate"><i class="fa fa-check"></i><b>6.11</b> Willingness to pay and discount rate</a></li>
<li class="chapter" data-level="6.12" data-path="chapter-5.html"><a href="chapter-5.html#simulating-market-changes"><i class="fa fa-check"></i><b>6.12</b> Simulating market changes</a><ul>
<li class="chapter" data-level="6.12.1" data-path="chapter-5.html"><a href="chapter-5.html#incentives"><i class="fa fa-check"></i><b>6.12.1</b> Incentives</a></li>
<li class="chapter" data-level="6.12.2" data-path="chapter-5.html"><a href="chapter-5.html#introduction-of-a-new-system"><i class="fa fa-check"></i><b>6.12.2</b> Introduction of a new system</a></li>
</ul></li>
<li class="chapter" data-level="6.13" data-path="chapter-5.html"><a href="chapter-5.html#exercise-4"><i class="fa fa-check"></i><b>6.13</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="chapter-6.html"><a href="chapter-6.html"><i class="fa fa-check"></i><b>7</b> Non-Proportional Substitution Patterns I: Generalized Extreme Value Models</a><ul>
<li class="chapter" data-level="7.1" data-path="chapter-6.html"><a href="chapter-6.html#preliminaries-4"><i class="fa fa-check"></i><b>7.1</b> Preliminaries</a></li>
<li class="chapter" data-level="7.2" data-path="chapter-6.html"><a href="chapter-6.html#the-limits-of-perfection"><i class="fa fa-check"></i><b>7.2</b> The limits of perfection</a></li>
<li class="chapter" data-level="7.3" data-path="chapter-6.html"><a href="chapter-6.html#how-to-use-this-note-5"><i class="fa fa-check"></i><b>7.3</b> How to use this note</a></li>
<li class="chapter" data-level="7.4" data-path="chapter-6.html"><a href="chapter-6.html#learning-objectives-6"><i class="fa fa-check"></i><b>7.4</b> Learning objectives</a></li>
<li class="chapter" data-level="7.5" data-path="chapter-6.html"><a href="chapter-6.html#suggested-readings-5"><i class="fa fa-check"></i><b>7.5</b> Suggested readings</a></li>
<li class="chapter" data-level="7.6" data-path="chapter-6.html"><a href="chapter-6.html#generalized-extreme-value-models-a-recipe-for-deriving-discrete-choice-models"><i class="fa fa-check"></i><b>7.6</b> Generalized Extreme Value models: a recipe for deriving discrete choice models</a></li>
<li class="chapter" data-level="7.7" data-path="chapter-6.html"><a href="chapter-6.html#nested-logit-model"><i class="fa fa-check"></i><b>7.7</b> Nested Logit model</a></li>
<li class="chapter" data-level="7.8" data-path="chapter-6.html"><a href="chapter-6.html#properties-of-the-nested-logit-model"><i class="fa fa-check"></i><b>7.8</b> Properties of the nested logit model</a></li>
<li class="chapter" data-level="7.9" data-path="chapter-6.html"><a href="chapter-6.html#estimation-of-the-nested-logit-model"><i class="fa fa-check"></i><b>7.9</b> Estimation of the nested logit model</a></li>
<li class="chapter" data-level="7.10" data-path="chapter-6.html"><a href="chapter-6.html#substitution-patterns-with-the-nested-logit-model"><i class="fa fa-check"></i><b>7.10</b> Substitution patterns with the nested logit model</a></li>
<li class="chapter" data-level="7.11" data-path="chapter-6.html"><a href="chapter-6.html#elasticities-of-the-nested-logit-model"><i class="fa fa-check"></i><b>7.11</b> Elasticities of the nested logit model</a></li>
<li class="chapter" data-level="7.12" data-path="chapter-6.html"><a href="chapter-6.html#exercise-5"><i class="fa fa-check"></i><b>7.12</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="chapter-7.html"><a href="chapter-7.html"><i class="fa fa-check"></i><b>8</b> Non-Proportional Substitution Patterns I: The Probit Model</a><ul>
<li class="chapter" data-level="8.1" data-path="chapter-7.html"><a href="chapter-7.html#preliminaries-5"><i class="fa fa-check"></i><b>8.1</b> Preliminaries</a></li>
<li class="chapter" data-level="8.2" data-path="chapter-7.html"><a href="chapter-7.html#more-flexible-substitution-patterns"><i class="fa fa-check"></i><b>8.2</b> More flexible substitution patterns</a></li>
<li class="chapter" data-level="8.3" data-path="chapter-7.html"><a href="chapter-7.html#how-to-use-this-note-6"><i class="fa fa-check"></i><b>8.3</b> How to use this note</a></li>
<li class="chapter" data-level="8.4" data-path="chapter-7.html"><a href="chapter-7.html#learning-objectives-7"><i class="fa fa-check"></i><b>8.4</b> Learning objectives</a></li>
<li class="chapter" data-level="8.5" data-path="chapter-7.html"><a href="chapter-7.html#suggested-readings-6"><i class="fa fa-check"></i><b>8.5</b> Suggested readings</a></li>
<li class="chapter" data-level="8.6" data-path="chapter-7.html"><a href="chapter-7.html#probit-model"><i class="fa fa-check"></i><b>8.6</b> Probit model</a></li>
<li class="chapter" data-level="8.7" data-path="chapter-7.html"><a href="chapter-7.html#exercise-6"><i class="fa fa-check"></i><b>8.7</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="chapter-8.html"><a href="chapter-8.html"><i class="fa fa-check"></i><b>9</b> Dealing with Heterogeneity I: The Mixed Logit Model</a><ul>
<li class="chapter" data-level="9.1" data-path="chapter-8.html"><a href="chapter-8.html#preliminaries-6"><i class="fa fa-check"></i><b>9.1</b> Preliminaries</a></li>
<li class="chapter" data-level="9.2" data-path="chapter-8.html"><a href="chapter-8.html#taste-variations-in-the-population"><i class="fa fa-check"></i><b>9.2</b> Taste variations in the population</a></li>
<li class="chapter" data-level="9.3" data-path="chapter-8.html"><a href="chapter-8.html#how-to-use-this-note-7"><i class="fa fa-check"></i><b>9.3</b> How to use this note</a></li>
<li class="chapter" data-level="9.4" data-path="chapter-8.html"><a href="chapter-8.html#learning-objectives-8"><i class="fa fa-check"></i><b>9.4</b> Learning objectives</a></li>
<li class="chapter" data-level="9.5" data-path="chapter-8.html"><a href="chapter-8.html#suggested-readings-7"><i class="fa fa-check"></i><b>9.5</b> Suggested readings</a></li>
<li class="chapter" data-level="9.6" data-path="chapter-8.html"><a href="chapter-8.html#mixed-logit"><i class="fa fa-check"></i><b>9.6</b> Mixed logit</a></li>
<li class="chapter" data-level="9.7" data-path="chapter-8.html"><a href="chapter-8.html#estimation-1"><i class="fa fa-check"></i><b>9.7</b> Estimation</a></li>
<li class="chapter" data-level="9.8" data-path="chapter-8.html"><a href="chapter-8.html#practical-example"><i class="fa fa-check"></i><b>9.8</b> Practical example</a></li>
<li class="chapter" data-level="9.9" data-path="chapter-8.html"><a href="chapter-8.html#behavioral-insights-from-the-mixed-logit-model"><i class="fa fa-check"></i><b>9.9</b> Behavioral insights from the mixed logit model</a><ul>
<li class="chapter" data-level="9.9.1" data-path="chapter-8.html"><a href="chapter-8.html#unconditional-distribution-of-a-random-parameter"><i class="fa fa-check"></i><b>9.9.1</b> Unconditional distribution of a random parameter</a></li>
<li class="chapter" data-level="9.9.2" data-path="chapter-8.html"><a href="chapter-8.html#conditional-distribution-of-the-random-coefficients"><i class="fa fa-check"></i><b>9.9.2</b> Conditional distribution of the random coefficients</a></li>
</ul></li>
<li class="chapter" data-level="9.10" data-path="chapter-8.html"><a href="chapter-8.html#using-covariates-to-capture-variations-in-taste"><i class="fa fa-check"></i><b>9.10</b> Using covariates to capture variations in taste</a></li>
<li class="chapter" data-level="9.11" data-path="chapter-8.html"><a href="chapter-8.html#revisiting-the-example"><i class="fa fa-check"></i><b>9.11</b> Revisiting the example</a></li>
<li class="chapter" data-level="9.12" data-path="chapter-8.html"><a href="chapter-8.html#full-covariance-matrix-for-random-components"><i class="fa fa-check"></i><b>9.12</b> Full covariance matrix for random components</a></li>
<li class="chapter" data-level="9.13" data-path="chapter-8.html"><a href="chapter-8.html#final-remarks"><i class="fa fa-check"></i><b>9.13</b> Final remarks</a></li>
<li class="chapter" data-level="9.14" data-path="chapter-8.html"><a href="chapter-8.html#exercise-7"><i class="fa fa-check"></i><b>9.14</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="chapter-9.html"><a href="chapter-9.html"><i class="fa fa-check"></i><b>10</b> Dealing with Heterogeneity II: The Latent Class Logit Model</a><ul>
<li class="chapter" data-level="10.1" data-path="chapter-9.html"><a href="chapter-9.html#preliminaries-7"><i class="fa fa-check"></i><b>10.1</b> Preliminaries</a></li>
<li class="chapter" data-level="10.2" data-path="chapter-9.html"><a href="chapter-9.html#more-on-taste-variation"><i class="fa fa-check"></i><b>10.2</b> More on taste variation</a></li>
<li class="chapter" data-level="10.3" data-path="chapter-9.html"><a href="chapter-9.html#how-to-use-this-note-8"><i class="fa fa-check"></i><b>10.3</b> How to use this note</a></li>
<li class="chapter" data-level="10.4" data-path="chapter-9.html"><a href="chapter-9.html#learning-objectives-9"><i class="fa fa-check"></i><b>10.4</b> Learning objectives</a></li>
<li class="chapter" data-level="10.5" data-path="chapter-9.html"><a href="chapter-9.html#suggested-readings-8"><i class="fa fa-check"></i><b>10.5</b> Suggested readings</a></li>
<li class="chapter" data-level="10.6" data-path="chapter-9.html"><a href="chapter-9.html#latent-class-logit"><i class="fa fa-check"></i><b>10.6</b> Latent class logit</a></li>
<li class="chapter" data-level="10.7" data-path="chapter-9.html"><a href="chapter-9.html#estimation-2"><i class="fa fa-check"></i><b>10.7</b> Estimation</a></li>
<li class="chapter" data-level="10.8" data-path="chapter-9.html"><a href="chapter-9.html#properties-of-the-latent-class-logit-model"><i class="fa fa-check"></i><b>10.8</b> Properties of the latent class logit model</a></li>
<li class="chapter" data-level="10.9" data-path="chapter-9.html"><a href="chapter-9.html#empirical-example"><i class="fa fa-check"></i><b>10.9</b> Empirical example</a></li>
<li class="chapter" data-level="10.10" data-path="chapter-9.html"><a href="chapter-9.html#adding-individual-level-attributes"><i class="fa fa-check"></i><b>10.10</b> Adding individual-level attributes</a></li>
<li class="chapter" data-level="10.11" data-path="chapter-9.html"><a href="chapter-9.html#adding-variables-to-the-latent-class-selection-model"><i class="fa fa-check"></i><b>10.11</b> Adding variables to the latent class selection model</a></li>
<li class="chapter" data-level="10.12" data-path="chapter-9.html"><a href="chapter-9.html#exercise-8"><i class="fa fa-check"></i><b>10.12</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="chapter-10.html"><a href="chapter-10.html"><i class="fa fa-check"></i><b>11</b> Ordinal and Ranked Responses</a><ul>
<li class="chapter" data-level="11.1" data-path="chapter-10.html"><a href="chapter-10.html#preliminaries-8"><i class="fa fa-check"></i><b>11.1</b> Preliminaries</a></li>
<li class="chapter" data-level="11.2" data-path="chapter-10.html"><a href="chapter-10.html#more-on-taste-variation-1"><i class="fa fa-check"></i><b>11.2</b> More on taste variation</a></li>
<li class="chapter" data-level="11.3" data-path="chapter-10.html"><a href="chapter-10.html#how-to-use-this-note-9"><i class="fa fa-check"></i><b>11.3</b> How to use this note</a></li>
<li class="chapter" data-level="11.4" data-path="chapter-10.html"><a href="chapter-10.html#learning-objectives-10"><i class="fa fa-check"></i><b>11.4</b> Learning objectives</a></li>
<li class="chapter" data-level="11.5" data-path="chapter-10.html"><a href="chapter-10.html#suggested-readings-9"><i class="fa fa-check"></i><b>11.5</b> Suggested readings</a></li>
<li class="chapter" data-level="11.6" data-path="chapter-10.html"><a href="chapter-10.html#latent-class-logit-1"><i class="fa fa-check"></i><b>11.6</b> Latent class logit</a></li>
<li class="chapter" data-level="11.7" data-path="chapter-10.html"><a href="chapter-10.html#estimation-3"><i class="fa fa-check"></i><b>11.7</b> Estimation</a></li>
<li class="chapter" data-level="11.8" data-path="chapter-10.html"><a href="chapter-10.html#properties-of-the-latent-class-logit-model-1"><i class="fa fa-check"></i><b>11.8</b> Properties of the latent class logit model</a></li>
<li class="chapter" data-level="11.9" data-path="chapter-10.html"><a href="chapter-10.html#empirical-example-1"><i class="fa fa-check"></i><b>11.9</b> Empirical example</a></li>
<li class="chapter" data-level="11.10" data-path="chapter-10.html"><a href="chapter-10.html#adding-individual-level-attributes-1"><i class="fa fa-check"></i><b>11.10</b> Adding individual-level attributes</a></li>
<li class="chapter" data-level="11.11" data-path="chapter-10.html"><a href="chapter-10.html#adding-variables-to-the-latent-class-selection-model-1"><i class="fa fa-check"></i><b>11.11</b> Adding variables to the latent class selection model</a></li>
<li class="chapter" data-level="11.12" data-path="chapter-10.html"><a href="chapter-10.html#exercise-9"><i class="fa fa-check"></i><b>11.12</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An Introduction to Discrete Choice Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chapter-10" class="section level1">
<h1><span class="header-section-number">Chapter 11</span> Ordinal and Ranked Responses</h1>
<blockquote>
<p>“I can’t rank anything. I mean, how could anyone possibly say what their favourite piece of music is? I don’t have the ability or the desire to categorise things of that nature.”</p>
<p>— Charlie Brooker</p>
</blockquote>
<div id="preliminaries-8" class="section level2">
<h2><span class="header-section-number">11.1</span> Preliminaries</h2>
<p>Load the packages used in this section:</p>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb376-1" title="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb376-2" title="2"><span class="co">#library(mlogit)</span></a>
<a class="sourceLine" id="cb376-3" title="3"><span class="co">#library(gmnl)</span></a>
<a class="sourceLine" id="cb376-4" title="4"><span class="kw">library</span>(kableExtra)</a>
<a class="sourceLine" id="cb376-5" title="5"><span class="kw">library</span>(gridExtra)</a></code></pre></div>
<p>Load the dataset used in this chapter, from the <code>mlogit</code> package:</p>
<div class="sourceCode" id="cb377"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb377-1" title="1"><span class="kw">library</span>(readxl)</a>
<a class="sourceLine" id="cb377-2" title="2">Individual_DA_Data_Built_Environment &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;Raw/Examples/Sense of Community/Individual+DA Data+Built Environment.xls&quot;</span>)</a>
<a class="sourceLine" id="cb377-3" title="3"><span class="kw">View</span>(Individual_DA_Data_Built_Environment)</a></code></pre></div>
<p>This dataset is from a study reported by Leon and Miguel <span class="citation">(<a href="#ref-Leon2017risky" role="doc-biblioref">2017</a>)</span> on the transportation choices of individuals travelling to and from the airport in Freetown, Sierra Leone. This airport is not on the mainland, and the alternatives for travel are ferry, hovercraft, helicopter, and water taxi. Information about the number of fatalities due to accidents by each of these modes allowed the researchers to calculate the mortality risk by mode.</p>
<p>The choice set is not balanced, meaning that not all alternatives were available to all individuals surveyed for this study. This is due to the seasonality or occasional unavailability of some modes. For the example in this chapter, we will extract a subset of observations for those individuals who had the four alternatives available as part of their choice set. To do this, we identify all respondents with four modes:</p>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb378-1" title="1">all_available &lt;-<span class="st"> </span>RiskyTransport <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(chid) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>(<span class="dt">no_rows =</span> <span class="kw">length</span>(chid)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(no_rows <span class="op">==</span><span class="st"> </span><span class="dv">4</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(chid)</a></code></pre></div>
<p>Next, we do an inner join of those respondents with the full dataset. This joins will only preserve the rows in the table corresponding to the respondents in <code>all_available</code>:</p>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb379-1" title="1">RT &lt;-<span class="st"> </span><span class="kw">inner_join</span>(RiskyTransport, all_available, <span class="dt">by =</span> <span class="st">&quot;chid&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">drop_na</span>()</a></code></pre></div>
<p>The two key variables (in addition to the mode chosen) are the generalized cost of the transport mode (<code>cost</code>) and the fatality rate in deaths per 100,000 trips (<code>risk</code>). The following table presents the descriptive statistics for the different modes of transportation:</p>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb380-1" title="1">df &lt;-<span class="st"> </span>RT <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(mode) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarize</span>(<span class="dt">use =</span> <span class="kw">sum</span>(choice),</a>
<a class="sourceLine" id="cb380-2" title="2">                                    <span class="dt">min_cost =</span> <span class="kw">min</span>(cost), <span class="dt">mean_cost =</span> <span class="kw">mean</span>(cost), <span class="dt">max_cost =</span> <span class="kw">max</span>(cost),</a>
<a class="sourceLine" id="cb380-3" title="3">                                    <span class="dt">min_risk =</span> <span class="kw">min</span>(risk), <span class="dt">mean_risk =</span> <span class="kw">mean</span>(risk), <span class="dt">max_risk =</span> <span class="kw">max</span>(risk))</a>
<a class="sourceLine" id="cb380-4" title="4">df<span class="op">$</span>use &lt;-<span class="st"> </span>df<span class="op">$</span>use<span class="op">/</span><span class="kw">sum</span>(df<span class="op">$</span>use)</a>
<a class="sourceLine" id="cb380-5" title="5"></a>
<a class="sourceLine" id="cb380-6" title="6"><span class="kw">kable</span>(df, </a>
<a class="sourceLine" id="cb380-7" title="7">      <span class="st">&quot;html&quot;</span>,</a>
<a class="sourceLine" id="cb380-8" title="8">      <span class="dt">digits =</span> <span class="dv">4</span>,</a>
<a class="sourceLine" id="cb380-9" title="9">      <span class="dt">col.names =</span> <span class="kw">c</span>(<span class="st">&quot;Mode&quot;</span>,</a>
<a class="sourceLine" id="cb380-10" title="10">                    <span class="st">&quot;Proportion&quot;</span>,</a>
<a class="sourceLine" id="cb380-11" title="11">                    <span class="st">&quot;Min&quot;</span>,</a>
<a class="sourceLine" id="cb380-12" title="12">                    <span class="st">&quot;Mean&quot;</span>,</a>
<a class="sourceLine" id="cb380-13" title="13">                    <span class="st">&quot;Max&quot;</span>,</a>
<a class="sourceLine" id="cb380-14" title="14">                    <span class="st">&quot;Min&quot;</span>,</a>
<a class="sourceLine" id="cb380-15" title="15">                    <span class="st">&quot;Mean&quot;</span>,</a>
<a class="sourceLine" id="cb380-16" title="16">                    <span class="st">&quot;Max&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb380-17" title="17"><span class="st">  </span><span class="kw">kable_styling</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb380-18" title="18"><span class="st">  </span><span class="kw">add_header_above</span>(<span class="kw">c</span>(<span class="st">&quot; &quot;</span> =<span class="st"> </span><span class="dv">2</span>, <span class="st">&quot;Cost&quot;</span> =<span class="st"> </span><span class="dv">3</span>, <span class="st">&quot;Risk&quot;</span> =<span class="st"> </span><span class="dv">3</span>))</a></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="border-bottom:hidden" colspan="2">
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="3">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Cost
</div>
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="3">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Risk
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
Mode
</th>
<th style="text-align:right;">
Proportion
</th>
<th style="text-align:right;">
Min
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
Max
</th>
<th style="text-align:right;">
Min
</th>
<th style="text-align:right;">
Mean
</th>
<th style="text-align:right;">
Max
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Helicopter
</td>
<td style="text-align:right;">
0.0031
</td>
<td style="text-align:right;">
54.2802
</td>
<td style="text-align:right;">
155.5311
</td>
<td style="text-align:right;">
312.9832
</td>
<td style="text-align:right;">
18.4082
</td>
<td style="text-align:right;">
18.4082
</td>
<td style="text-align:right;">
18.4082
</td>
</tr>
<tr>
<td style="text-align:left;">
WaterTaxi
</td>
<td style="text-align:right;">
0.4031
</td>
<td style="text-align:right;">
31.2185
</td>
<td style="text-align:right;">
95.5302
</td>
<td style="text-align:right;">
270.9509
</td>
<td style="text-align:right;">
2.5513
</td>
<td style="text-align:right;">
2.5513
</td>
<td style="text-align:right;">
2.5513
</td>
</tr>
<tr>
<td style="text-align:left;">
Ferry
</td>
<td style="text-align:right;">
0.4594
</td>
<td style="text-align:right;">
1.6065
</td>
<td style="text-align:right;">
63.9575
</td>
<td style="text-align:right;">
510.8410
</td>
<td style="text-align:right;">
4.4312
</td>
<td style="text-align:right;">
4.4312
</td>
<td style="text-align:right;">
4.4312
</td>
</tr>
<tr>
<td style="text-align:left;">
Hovercraft
</td>
<td style="text-align:right;">
0.1344
</td>
<td style="text-align:right;">
30.7787
</td>
<td style="text-align:right;">
108.9716
</td>
<td style="text-align:right;">
282.4194
</td>
<td style="text-align:right;">
3.8818
</td>
<td style="text-align:right;">
3.8818
</td>
<td style="text-align:right;">
3.8818
</td>
</tr>
</tbody>
</table>
<p>The two most popular modes are Water Taxi and Ferry, with Hovercraft as a distant third. Helicopter is the most expensive mode and the least popular, in addition to being the riskier. Notice that while the cost by mode varies (due to seasonal variations in fare), <code>risk</code> is in fact a constant for each mode. For this reason, and to avoid perfect multicollinearity, any models that use this variable cannot include a constant term.</p>
<p>The dataset includes information on number of seats, noise, crowdness, convenience of location, and clientele by mode. Finally, it includes information about the decision-makers, including whether they are African, their declared life expectancy, their declared hourly wage, their imputed hourly wage, their level of education, a self-ranked response on their degree of fatalism, gender, age, whether they have children, and if they know how to swim.</p>
<p>Althought the survey includes sample weights, we will ignore those after subsetting the data.</p>
<p>We add to the dataset some interactions and non-linear terms:</p>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb381-1" title="1">RT &lt;-<span class="st"> </span>RT <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="st">`</span><span class="dt">cost:dwage</span><span class="st">`</span> =<span class="st"> </span>cost <span class="op">*</span><span class="st"> </span>dwage,</a>
<a class="sourceLine" id="cb381-2" title="2">                    <span class="st">`</span><span class="dt">risk:dwage</span><span class="st">`</span> =<span class="st"> </span>risk <span class="op">*</span><span class="st"> </span>dwage,</a>
<a class="sourceLine" id="cb381-3" title="3">                    <span class="dt">dwage2 =</span> dwage<span class="op">^</span><span class="dv">2</span>)</a></code></pre></div>
<p>Next, we use <code>mlogit.data</code> to format the table for use with <code>mlogit</code> and <code>gmnl</code>:</p>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb382-1" title="1">RT &lt;-<span class="st"> </span><span class="kw">mlogit.data</span>(RT, <span class="dt">shape =</span> <span class="st">&quot;long&quot;</span>, <span class="dt">choice =</span> <span class="st">&quot;choice&quot;</span>, <span class="dt">alt.var =</span> <span class="st">&quot;mode&quot;</span>, <span class="dt">id.var =</span> <span class="st">&quot;id&quot;</span>)</a></code></pre></div>
</div>
<div id="more-on-taste-variation-1" class="section level2">
<h2><span class="header-section-number">11.2</span> More on taste variation</h2>
<p>Chapter <a href="chapter-8.html#chapter-8">9</a> introduced the mixed logit model, a technique useful to model taste variation. In this chapter, a variation on the theme will be introduced, namely the latent class logit model. We will see how the latent class model is related to the mixed logit model.</p>
</div>
<div id="how-to-use-this-note-9" class="section level2">
<h2><span class="header-section-number">11.3</span> How to use this note</h2>
<p>Remember that the source for the document you are reading is an R Notebook. Throughout the notes, you will find examples of code in segments of text called <em>chunks</em>. This is an example of a chunk:</p>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb383-1" title="1"><span class="kw">print</span>(<span class="st">&quot;Ignorance is the foundation of absolute power&quot;</span>)</a></code></pre></div>
<pre><code>## [1] &quot;Ignorance is the foundation of absolute power&quot;</code></pre>
<p>If you are working with the Notebook version of the document, you can run the code by clicking the ‘play’ icon on the top right corner of the chunk. If you are reading the web-book version of the document, you will often see that the code has already been executed. You can still try it by copying and pasting into your R or RStudio console.</p>
</div>
<div id="learning-objectives-10" class="section level2">
<h2><span class="header-section-number">11.4</span> Learning objectives</h2>
<p>In this practice, you will learn about:</p>
<ol style="list-style-type: decimal">
<li>A framework for modeling taste variations.</li>
<li>The latent class logit model.</li>
<li>Behavioral insights of the latent class logit model.</li>
</ol>
</div>
<div id="suggested-readings-9" class="section level2">
<h2><span class="header-section-number">11.5</span> Suggested readings</h2>
<ul>
<li>Louviere, J.J., Hensher, D.A., Swait, J.D. <span class="citation">(<a href="#ref-Louviere2000stated" role="doc-biblioref">2000</a>)</span> Stated Choice Methods: Analysis and Application, <strong>Chapter 6, pp. 205-206</strong>, Cambridge University Press.</li>
<li>Train <span class="citation">(<a href="#ref-Train2009discrete" role="doc-biblioref">2009</a>)</span> Discrete Choice Methods with Simulation, Second Edition, <strong>Chapter 6 pp. 135-136</strong>, Cambridge University Press.</li>
</ul>
</div>
<div id="latent-class-logit-1" class="section level2">
<h2><span class="header-section-number">11.6</span> Latent class logit</h2>
<p>To motivate the discussion, we begin by estimating a base model with two alternative-specific attributes, namely cost and risk.</p>
<p>The utility function for individual <span class="math inline">\(n\)</span> and mode <span class="math inline">\(i\)</span> is as follows:
<span class="math display">\[
V_{ni} = \beta_{cost} cost_i + \beta_{risk} {risk}_i
\]</span>
where <code>safe</code> is the probability of completing a trip safely.</p>
<p>This model is estimated as follows, supressing the constants in the second term of the formula:</p>
<div class="sourceCode" id="cb385"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb385-1" title="1">mnl.rt0 &lt;-<span class="st"> </span><span class="kw">mlogit</span>(choice <span class="op">~</span><span class="st"> </span>cost <span class="op">+</span><span class="st"> </span>risk <span class="op">|</span><span class="st"> </span><span class="dv">0</span>, </a>
<a class="sourceLine" id="cb385-2" title="2">                <span class="dt">data =</span> RT</a>
<a class="sourceLine" id="cb385-3" title="3">)</a>
<a class="sourceLine" id="cb385-4" title="4"><span class="kw">summary</span>(mnl.rt0)</a></code></pre></div>
<pre><code>## 
## Call:
## mlogit(formula = choice ~ cost + risk | 0, data = RT, method = &quot;nr&quot;)
## 
## Frequencies of alternatives:
## Helicopter  WaterTaxi      Ferry Hovercraft 
##   0.003125   0.403125   0.459375   0.134375 
## 
## nr method
## 8 iterations, 0h:0m:0s 
## g&#39;(-H)^-1g = 1.01E-06 
## successive function values within tolerance limits 
## 
## Coefficients :
##        Estimate Std. Error z-value  Pr(&gt;|z|)    
## cost -0.0140106  0.0020303 -6.9006 5.180e-12 ***
## risk -0.2530895  0.0487235 -5.1944 2.054e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Log-Likelihood: -335.21</code></pre>
<p>The coefficients for <code>cost</code> and <code>safe</code> provide useful information. In this case, the typical willingness to pay is as follows:
<span class="math display">\[
-\frac{\partial cost}{\partial risk} = \frac{\beta_{risk}}{\beta_{cost}}
\]</span>
Since the probability is of not surviving a trip, the ratio of the coefficients is the willingness to pay to reduce the risk of accidental death:
<span class="math display">\[
-\frac{\beta_{p_{safe}}}{\beta_{cost}} = \frac{-0.25309}{-0.01401} \simeq 18.06
\]</span></p>
<p>A question, however, is whether there are unobserved variations in the implicit behavior, that is, whether some individuals have more taste for life than other, and therefore their values for a statistical life vary.</p>
<p>We will redefine the utility functions of the model in the following manner:
<span class="math display">\[
V_{niq} = \beta_{q,cost} cost_i + \beta_{q,safe} {safe}_i
\]</span>
where <span class="math inline">\(q\)</span> is a subindex to indicate that the coefficients are not fixed for individual <span class="math inline">\(n\)</span>, but may vary. For instance, lets suppose that there are two classes, say cost-conscious individuals (class <span class="math inline">\(1\)</span>) and risk-conscious individuals (say class <span class="math inline">\(2\)</span>).</p>
<p>Now the utility functions are:
<span class="math display">\[
\begin{array}{c}
V_{ni1} = \beta_{1,cost} cost_i + \beta_{1,safe} {safe}_i\\
V_{ni2} = \beta_{2,cost} cost_i + \beta_{2,safe} {safe}_i
\end{array}
\]</span>
with:
<span class="math display">\[
\begin{array}{c}
\beta_{1,cost} \neq \beta_{1,cost}\\
\text{and}\\
\beta_{1,risk} \neq \beta_{1,risk}\\
\end{array}
\]</span></p>
<p>Making the usual assumption about the random utility (i.e., Extreme Value Type I), the probability that an individual who is cost-conscious will choose alternative <span class="math inline">\(i\)</span> is:
<span class="math display">\[
\frac{e^{V_{ni1}}}{\sum_k e^{V_{nk1}}}
\]</span>
and the probability that an individual who is risk-conscious will choose alternative <span class="math inline">\(i\)</span> is:
<span class="math display">\[
\frac{e^{V_{ni2}}}{\sum_k e^{V_{nk2}}}
\]</span></p>
<p>The issue, however, is that we do not know which decision-makers belong to which class, therefore the term <em>latent classes</em>. A way to proceed is to assume that decision-makers belong with certain probability to each class of decision makers, say <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span>. In this way, we can condition the probability of choosing <span class="math inline">\(i\)</span> on the probability of a decision-maker being in each class:
<span class="math display">\[
\begin{array}{l}
  P_{ni|1} = p_q\frac{e^{V_{ni1}}}{\sum_k e^{V_{nk1}}}\\
\text{and}\\
  P_{ni|2} = p_q\frac{e^{V_{ni2}}}{\sum_k e^{V_{nk2}}}\\
\end{array}
\]</span></p>
<p>The probability of belonging to each latent class can be defined by means of a logit-like expression:
<span class="math display">\[
\begin{array}{c}
p_1 = \frac{e^{\gamma_1}}{e^{\gamma_1} + e^{\gamma_2}}\\
\text{and}\\
p_2 = \frac{e^{\gamma_2}}{e^{\gamma_1} + e^{\gamma_2}}\\
\end{array}
\]</span>
or, if we define <span class="math inline">\(\gamma_1=0\)</span>:
<span class="math display">\[
\begin{array}{c}
p_1 = \frac{1}{1 + e^{\gamma_2}}\\
\text{and}\\
p_2 = \frac{e^{\gamma_2}}{1 + e^{\gamma_2}}\\
\end{array}
\]</span>
which implies that:
<span class="math display">\[
p_1 + p_2 = \frac{1}{1 + e^{\gamma_2}} + \frac{e^{\gamma_2}}{1 + e^{\gamma_2}} = 1
\]</span></p>
<p>Accordingly, the unconditional probability of the decision-maker choosing alternative <span class="math inline">\(i\)</span> is:
<span class="math display">\[
P_{ni} = p_1\frac{e^{V_{ni1}}}{\sum_k e^{V_{nk1}}} + p_2\frac{e^{V_{ni2}}}{\sum_k e^{V_{nk2}}}
\]</span></p>
<p>And since the sum of probabilities <span class="math inline">\(p_1 + p_2=1\)</span>, the unconditional probability is essentially the weighted average of the probabilities for each latent class.</p>
<p>More generally, we allow for an arbitrary number of groups <span class="math inline">\(q=1,2,\cdots,Q\)</span> each with their own distinctive set of coefficients, for <span class="math inline">\(Q\)</span> latent classes, and therefore, the unconditional probability of decision-maker <span class="math inline">\(n\)</span> choosing alternative <span class="math inline">\(i\)</span> is:
<span class="math display">\[
P_{ni} = \sum_q^Q P_{ni|q} = \sum_q^Q p_q\frac{e^{V_{niq}}}{\sum_k e^{V_{nkq}}}
\]</span>
and the probability of belonging to each group is:
<span class="math display">\[
p_q = \frac{e^{\gamma_q}}{\sum_{z=1}^Qe^{\gamma_z}}
\]</span>
with <span class="math inline">\(\gamma_1=0\)</span>.</p>
</div>
<div id="estimation-3" class="section level2">
<h2><span class="header-section-number">11.7</span> Estimation</h2>
<p>The log-likelihood function of the latent class logit model is this:
<span class="math display">\[
l = \sum_nln\Big[\sum_q p_q(\prod_i P_{ni}^{y_{ni}})\Big]
\]</span>
where <span class="math inline">\(y_{ni}\)</span> is an indicator variable that takes the value of one if decision maker <span class="math inline">\(n\)</span> chose alternative <span class="math inline">\(i\)</span>, and zero otherwise.</p>
<p>The log-likelihood function can be maximized using conventional optimization techniques, contingent on the selection of the number of latent classes <span class="math inline">\(Q\)</span>.</p>
</div>
<div id="properties-of-the-latent-class-logit-model-1" class="section level2">
<h2><span class="header-section-number">11.8</span> Properties of the latent class logit model</h2>
<p>Among the properties of the latent class logit, two are of interest.</p>
<p>The first one can be illustrated by means of the odds-ratio of two alternatives, say <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>:
<span class="math display">\[
\frac{P_{ni}}{P_{nj}} = \frac{\sum_q^Q p_q\frac{e^{V_{niq}}}{\sum_k e^{V_{nkq}}}}{\sum_q^Q p_q\frac{e^{V_{njq}}}{\sum_k e^{V_{nkq}}}}
\]</span></p>
<p>When <span class="math inline">\(Q=1\)</span> the model collapses to the multinomial logit model and proportional substitution patterns. When <span class="math inline">\(Q\ge3\)</span>, on the other hand, the denominator of the logit probabilities is inside the summation for the classes, and does not vanish:
<span class="math display">\[
\frac{P_{ni}}{P_{nj}} = \frac{p_1\frac{e^{V_{ni1}}}{\sum_k e^{V_{nk1}}} + p_2\frac{e^{V_{ni2}}}{\sum_k e^{V_{nk1}}} + p_3\frac{e^{V_{ni3}}}{\sum_k e^{V_{nk3}}}}{p_1\frac{e^{V_{nj1}}}{\sum_k e^{V_{nk1}}} + p_2\frac{e^{V_{nj2}}}{\sum_k e^{V_{nk1}}}+ p_3\frac{e^{V_{ni3}}}{\sum_k e^{V_{nk3}}}}
\]</span></p>
<p>Therefore, the latent class logit model does not display independence from irrelevant alterantives.</p>
<p>Secondly, latent class logit models with higher number of classes do <em>not</em> nest into each other. The reason for this is that the parameters that define the probability of belonging to a class are contingent on the number of classes. Therefore, reducing the number of classes, say from <span class="math inline">\(Q=3\)</span> to <span class="math inline">\(Q=2\)</span>, is not equivalent to restricting some parameters to be zero. As a consequence, latent class models cannot be compared by means of the likelihood ratio test. Further, since the log-likelihood always improves with the addition of classes, it is not possible to compare the likelihood directly.</p>
<p>Instead, criteria that account for the size of the models are used. Roeder et al. <span class="citation">(<a href="#ref-Roeder1999modeling" role="doc-biblioref">1999</a>)</span> suggest using the Bayesian Information Criterion:
<span class="math display">\[
BIC = k\ln(n)-2\hat{l}
\]</span>
where <span class="math inline">\(k\)</span> is the number of parameters in the model, <span class="math inline">\(n\)</span> is the sample size, and <span class="math inline">\(\hat{l}\)</span> is the maximized value of the likelihood of the model.</p>
<p>Shen <span class="citation">(<a href="#ref-Shen2009latent" role="doc-biblioref">2009</a>)</span> suggests using Akaike’s Information Criterion:
<span class="math display">\[
AIC = 2k-2\hat{l}
\]</span>
or Consistent Akaike’s Information Criterion:
<span class="math display">\[
CAIC = k[ln(n)+1]-2\hat{l}
\]</span>
The three criteria above use the likelihood of the model and apply a penalty based on the size of the model and possibly the size of the sample. Since the negative of the likelihood is used in the calculations, minimizing an information criteria is an indicator of goodness-of-fit.</p>
<p>In particular, when using <span class="math inline">\(AIC\)</span>, the following decision rule could be followed. Suppose that there are candidate models with <span class="math inline">\(q=1, 2, \cdots,Q\)</span> latent classes. Calculate the <span class="math inline">\(AIC\)</span> for each model, such that there are <span class="math inline">\(AIC_{q=1}, AIC_{q=2},\cdots, AIC_{q=Q}\)</span>. Denote the minimum <span class="math inline">\(AIC\)</span> as <span class="math inline">\(AIC_{min}\)</span>. The <em>relative likelihood</em> is defined as:
<span class="math display">\[
RL = e^{\frac{AIC_{min}-AIC_q}{2}}
\]</span>
The interpretation of the relative likelihood is as being proportional to the probability that the model with <span class="math inline">\(q\)</span> classes minimizes the estimated information loss.</p>
</div>
<div id="empirical-example-1" class="section level2">
<h2><span class="header-section-number">11.9</span> Empirical example</h2>
<p>Here we revisit the empirical example. To estimate latent class models we use the package <code>gmnl</code>. This package uses a similar syntax for specifying multi-part formulas as <code>mlogit</code>. In particular, the parts of a formula are:
<span class="math display">\[
\begin{array}{cr}
choice &amp; \sim&amp; \text{alternative attributes with generic coefficients } |\\
&amp;&amp;\text{individual attributes }|\\
&amp;&amp;\text{alternative attributes with specific coefficients }|\\
&amp;&amp;\text{variables for random coefficients }|\\
&amp;&amp;\text{variables for latent class model }\\
\end{array}
\]</span></p>
<p>We proceed to estimate latent class models as follows, with <span class="math inline">\(Q=2\)</span> and <span class="math inline">\(Q=3\)</span> (i.e., two and three latent classes):</p>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb387-1" title="1">lc2 &lt;-<span class="st"> </span><span class="kw">gmnl</span>(choice <span class="op">~</span><span class="st"> </span>cost <span class="op">+</span><span class="st"> </span>risk <span class="op">|</span><span class="st"> </span><span class="dv">0</span> <span class="op">|</span><span class="st"> </span><span class="dv">0</span> <span class="op">|</span><span class="st"> </span><span class="dv">0</span> <span class="op">|</span><span class="st"> </span><span class="dv">1</span>, </a>
<a class="sourceLine" id="cb387-2" title="2">           <span class="dt">data =</span> RT,</a>
<a class="sourceLine" id="cb387-3" title="3">           <span class="dt">model =</span> <span class="st">&#39;lc&#39;</span>, </a>
<a class="sourceLine" id="cb387-4" title="4">           <span class="dt">Q =</span> <span class="dv">2</span>,</a>
<a class="sourceLine" id="cb387-5" title="5">           <span class="dt">panel =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb387-6" title="6">           <span class="dt">method =</span> <span class="st">&quot;bhhh&quot;</span>)</a></code></pre></div>
<pre><code>## Estimating LC model</code></pre>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb389-1" title="1"><span class="co">#summary(lc2)</span></a>
<a class="sourceLine" id="cb389-2" title="2"></a>
<a class="sourceLine" id="cb389-3" title="3">lc3 &lt;-<span class="st"> </span><span class="kw">gmnl</span>(choice <span class="op">~</span><span class="st"> </span>cost <span class="op">+</span><span class="st"> </span>risk <span class="op">|</span><span class="st"> </span><span class="dv">0</span> <span class="op">|</span><span class="st"> </span><span class="dv">0</span> <span class="op">|</span><span class="st"> </span><span class="dv">0</span> <span class="op">|</span><span class="st"> </span><span class="dv">1</span>, </a>
<a class="sourceLine" id="cb389-4" title="4">           <span class="dt">data =</span> RT,</a>
<a class="sourceLine" id="cb389-5" title="5">           <span class="dt">model =</span> <span class="st">&#39;lc&#39;</span>, </a>
<a class="sourceLine" id="cb389-6" title="6">           <span class="dt">Q =</span> <span class="dv">3</span>,</a>
<a class="sourceLine" id="cb389-7" title="7">           <span class="dt">panel =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb389-8" title="8">           <span class="dt">method =</span> <span class="st">&quot;bhhh&quot;</span>)</a></code></pre></div>
<pre><code>## Estimating LC model</code></pre>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb391-1" title="1"><span class="co">#summary(lc3)</span></a></code></pre></div>
<p>The results of these models are summarized in the table below.</p>
<div class="sourceCode" id="cb392"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb392-1" title="1"><span class="co"># Estimate a constants only model to calculate McFadden&#39;s _adjusted_ rho2</span></a>
<a class="sourceLine" id="cb392-2" title="2"></a>
<a class="sourceLine" id="cb392-3" title="3"><span class="kw">names</span>(mnl.rt0<span class="op">$</span>coefficients) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;class.1.cost&quot;</span>, <span class="st">&quot;class.1.risk&quot;</span>)</a>
<a class="sourceLine" id="cb392-4" title="4"></a>
<a class="sourceLine" id="cb392-5" title="5">mnl0.summary &lt;-<span class="st"> </span><span class="kw">rownames_to_column</span>(<span class="kw">data.frame</span>(<span class="kw">summary</span>(mnl.rt0)<span class="op">$</span>CoefTable), <span class="st">&quot;Variable&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb392-6" title="6"><span class="st">  </span><span class="kw">transmute</span>(Variable, Estimate, <span class="dt">pval =</span> <span class="st">`</span><span class="dt">Pr...z..</span><span class="st">`</span>)</a>
<a class="sourceLine" id="cb392-7" title="7"></a>
<a class="sourceLine" id="cb392-8" title="8">lc2.summary &lt;-<span class="st"> </span><span class="kw">rownames_to_column</span>(<span class="kw">data.frame</span>(<span class="kw">summary</span>(lc2)<span class="op">$</span>CoefTable), <span class="st">&quot;Variable&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb392-9" title="9"><span class="st">  </span><span class="kw">transmute</span>(Variable, Estimate, <span class="dt">pval =</span> <span class="st">`</span><span class="dt">Pr...z..</span><span class="st">`</span>)</a>
<a class="sourceLine" id="cb392-10" title="10"></a>
<a class="sourceLine" id="cb392-11" title="11">lc3.summary &lt;-<span class="st"> </span><span class="kw">rownames_to_column</span>(<span class="kw">data.frame</span>(<span class="kw">summary</span>(lc3)<span class="op">$</span>CoefTable), <span class="st">&quot;Variable&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb392-12" title="12"><span class="st">  </span><span class="kw">transmute</span>(Variable, Estimate, <span class="dt">pval =</span> <span class="st">`</span><span class="dt">Pr...z..</span><span class="st">`</span>)</a>
<a class="sourceLine" id="cb392-13" title="13"></a>
<a class="sourceLine" id="cb392-14" title="14">df &lt;-<span class="st"> </span><span class="kw">full_join</span>(mnl0.summary, lc2.summary, <span class="dt">by =</span> <span class="st">&quot;Variable&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb392-15" title="15"><span class="st">  </span><span class="kw">full_join</span>(lc3.summary, <span class="dt">by =</span> <span class="st">&quot;Variable&quot;</span>)</a>
<a class="sourceLine" id="cb392-16" title="16"></a>
<a class="sourceLine" id="cb392-17" title="17"><span class="kw">kable</span>(df, </a>
<a class="sourceLine" id="cb392-18" title="18">      <span class="st">&quot;html&quot;</span>,</a>
<a class="sourceLine" id="cb392-19" title="19">      <span class="dt">digits =</span> <span class="dv">4</span>,</a>
<a class="sourceLine" id="cb392-20" title="20">      <span class="dt">col.names =</span> <span class="kw">c</span>(<span class="st">&quot;Variable&quot;</span>,</a>
<a class="sourceLine" id="cb392-21" title="21">                    <span class="st">&quot;Estimate&quot;</span>,</a>
<a class="sourceLine" id="cb392-22" title="22">                    <span class="st">&quot;p-value&quot;</span>,</a>
<a class="sourceLine" id="cb392-23" title="23">                    <span class="st">&quot;Estimate&quot;</span>,</a>
<a class="sourceLine" id="cb392-24" title="24">                    <span class="st">&quot;p-value&quot;</span>,</a>
<a class="sourceLine" id="cb392-25" title="25">                    <span class="st">&quot;Estimate&quot;</span>,</a>
<a class="sourceLine" id="cb392-26" title="26">                    <span class="st">&quot;p-value&quot;</span>),</a>
<a class="sourceLine" id="cb392-27" title="27">      <span class="dt">caption =</span> <span class="st">&quot;Base models: multinomial logit (MNL), latent class Q = 2 (LC2), latent class Q = 3 (LC3)&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb392-28" title="28"><span class="st">  </span><span class="kw">kable_styling</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb392-29" title="29"><span class="st">  </span><span class="kw">add_header_above</span>(<span class="kw">c</span>(<span class="st">&quot; &quot;</span> =<span class="st"> </span><span class="dv">1</span>, <span class="st">&quot;MNL&quot;</span> =<span class="st"> </span><span class="dv">2</span>, <span class="st">&quot;LC2&quot;</span> =<span class="st"> </span><span class="dv">2</span>, <span class="st">&quot;LC3&quot;</span> =<span class="st"> </span><span class="dv">2</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb392-30" title="30"><span class="st">  </span><span class="kw">footnote</span>(<span class="dt">general =</span> <span class="kw">c</span>(<span class="kw">paste0</span>(<span class="st">&quot;Log-Likelihood: MNL = &quot;</span>, <span class="kw">round</span>(mnl.rt0<span class="op">$</span>logLik[<span class="dv">1</span>], <span class="dt">digits =</span> <span class="dv">3</span>),</a>
<a class="sourceLine" id="cb392-31" title="31">                            <span class="st">&quot;; Latent Class (Q=2) = &quot;</span>, <span class="kw">round</span>(lc2<span class="op">$</span>logLik<span class="op">$</span>maximum, <span class="dt">digits =</span> <span class="dv">3</span>),</a>
<a class="sourceLine" id="cb392-32" title="32">                            <span class="st">&quot;; Latent Class (Q=2) = &quot;</span>, <span class="kw">round</span>(lc3<span class="op">$</span>logLik<span class="op">$</span>maximum, <span class="dt">digits =</span> <span class="dv">3</span>))))</a></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-216">Table 11.1: </span>Base models: multinomial logit (MNL), latent class Q = 2 (LC2), latent class Q = 3 (LC3)
</caption>
<thead>
<tr>
<th style="border-bottom:hidden" colspan="1">
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
MNL
</div>
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
LC2
</div>
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
LC3
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
Variable
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
p-value
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
p-value
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
p-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
class.1.cost
</td>
<td style="text-align:right;">
-0.0140
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
-0.1256
</td>
<td style="text-align:right;">
0.0167
</td>
<td style="text-align:right;">
-0.1151
</td>
<td style="text-align:right;">
0.0202
</td>
</tr>
<tr>
<td style="text-align:left;">
class.1.risk
</td>
<td style="text-align:right;">
-0.2531
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
-0.6347
</td>
<td style="text-align:right;">
0.1540
</td>
<td style="text-align:right;">
-0.0365
</td>
<td style="text-align:right;">
0.9260
</td>
</tr>
<tr>
<td style="text-align:left;">
class.2.cost
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.0026
</td>
<td style="text-align:right;">
0.3359
</td>
<td style="text-align:right;">
-0.0678
</td>
<td style="text-align:right;">
0.0044
</td>
</tr>
<tr>
<td style="text-align:left;">
class.2.risk
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
-0.3725
</td>
<td style="text-align:right;">
0.0000
</td>
<td style="text-align:right;">
-2.4147
</td>
<td style="text-align:right;">
0.0026
</td>
</tr>
<tr>
<td style="text-align:left;">
(class)2
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.4207
</td>
<td style="text-align:right;">
0.0115
</td>
<td style="text-align:right;">
-0.0886
</td>
<td style="text-align:right;">
0.7050
</td>
</tr>
<tr>
<td style="text-align:left;">
class.3.cost
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.0097
</td>
<td style="text-align:right;">
0.0048
</td>
</tr>
<tr>
<td style="text-align:left;">
class.3.risk
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
-0.2766
</td>
<td style="text-align:right;">
0.0633
</td>
</tr>
<tr>
<td style="text-align:left;">
(class)3
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.0787
</td>
<td style="text-align:right;">
0.7126
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<span style="font-style: italic;">Note: </span>
</td>
</tr>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<sup></sup> Log-Likelihood: MNL = -335.213; Latent Class (Q=2) = -310.677; Latent Class (Q=2) = -299.196
</td>
</tr>
</tfoot>
</table>
<p>Notice that model LC3, despite improving the likelihood, returns non-significant parameters for the latent class model. For this reason, we compare only the multinomila logit model and LC2.</p>
<p>The <span class="math inline">\(AIC\)</span> of the base multinomial logit model is:</p>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb393-1" title="1"><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">length</span>(<span class="kw">coef</span>(mnl.rt0)) <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>mnl.rt0<span class="op">$</span>logLik</a></code></pre></div>
<pre><code>## &#39;log Lik.&#39; 674.426 (df=2)</code></pre>
<p>The <span class="math inline">\(AIC\)</span> of model LC2 is:</p>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb395-1" title="1"><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">length</span>(<span class="kw">coef</span>(lc2)) <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>lc2<span class="op">$</span>logLik<span class="op">$</span>maximum</a></code></pre></div>
<pre><code>## [1] 631.3531
## attr(,&quot;df&quot;)
## [1] 5</code></pre>
<p>The minimum <span class="math inline">\(AIC\)</span> is for the latent class model. If we calculate the relative likelihood:</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb397-1" title="1"><span class="kw">as.numeric</span>(<span class="kw">exp</span>(((<span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">length</span>(<span class="kw">coef</span>(lc2)) <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>lc2<span class="op">$</span>logLik<span class="op">$</span>maximum) <span class="op">-</span><span class="st"> </span>(<span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">length</span>(<span class="kw">coef</span>(mnl.rt0)) <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>mnl.rt0<span class="op">$</span>logLik))<span class="op">/</span><span class="dv">2</span>))</a></code></pre></div>
<pre><code>## [1] 4.434555e-10</code></pre>
<p>Therefore, the standard multinomial logit model is less than <span class="math inline">\(0.001\)</span> times probable as the latent class model with <span class="math inline">\(Q=2\)</span> to minimize the information loss.</p>
<p>Notice that in the latent class model, the coefficient for risk in class 1 is not significant, whereas the coefficient for cost in class 2 is not significant. This suggests that class 1 is more cost-averse and class 2 more risk-averse.</p>
<p>To calculate the shares of the latent classes in the population, we can write the latent class model as follows:
<span class="math display">\[
p_2 = \frac{e^{0.4207}}{1 + e^{0.4207}}
\]</span>
and:
<span class="math display">\[
p_1 = 1 - p_2
\]</span></p>
<p>Therefore, the share for class 1 is:</p>
<div class="sourceCode" id="cb399"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb399-1" title="1"><span class="kw">as.numeric</span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">exp</span>(<span class="kw">coef</span>(lc2)[<span class="st">&quot;(class)2&quot;</span>])<span class="op">/</span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span><span class="kw">exp</span>(<span class="kw">coef</span>(lc2)[<span class="st">&quot;(class)2&quot;</span>])))</a></code></pre></div>
<pre><code>## [1] 0.3963601</code></pre>
<p>and the share for class 2 is:</p>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb401-1" title="1"><span class="kw">as.numeric</span>(<span class="kw">exp</span>(<span class="kw">coef</span>(lc2)[<span class="st">&quot;(class)2&quot;</span>])<span class="op">/</span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span><span class="kw">exp</span>(<span class="kw">coef</span>(lc2)[<span class="st">&quot;(class)2&quot;</span>])))</a></code></pre></div>
<pre><code>## [1] 0.6036399</code></pre>
</div>
<div id="adding-individual-level-attributes-1" class="section level2">
<h2><span class="header-section-number">11.10</span> Adding individual-level attributes</h2>
<p>A question when doing this kind of analysis is, to what extent can the inclusion of individual-level attributes capture the variations in taste.</p>
<p>Here, we revisit the models after adding covariates. There are two multinomial logit models. In one, we introduce the same covariate to all but one utility function (MNL-COV), and in a second model the covariate is used to expand the coefficients of the alternative-level attributes as follows:
<span class="math display">\[
V_{ni} = (b_{cost} + b_{cost:dwage}dwage_n)cost_i + (b_{risk} + b_{risk:dwage}dwage_n)risk_i
\]</span></p>
<p>These models are estimated next:</p>
<div class="sourceCode" id="cb403"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb403-1" title="1">mnl.cov &lt;-<span class="st"> </span><span class="kw">mlogit</span>(choice <span class="op">~</span><span class="st"> </span>cost <span class="op">+</span><span class="st"> </span>risk <span class="op">|</span><span class="st"> </span>dwage <span class="op">+</span><span class="st"> </span><span class="dv">0</span>, </a>
<a class="sourceLine" id="cb403-2" title="2">                <span class="dt">data =</span> RT)</a>
<a class="sourceLine" id="cb403-3" title="3"><span class="co">#summary(mnl.cov)</span></a>
<a class="sourceLine" id="cb403-4" title="4"></a>
<a class="sourceLine" id="cb403-5" title="5">mnl.exp &lt;-<span class="st"> </span><span class="kw">mlogit</span>(choice <span class="op">~</span><span class="st"> </span>cost <span class="op">+</span><span class="st"> </span>cost<span class="op">:</span>dwage <span class="op">+</span></a>
<a class="sourceLine" id="cb403-6" title="6"><span class="st">                   </span>risk <span class="op">+</span><span class="st"> </span>risk<span class="op">:</span>dwage <span class="op">|</span><span class="st"> </span><span class="dv">0</span>, </a>
<a class="sourceLine" id="cb403-7" title="7">                <span class="dt">data =</span> RT)</a>
<a class="sourceLine" id="cb403-8" title="8"><span class="co">#summary(mnl.exp)</span></a></code></pre></div>
<p>The models are summarized next:</p>
<div class="sourceCode" id="cb404"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb404-1" title="1">mnl.cov.summary &lt;-<span class="st"> </span><span class="kw">rownames_to_column</span>(<span class="kw">data.frame</span>(<span class="kw">summary</span>(mnl.cov)<span class="op">$</span>CoefTable), <span class="st">&quot;Variable&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb404-2" title="2"><span class="st">  </span><span class="kw">transmute</span>(Variable, Estimate, <span class="dt">pval =</span> <span class="st">`</span><span class="dt">Pr...z..</span><span class="st">`</span>)</a>
<a class="sourceLine" id="cb404-3" title="3"></a>
<a class="sourceLine" id="cb404-4" title="4">mnl.exp.summary &lt;-<span class="st"> </span><span class="kw">rownames_to_column</span>(<span class="kw">data.frame</span>(<span class="kw">summary</span>(mnl.exp)<span class="op">$</span>CoefTable), <span class="st">&quot;Variable&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb404-5" title="5"><span class="st">  </span><span class="kw">transmute</span>(Variable, Estimate, <span class="dt">pval =</span> <span class="st">`</span><span class="dt">Pr...z..</span><span class="st">`</span>)</a>
<a class="sourceLine" id="cb404-6" title="6"></a>
<a class="sourceLine" id="cb404-7" title="7"></a>
<a class="sourceLine" id="cb404-8" title="8"></a>
<a class="sourceLine" id="cb404-9" title="9">df &lt;-<span class="st"> </span><span class="kw">full_join</span>(mnl.cov.summary, mnl.exp.summary, <span class="dt">by =</span> <span class="st">&quot;Variable&quot;</span>)</a>
<a class="sourceLine" id="cb404-10" title="10"></a>
<a class="sourceLine" id="cb404-11" title="11"><span class="kw">kable</span>(df, </a>
<a class="sourceLine" id="cb404-12" title="12">      <span class="st">&quot;html&quot;</span>,</a>
<a class="sourceLine" id="cb404-13" title="13">      <span class="dt">digits =</span> <span class="dv">4</span>,</a>
<a class="sourceLine" id="cb404-14" title="14">      <span class="dt">col.names =</span> <span class="kw">c</span>(<span class="st">&quot;Variable&quot;</span>,</a>
<a class="sourceLine" id="cb404-15" title="15">                    <span class="st">&quot;Estimate&quot;</span>,</a>
<a class="sourceLine" id="cb404-16" title="16">                    <span class="st">&quot;p-value&quot;</span>,</a>
<a class="sourceLine" id="cb404-17" title="17">                    <span class="st">&quot;Estimate&quot;</span>,</a>
<a class="sourceLine" id="cb404-18" title="18">                    <span class="st">&quot;p-value&quot;</span>),</a>
<a class="sourceLine" id="cb404-19" title="19">      <span class="dt">caption =</span> <span class="st">&quot;Models: multinomial logit with covariates (MNL-COV) and multinomial logit with expanded coefficients (MNL-EXP)&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb404-20" title="20"><span class="st">  </span><span class="kw">kable_styling</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb404-21" title="21"><span class="st">  </span><span class="kw">add_header_above</span>(<span class="kw">c</span>(<span class="st">&quot; &quot;</span> =<span class="st"> </span><span class="dv">1</span>, <span class="st">&quot;MNL-COV&quot;</span> =<span class="st"> </span><span class="dv">2</span>, <span class="st">&quot;MNL-EXP&quot;</span> =<span class="st"> </span><span class="dv">2</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb404-22" title="22"><span class="st">  </span><span class="kw">footnote</span>(<span class="dt">general =</span> <span class="kw">c</span>(<span class="kw">paste0</span>(<span class="st">&quot;Log-Likelihood: MNL-COV = &quot;</span>, <span class="kw">round</span>(mnl.cov<span class="op">$</span>logLik[<span class="dv">1</span>], <span class="dt">digits =</span> <span class="dv">3</span>),</a>
<a class="sourceLine" id="cb404-23" title="23">                            <span class="st">&quot;; MNL-EXP = &quot;</span>, <span class="kw">round</span>(mnl.exp<span class="op">$</span>logLik[<span class="dv">1</span>], <span class="dt">digits =</span> <span class="dv">3</span>))))</a></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-223">Table 11.2: </span>Models: multinomial logit with covariates (MNL-COV) and multinomial logit with expanded coefficients (MNL-EXP)
</caption>
<thead>
<tr>
<th style="border-bottom:hidden" colspan="1">
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
MNL-COV
</div>
</th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
MNL-EXP
</div>
</th>
</tr>
<tr>
<th style="text-align:left;">
Variable
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
p-value
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
p-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
cost
</td>
<td style="text-align:right;">
-0.0117
</td>
<td style="text-align:right;">
0.0000
</td>
<td style="text-align:right;">
-0.0157
</td>
<td style="text-align:right;">
0.0000
</td>
</tr>
<tr>
<td style="text-align:left;">
risk
</td>
<td style="text-align:right;">
-0.1662
</td>
<td style="text-align:right;">
0.0193
</td>
<td style="text-align:right;">
-0.1429
</td>
<td style="text-align:right;">
0.0249
</td>
</tr>
<tr>
<td style="text-align:left;">
dwage:WaterTaxi
</td>
<td style="text-align:right;">
0.0592
</td>
<td style="text-align:right;">
0.3608
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
dwage:Ferry
</td>
<td style="text-align:right;">
0.0597
</td>
<td style="text-align:right;">
0.3473
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
dwage:Hovercraft
</td>
<td style="text-align:right;">
0.0445
</td>
<td style="text-align:right;">
0.4846
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
cost:dwage
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
0.0001
</td>
<td style="text-align:right;">
0.0006
</td>
</tr>
<tr>
<td style="text-align:left;">
risk:dwage
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
-0.0042
</td>
<td style="text-align:right;">
0.0245
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<span style="font-style: italic;">Note: </span>
</td>
</tr>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<sup></sup> Log-Likelihood: MNL-COV = -323.807; MNL-EXP = -329.728
</td>
</tr>
</tfoot>
</table>
<p>The <span class="math inline">\(AIC\)</span> of MNL-COV is:</p>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb405-1" title="1"><span class="kw">as.numeric</span>(<span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">length</span>(<span class="kw">coef</span>(mnl.cov)) <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>mnl.cov<span class="op">$</span>logLik)</a></code></pre></div>
<pre><code>## [1] 657.6149</code></pre>
<p>and the <span class="math inline">\(AIC\)</span> of MNL-EXP is:</p>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb407-1" title="1"><span class="kw">as.numeric</span>(<span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">length</span>(<span class="kw">coef</span>(mnl.exp)) <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>mnl.exp<span class="op">$</span>logLik)</a></code></pre></div>
<pre><code>## [1] 667.4561</code></pre>
<p>The minimum <span class="math inline">\(AIC\)</span> is still for latent class model LC2. If we calculate the relative likelihood with respect to the best performing multinomial logit model:</p>
<div class="sourceCode" id="cb409"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb409-1" title="1"><span class="kw">as.numeric</span>(<span class="kw">exp</span>(((<span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">length</span>(<span class="kw">coef</span>(lc2)) <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>lc2<span class="op">$</span>logLik<span class="op">$</span>maximum) <span class="op">-</span><span class="st"> </span>(<span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">length</span>(<span class="kw">coef</span>(mnl.cov)) <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>mnl.cov<span class="op">$</span>logLik))<span class="op">/</span><span class="dv">2</span>))</a></code></pre></div>
<pre><code>## [1] 1.983059e-06</code></pre>
<p>Clearly, latent class model LC2 is still the best candidate for fit.</p>
</div>
<div id="adding-variables-to-the-latent-class-selection-model-1" class="section level2">
<h2><span class="header-section-number">11.11</span> Adding variables to the latent class selection model</h2>
<p>The latent class model can accommodate individual level attributes in the class selection model. The model thus becomes:
<span class="math display">\[
p_q = \frac{e^{\gamma&#39;_q x_i}}{\sum_{z=1}^Qe^{\gamma&#39;_z x_i}}
\]</span>
where now <span class="math inline">\(\gamma_q\)</span> is a vector of size <span class="math inline">\(1 \times h\)</span> and <span class="math inline">\(x_1\)</span> is a vector of <span class="math inline">\(h\)</span> individual-level attributes. As before, <span class="math inline">\(\gamma_1 = 0\)</span>.</p>
<p>To estimate a model with variables in the selection model, the fifth part of the formula is used, as shown next (call this model LC2-COV):</p>
<div class="sourceCode" id="cb411"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb411-1" title="1">lc2.cov &lt;-<span class="st"> </span><span class="kw">gmnl</span>(choice <span class="op">~</span><span class="st"> </span>cost <span class="op">+</span><span class="st"> </span>risk <span class="op">|</span><span class="st"> </span><span class="dv">0</span> <span class="op">|</span><span class="st"> </span><span class="dv">0</span> <span class="op">|</span><span class="st"> </span><span class="dv">0</span> <span class="op">|</span><span class="st"> </span>dwage, </a>
<a class="sourceLine" id="cb411-2" title="2">           <span class="dt">data =</span> RT,</a>
<a class="sourceLine" id="cb411-3" title="3">           <span class="dt">model =</span> <span class="st">&#39;lc&#39;</span>, </a>
<a class="sourceLine" id="cb411-4" title="4">           <span class="dt">Q =</span> <span class="dv">2</span>,</a>
<a class="sourceLine" id="cb411-5" title="5">           <span class="dt">panel =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb411-6" title="6">           <span class="dt">method =</span> <span class="st">&quot;nm&quot;</span>,</a>
<a class="sourceLine" id="cb411-7" title="7">           <span class="dt">iterlim =</span> <span class="dv">1200</span>)</a></code></pre></div>
<pre><code>## Estimating LC model</code></pre>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb413-1" title="1"><span class="kw">summary</span>(lc2.cov)</a></code></pre></div>
<pre><code>## 
## Model estimated on: Wed Feb 05 9:59:18 AM 2020 
## 
## Call:
## gmnl(formula = choice ~ cost + risk | 0 | 0 | 0 | dwage, data = RT, 
##     model = &quot;lc&quot;, Q = 2, panel = TRUE, method = &quot;nm&quot;, iterlim = 1200)
## 
## Frequencies of categories:
## 
## Helicopter  WaterTaxi      Ferry Hovercraft 
##   0.003125   0.403125   0.459375   0.134375 
## 
## The estimation took: 0h:0m:1s 
## 
## Coefficients:
##                Estimate Std. Error z-value  Pr(&gt;|z|)    
## class.1.cost -0.1159165  0.0333901 -3.4716 0.0005174 ***
## class.1.risk  0.0861966  0.1056785  0.8156 0.4147008    
## class.2.cost  0.0018230  0.0031749  0.5742 0.5658431    
## class.2.risk -0.6166901  0.0994760 -6.1994 5.668e-10 ***
## (class)2     -0.3362670  0.2237047 -1.5032 0.1327943    
## dwage:class2  0.0317098  0.0080091  3.9592 7.519e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Optimization of log-likelihood by Nelder-Mead maximization
## Log Likelihood: -302.22
## Number of observations: 320
## Number of iterations: 1149
## Exit of MLE: successful convergence</code></pre>
<p>The <span class="math inline">\(AIC\)</span> of this model is:</p>
<div class="sourceCode" id="cb415"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb415-1" title="1"><span class="kw">as.numeric</span>(<span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">length</span>(<span class="kw">coef</span>(lc2.cov)) <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>lc2.cov<span class="op">$</span>logLik<span class="op">$</span>maximum)</a></code></pre></div>
<pre><code>## [1] 616.4306</code></pre>
<p>which improves on the <span class="math inline">\(AIC\)</span> of the LC2 model:</p>
<div class="sourceCode" id="cb417"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb417-1" title="1"><span class="kw">as.numeric</span>(<span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">length</span>(<span class="kw">coef</span>(lc2)) <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>lc2<span class="op">$</span>logLik<span class="op">$</span>maximum)</a></code></pre></div>
<pre><code>## [1] 631.3531</code></pre>
<p>The relative likelihood is now:</p>
<div class="sourceCode" id="cb419"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb419-1" title="1"><span class="kw">as.numeric</span>(<span class="kw">exp</span>(((<span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">length</span>(<span class="kw">coef</span>(lc2.cov)) <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>lc2.cov<span class="op">$</span>logLik<span class="op">$</span>maximum) <span class="op">-</span><span class="st"> </span>(<span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">length</span>(<span class="kw">coef</span>(lc2)) <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>lc2<span class="op">$</span>logLik<span class="op">$</span>maximum))<span class="op">/</span><span class="dv">2</span>))</a></code></pre></div>
<pre><code>## [1] 0.0005749284</code></pre>
<p>Which clearly indicates the improved performance of the model LC2-COV.</p>
<p>The model still points at two classes of decision-makers, cost-averse and risk-averse. However, the probability of membership in those classes now changes as a function of declared wage. The following figure explores the shares of the classes by levels of wage:</p>
<div class="sourceCode" id="cb421"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb421-1" title="1"><span class="co">#Create a dataframe for plotting:</span></a>
<a class="sourceLine" id="cb421-2" title="2">df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">dwage =</span> <span class="kw">seq</span>(<span class="kw">min</span>(RT<span class="op">$</span>dwage), <span class="dt">to =</span> <span class="kw">max</span>(RT<span class="op">$</span>dwage), <span class="dt">by =</span> (<span class="kw">max</span>(RT<span class="op">$</span>dwage) <span class="op">-</span><span class="st"> </span><span class="kw">min</span>(RT<span class="op">$</span>dwage))<span class="op">/</span><span class="dv">100</span>))</a>
<a class="sourceLine" id="cb421-3" title="3"></a>
<a class="sourceLine" id="cb421-4" title="4"><span class="co"># Use the class selection model to calculate the membership probabilities</span></a>
<a class="sourceLine" id="cb421-5" title="5">df &lt;-<span class="st"> </span>df <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">p_1 =</span> <span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">exp</span>(<span class="kw">coef</span>(lc2.cov)[<span class="st">&quot;(class)2&quot;</span>] <span class="op">+</span><span class="st"> </span><span class="kw">coef</span>(lc2.cov)[<span class="st">&quot;dwage:class2&quot;</span>] <span class="op">*</span><span class="st"> </span>dwage)<span class="op">/</span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span><span class="kw">exp</span>(<span class="kw">coef</span>(lc2.cov)[<span class="st">&quot;(class)2&quot;</span>] <span class="op">+</span><span class="st"> </span><span class="kw">coef</span>(lc2.cov)[<span class="st">&quot;dwage:class2&quot;</span>] <span class="op">*</span><span class="st"> </span>dwage)),</a>
<a class="sourceLine" id="cb421-6" title="6">                    <span class="dt">p_2 =</span> <span class="kw">exp</span>(<span class="kw">coef</span>(lc2.cov)[<span class="st">&quot;(class)2&quot;</span>] <span class="op">+</span><span class="st"> </span><span class="kw">coef</span>(lc2.cov)[<span class="st">&quot;dwage:class2&quot;</span>] <span class="op">*</span><span class="st"> </span>dwage)<span class="op">/</span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span><span class="kw">exp</span>(<span class="kw">coef</span>(lc2.cov)[<span class="st">&quot;(class)2&quot;</span>] <span class="op">+</span><span class="st"> </span><span class="kw">coef</span>(lc2.cov)[<span class="st">&quot;dwage:class2&quot;</span>] <span class="op">*</span><span class="st"> </span>dwage)))</a>
<a class="sourceLine" id="cb421-7" title="7"></a>
<a class="sourceLine" id="cb421-8" title="8"><span class="co"># Plot</span></a>
<a class="sourceLine" id="cb421-9" title="9"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> dwage)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb421-10" title="10"><span class="st">  </span><span class="kw">geom_ribbon</span>(<span class="kw">aes</span>(<span class="dt">ymin =</span> <span class="dv">0</span>, <span class="dt">ymax =</span> <span class="dv">1</span>), <span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb421-11" title="11"><span class="st">  </span><span class="kw">geom_ribbon</span>(<span class="kw">aes</span>(<span class="dt">ymin =</span> <span class="dv">0</span>, <span class="dt">ymax =</span> p_<span class="dv">1</span>), <span class="dt">fill =</span> <span class="st">&quot;orange&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb421-12" title="12"><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Probability of class membership&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb421-13" title="13"><span class="st">  </span><span class="kw">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="dt">x =</span> <span class="dv">25</span>, <span class="dt">y =</span> <span class="fl">0.22</span>, <span class="dt">label =</span> <span class="st">&quot;Class 1&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb421-14" title="14"><span class="st">  </span><span class="kw">annotate</span>(<span class="st">&quot;text&quot;</span>, <span class="dt">x =</span> <span class="dv">250</span>, <span class="dt">y =</span> <span class="fl">0.75</span>, <span class="dt">label =</span> <span class="st">&quot;Class 2&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-231-1.png" width="672" /></p>
<p>The plot indicates that individuals with lower declared wages have a higher probability of being in class 1, which is risk-averse. This tends to decline quite rapidly as declared wage increases, and overall most members of the population tend to be risk-averse.</p>
</div>
<div id="exercise-9" class="section level2">
<h2><span class="header-section-number">11.12</span> Exercise</h2>
<p>Load the following dataset (used in this chapter):</p>
<div class="sourceCode" id="cb422"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb422-1" title="1"><span class="kw">data</span>(<span class="st">&quot;RiskyTransport&quot;</span>, <span class="dt">package =</span> <span class="st">&quot;mlogit&quot;</span>)</a></code></pre></div>
<p>Select individuals who had access to all four modes of transportation:</p>
<div class="sourceCode" id="cb423"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb423-1" title="1">all_available &lt;-<span class="st"> </span>RiskyTransport <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(chid) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summarise</span>(<span class="dt">no_rows =</span> <span class="kw">length</span>(chid)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(no_rows <span class="op">==</span><span class="st"> </span><span class="dv">4</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(chid)</a>
<a class="sourceLine" id="cb423-2" title="2">RT &lt;-<span class="st"> </span><span class="kw">inner_join</span>(RiskyTransport, all_available, <span class="dt">by =</span> <span class="st">&quot;chid&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">drop_na</span>()</a></code></pre></div>
<ol style="list-style-type: decimal">
<li>Estimate a mixed logit model using the Risky Transportation dataset used in this chapter. Compare the mixed logit model and the latent class logit models. Which one would you select? Discuss.</li>
</ol>
<p>Load the following dataset from the <code>AER</code> package:</p>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb424-1" title="1"><span class="kw">data</span>(<span class="st">&quot;TravelMode&quot;</span>, <span class="dt">package =</span> <span class="st">&quot;AER&quot;</span>)</a></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Estimate a latent class logit model. Justify your modelling decisions, including the number of classes to use and the use of covariates.</li>
</ol>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-Leon2017risky">
<p>León, Gianmarco, and Edward Miguel. 2017. “Risky Transportation Choices and the Value of a Statistical Life.” <em>American Economic Journal: Applied Economics</em> 9 (1): 202–28.</p>
</div>
<div id="ref-Louviere2000stated">
<p>Louviere, Jordan J, David A Hensher, and Joffre D Swait. 2000. <em>Stated Choice Methods: Analysis and Applications</em>. Cambridge University Press.</p>
</div>
<div id="ref-Roeder1999modeling">
<p>Roeder, Kathryn, Kevin G Lynch, and Daniel S Nagin. 1999. “Modeling Uncertainty in Latent Class Membership: A Case Study in Criminology.” <em>Journal of the American Statistical Association</em> 94 (447): 766–76.</p>
</div>
<div id="ref-Shen2009latent">
<p>Shen, Junyi. 2009. “Latent Class Model or Mixed Logit Model? A Comparison by Transport Mode Choice Data.” <em>Applied Economics</em> 41 (22): 2915–24.</p>
</div>
<div id="ref-Train2009discrete">
<p>Train, K. 2009. <em>Discrete Choice Methods with Simulation</em>. Book. 2nd Edition. Cambridge: Cambridge University Press.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chapter-9.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/10-Ordinal-Ranked.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
