<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Chapter 3 Data and stuff | An Introduction to Discrete Choice Analysis</title>
  <meta name="description" content="These notes were created by Antonio Paez as a resource for teaching a graduate discrete choice analysis course (GEOG 738) at McMaster University.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Chapter 3 Data and stuff | An Introduction to Discrete Choice Analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="These notes were created by Antonio Paez as a resource for teaching a graduate discrete choice analysis course (GEOG 738) at McMaster University." />
  <meta name="github-repo" content="paezha/Discrete-Choice-Analysis-with-R" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Data and stuff | An Introduction to Discrete Choice Analysis" />
  
  <meta name="twitter:description" content="These notes were created by Antonio Paez as a resource for teaching a graduate discrete choice analysis course (GEOG 738) at McMaster University." />
  

<meta name="author" content="Antonio Paez">


<meta name="date" content="2019-02-04">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="preliminaries-installing-r-and-rstudio.html">
<link rel="next" href="chapter-2.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#choices-choices-choices"><i class="fa fa-check"></i>Choices, choices, choices</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="price-mechanisms.html"><a href="price-mechanisms.html"><i class="fa fa-check"></i><b>1</b> Price Mechanisms</a><ul>
<li class="chapter" data-level="" data-path="price-mechanisms.html"><a href="price-mechanisms.html#plan"><i class="fa fa-check"></i>Plan</a></li>
<li class="chapter" data-level="" data-path="price-mechanisms.html"><a href="price-mechanisms.html#audience"><i class="fa fa-check"></i>Audience</a></li>
<li class="chapter" data-level="" data-path="price-mechanisms.html"><a href="price-mechanisms.html#requisites"><i class="fa fa-check"></i>Requisites</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html"><i class="fa fa-check"></i><b>2</b> Preliminaries: Installing R and RStudio</a><ul>
<li class="chapter" data-level="2.1" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html#learning-objectives"><i class="fa fa-check"></i><b>2.2</b> Learning Objectives</a></li>
<li class="chapter" data-level="2.3" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html#r-the-open-statistical-computing-project"><i class="fa fa-check"></i><b>2.3</b> R: The Open Statistical Computing Project</a><ul>
<li class="chapter" data-level="2.3.1" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html#what-is-r"><i class="fa fa-check"></i><b>2.3.1</b> What is R?</a></li>
<li class="chapter" data-level="2.3.2" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html#the-rstudio-ide"><i class="fa fa-check"></i><b>2.3.2</b> The RStudio IDE</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="preliminaries-installing-r-and-rstudio.html"><a href="preliminaries-installing-r-and-rstudio.html#packages-in-r"><i class="fa fa-check"></i><b>2.4</b> Packages in R</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="chapter-1.html"><a href="chapter-1.html"><i class="fa fa-check"></i><b>3</b> Data and stuff</a><ul>
<li class="chapter" data-level="3.1" data-path="chapter-1.html"><a href="chapter-1.html#what-are-models"><i class="fa fa-check"></i><b>3.1</b> What are models?</a></li>
<li class="chapter" data-level="3.2" data-path="chapter-1.html"><a href="chapter-1.html#how-to-use-this-note"><i class="fa fa-check"></i><b>3.2</b> How to use this note</a></li>
<li class="chapter" data-level="3.3" data-path="chapter-1.html"><a href="chapter-1.html#learning-objectives-1"><i class="fa fa-check"></i><b>3.3</b> Learning objectives</a></li>
<li class="chapter" data-level="3.4" data-path="chapter-1.html"><a href="chapter-1.html#suggested-readings"><i class="fa fa-check"></i><b>3.4</b> Suggested readings</a></li>
<li class="chapter" data-level="3.5" data-path="chapter-1.html"><a href="chapter-1.html#ways-of-measuring-stuff"><i class="fa fa-check"></i><b>3.5</b> Ways of measuring stuff</a><ul>
<li class="chapter" data-level="3.5.1" data-path="chapter-1.html"><a href="chapter-1.html#categorical"><i class="fa fa-check"></i><b>3.5.1</b> Categorical</a></li>
<li class="chapter" data-level="3.5.2" data-path="chapter-1.html"><a href="chapter-1.html#quantitative"><i class="fa fa-check"></i><b>3.5.2</b> Quantitative</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="chapter-1.html"><a href="chapter-1.html#importing-data"><i class="fa fa-check"></i><b>3.6</b> Importing data</a></li>
<li class="chapter" data-level="3.7" data-path="chapter-1.html"><a href="chapter-1.html#data-classes-in-r"><i class="fa fa-check"></i><b>3.7</b> Data Classes in R</a></li>
<li class="chapter" data-level="3.8" data-path="chapter-1.html"><a href="chapter-1.html#more-on-indexing-and-data-manipulation"><i class="fa fa-check"></i><b>3.8</b> More on indexing and data manipulation</a></li>
<li class="chapter" data-level="3.9" data-path="chapter-1.html"><a href="chapter-1.html#visualization"><i class="fa fa-check"></i><b>3.9</b> Visualization</a></li>
<li class="chapter" data-level="3.10" data-path="chapter-1.html"><a href="chapter-1.html#exercise"><i class="fa fa-check"></i><b>3.10</b> Exercise</a><ul>
<li class="chapter" data-level="3.10.1" data-path="chapter-1.html"><a href="chapter-1.html#questions"><i class="fa fa-check"></i><b>3.10.1</b> Questions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="chapter-2.html"><a href="chapter-2.html"><i class="fa fa-check"></i><b>4</b> Fundamental concepts</a><ul>
<li class="chapter" data-level="4.1" data-path="chapter-2.html"><a href="chapter-2.html#why-modelling-choices"><i class="fa fa-check"></i><b>4.1</b> Why modelling choices?</a></li>
<li class="chapter" data-level="4.2" data-path="chapter-2.html"><a href="chapter-2.html#how-to-use-this-note-1"><i class="fa fa-check"></i><b>4.2</b> How to use this note</a></li>
<li class="chapter" data-level="4.3" data-path="chapter-2.html"><a href="chapter-2.html#learning-objectives-2"><i class="fa fa-check"></i><b>4.3</b> Learning objectives</a></li>
<li class="chapter" data-level="4.4" data-path="chapter-2.html"><a href="chapter-2.html#suggested-readings-1"><i class="fa fa-check"></i><b>4.4</b> Suggested readings</a></li>
<li class="chapter" data-level="4.5" data-path="chapter-2.html"><a href="chapter-2.html#preliminaries"><i class="fa fa-check"></i><b>4.5</b> Preliminaries</a></li>
<li class="chapter" data-level="4.6" data-path="chapter-2.html"><a href="chapter-2.html#utility-maximization"><i class="fa fa-check"></i><b>4.6</b> Utility maximization</a></li>
<li class="chapter" data-level="4.7" data-path="chapter-2.html"><a href="chapter-2.html#what-about-those-random-terms"><i class="fa fa-check"></i><b>4.7</b> What about those random terms?</a></li>
<li class="chapter" data-level="4.8" data-path="chapter-2.html"><a href="chapter-2.html#probability-distribution-functions-pdfs"><i class="fa fa-check"></i><b>4.8</b> Probability distribution functions (PDFs)</a></li>
<li class="chapter" data-level="4.9" data-path="chapter-2.html"><a href="chapter-2.html#a-simple-random-utility-discrete-choice-model"><i class="fa fa-check"></i><b>4.9</b> A simple random utility discrete choice model</a></li>
<li class="chapter" data-level="4.10" data-path="chapter-2.html"><a href="chapter-2.html#other-choice-mechanisms"><i class="fa fa-check"></i><b>4.10</b> Other choice mechanisms</a></li>
<li class="chapter" data-level="4.11" data-path="chapter-2.html"><a href="chapter-2.html#exercise-1"><i class="fa fa-check"></i><b>4.11</b> Exercise</a><ul>
<li class="chapter" data-level="4.11.1" data-path="chapter-2.html"><a href="chapter-2.html#questions-1"><i class="fa fa-check"></i><b>4.11.1</b> Questions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="chapter-3.html"><a href="chapter-3.html"><i class="fa fa-check"></i><b>5</b> Logit</a><ul>
<li class="chapter" data-level="5.1" data-path="chapter-3.html"><a href="chapter-3.html#modelling-choices"><i class="fa fa-check"></i><b>5.1</b> Modelling choices</a></li>
<li class="chapter" data-level="5.2" data-path="chapter-3.html"><a href="chapter-3.html#how-to-use-this-note-2"><i class="fa fa-check"></i><b>5.2</b> How to use this note</a></li>
<li class="chapter" data-level="5.3" data-path="chapter-3.html"><a href="chapter-3.html#learning-objectives-3"><i class="fa fa-check"></i><b>5.3</b> Learning objectives</a></li>
<li class="chapter" data-level="5.4" data-path="chapter-3.html"><a href="chapter-3.html#suggested-readings-2"><i class="fa fa-check"></i><b>5.4</b> Suggested readings</a></li>
<li class="chapter" data-level="5.5" data-path="chapter-3.html"><a href="chapter-3.html#preliminaries-1"><i class="fa fa-check"></i><b>5.5</b> Preliminaries</a></li>
<li class="chapter" data-level="5.6" data-path="chapter-3.html"><a href="chapter-3.html#once-again-those-random-terms"><i class="fa fa-check"></i><b>5.6</b> Once again those random terms</a></li>
<li class="chapter" data-level="5.7" data-path="chapter-3.html"><a href="chapter-3.html#now-about-those-parameters-mu-and-sigma"><i class="fa fa-check"></i><b>5.7</b> Now, about those parameters <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>…</a></li>
<li class="chapter" data-level="5.8" data-path="chapter-3.html"><a href="chapter-3.html#multinomial-logit"><i class="fa fa-check"></i><b>5.8</b> Multinomial logit</a></li>
<li class="chapter" data-level="5.9" data-path="chapter-3.html"><a href="chapter-3.html#properties-of-the-logit-model"><i class="fa fa-check"></i><b>5.9</b> Properties of the logit model</a></li>
<li class="chapter" data-level="5.10" data-path="chapter-3.html"><a href="chapter-3.html#revisiting-the-systematic-utilities"><i class="fa fa-check"></i><b>5.10</b> Revisiting the systematic utilities</a></li>
<li class="chapter" data-level="5.11" data-path="chapter-3.html"><a href="chapter-3.html#exercise-2"><i class="fa fa-check"></i><b>5.11</b> Exercise</a><ul>
<li class="chapter" data-level="5.11.1" data-path="chapter-3.html"><a href="chapter-3.html#questions-2"><i class="fa fa-check"></i><b>5.11.1</b> Questions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">An Introduction to Discrete Choice Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chapter-1" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Data and stuff</h1>
<blockquote>
<p>“Essentially, all models are wrong, but some are useful.”</p>
<p>— George E.P. Box</p>
</blockquote>
<blockquote>
<p>“You can have data without information, but you cannot have information without data.”</p>
<p>— Daniel Keys Moran</p>
</blockquote>
<div id="what-are-models" class="section level2">
<h2><span class="header-section-number">3.1</span> What are models?</h2>
<p>Model building requires three things:</p>
<ol style="list-style-type: decimal">
<li><p>Raw materials.</p></li>
<li><p>Tools.</p></li>
<li><p>Technical expertise (hopefully!).</p></li>
</ol>
<p>This is true whether the model is physical (for instance a sculpture), conceptual (a mental map), or statistical/mathematical (the gravity model or a regression model).</p>
<p>In the case of a sculpture, the raw materials can be marble, wood, or clay; the tools chisels, mallet, and spatula; and the technique the mastery of the sculptor when working with the tools and the materials. Anyone can try sculpture, and most people can create sculptures. These kind of models are evaluated by their aesthetic value, not necessarily their usefulness. But if the scultpure is poorly balanced and falls and breaks, then its value is limited by its structural integrity - the skill of the sculptor matters even if only in this sense.</p>
<p>In the case of a mental map, the raw materials are ideas, the tools are a drawing surface and tools for writing, or maybe an app, and the technical expertise is the ability of the modeler to organize ideas in a useful way. There are useful conceptual models, and conceptual models that are anything but. Figure <a href="chapter-1.html#fig:fig-conceptual-models">3.1</a> shows two example of conceptual models.</p>
<div class="figure"><span id="fig:fig-conceptual-models"></span>
<img src="01-Figure-1.jpg" alt="\label{fig:fig-conceptual-models}Two Examples of Conceptual Models" width="640" />
<p class="caption">
Figure 3.1: Two Examples of Conceptual Models
</p>
</div>
<p>In the case of mathematical/statistical models, the raw materials are data; the tools are descriptive statistics and statistical plots, and various forms of regression analysis; and the technical expertise is the ability of the modeler to select tools that are appropriate to the data, and to convince the data to “speak”: in other words, to extract information from the data. As Moran said in the aphorism quoted at the top of this section: you can have data without information, but no information without data. Technical mastery is the degree to which a modeller can obtain information from data that is useful, accurate, and precise, to the extent that the raw materials permit.</p>
<p>Before moving on to the technical skills required for modeling, it is important to understand the raw materials and the tools. The objective of this note is to introduce some important concerning data and data manipulation, and some useful tools.</p>
</div>
<div id="how-to-use-this-note" class="section level2">
<h2><span class="header-section-number">3.2</span> How to use this note</h2>
<p>The source for the document you are reading is an R Notebook. Notebooks are a form “literate programming”, a style of document that uses code to illustrate a discussion, as opposed to the traditional programming style that uses natural language to discuss/document the code. It flips around the usual technical writing approach to make it more intuitive and accessible.</p>
<p>Throughout the notes, you will find examples of code in segments of text called <em>chunks</em>. This is an example of a chunk:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(<span class="st">&quot;Hello, Discrete Choice Analysis!&quot;</span>)</code></pre></div>
<pre><code>## [1] &quot;Hello, Discrete Choice Analysis!&quot;</code></pre>
<p>If you are working with the Notebook version of the document, you can run the code by clicking the ‘play’ icon on the top right corner of the chunk. If you are reading the web-book version of the document, you will often see that the code has already been executed. You can still try it by copying and pasting into your R or RStudio console. Whichever way you are working, you might want to give it a try now! You will see that the chunk of code above instructed R (and trough R the computer) to <code>print</code> (or display on the screen) some text.</p>
</div>
<div id="learning-objectives-1" class="section level2">
<h2><span class="header-section-number">3.3</span> Learning objectives</h2>
<p>In this practice, you will learn about:</p>
<ol style="list-style-type: decimal">
<li>Different ways to measure stuff.</li>
<li>Basic operations in R.</li>
<li>Data classes, data types, and data transformations.</li>
<li>The use of packages in R.</li>
<li>Basic visualization.</li>
</ol>
</div>
<div id="suggested-readings" class="section level2">
<h2><span class="header-section-number">3.4</span> Suggested readings</h2>
<ul>
<li>Grolemund, G., Wickham, H. <span class="citation">(<a href="#ref-wickham2016r">2016</a>)</span> R for Data Science, <strong>Chapters 3-5</strong>, O’Reilly Media.</li>
</ul>
</div>
<div id="ways-of-measuring-stuff" class="section level2">
<h2><span class="header-section-number">3.5</span> Ways of measuring stuff</h2>
<p>Previously we said that data are the raw material for modeling, but we did not say precisely what we meant by ‘data’. You probably already have a working understanding of what ‘data’ means, but nonetheless lets begin with a definition. According to Mirriam-Webster, <a href="https://www.merriam-webster.com/dictionary/data">data</a> are:</p>
<blockquote>
<p>factual information (such as measurements or statistics) used as a basis for reasoning, discussion, or calculation</p>
</blockquote>
<p>As an aside, it is interesting to note that Tukey’s classic Exploratory Data Analysis <span class="citation">(Tuckey <a href="#ref-Tuckey1977">1977</a>)</span> does not define ‘data’ in the glossary!</p>
<p>Measurement theory is a branch of mathematics concerned with observing the <em>facts</em> about something. It is important to note that measurements are not the same as the thing being measured; however, we would like the measurements to be a reasonably close approximation of the thing being measured - otherwise the measurements might be pretty useless, an inadequate way to learn anything valuable from the thing we are measuring.</p>
<p>One fundamental contribution of the scientific method has been to produce standardized ways of measuring things. How would you measure the following things?</p>
<ul>
<li>The temperature at which water freezes.</li>
<li>The tempreature at which nitrogen freezes.</li>
<li>The length of a trip.</li>
<li>Blood donations.</li>
<li>Different brands of peanut butter.</li>
<li>The value of two bedroom apartment.</li>
<li>Someone’s opinion regarding taxes.</li>
</ul>
<p>Generally, there are multiple ways of measuring something, but not all of them are necessarily appropriate, partly because the scales of measurement may result in some loss of information. The interpretation of a measurement, as well, depends on what the scale is.</p>
<p>Two broad scales of measurement are as follows:</p>
<div id="categorical" class="section level3">
<h3><span class="header-section-number">3.5.1</span> Categorical</h3>
<p>Categorical measurements assign a label or category to the thing being measured. For example, a way to measure different brands of peanut butter could be to measure their sugar content, their fat content, their consistency, and so on, and in this way describe what makes each brand unique. A different way to do this would be to label one brand “Spooky” and another “Peter’s”. This has the effect of reducing a lot of information to a much simpler category. Is this loss of information inappropriate? Well, it really depends on what is the intended use of data! Categorical measurements are interesting because they may tell us something about the power of brands!</p>
<p>Within the class of categorical variables there are two distinct scales of measurement:</p>
<ul>
<li><p>Nominal scale. When the categories do not follow a natural order. For example, there is no reason to say that “Spooky” brand precedes “Peter’s” or vice versa. Similarly, when measuring modes of travel “walking” is not intrinsically higher or lower or better or worse than “cycling” or “riding bus”.</p></li>
<li><p>Ordinal scale. When the categories follow a natural or logical sequence. A common way of measuring opinions is by means of the <a href="https://en.wikipedia.org/wiki/Likert_scale">Likert scale</a>, which classifies responses for instance as “strongly disagree”, “disagree”, “neutral”, “agree”, “strongly agree”. In this case, it is sensible to order the responses, since “strongly agree” is probably closer to “agree” than to “strongly disagree”. Responses of this type are often represented by numbers, say, from 1 to 5. It is a mistake to treat the measurements as numbers instead of lables. When treated as numbers there is a temptation to thing of the difference between 4 and 5 and the difference between 3 and 4 as being equivalent, when in fact the strength of disagreement could be stronger than the strength of agreement. In other words, the interval between “strongly disagree” and “disagree” may not be the same as “agree” and “strongly agree”. With ordinal scales we do not know that, all that we know is that they measure a different opinion.</p></li>
</ul>
<p>Sometimes, different measurement scales might represent different behavioral mechanisms, as Bhat and Pulugurta discuss in their comparison of categorical and ordinal measurements for vehicle ownership <span class="citation">(Bhat and Pulugurta <a href="#ref-Bhat1998comparison">1998</a>)</span>.</p>
</div>
<div id="quantitative" class="section level3">
<h3><span class="header-section-number">3.5.2</span> Quantitative</h3>
<p>Quantitative measurements assign a number to an attribute, and the number quantifies the presence of the attribute. Within this class of variables, there are also two ways of measuring things.</p>
<ul>
<li><p>Interval scale. A quantity can be assigned to an attribute, the values follow an order, and their differences can be computed and remain constant. Temperature is typically measured in interval scale. The difference between <span class="math inline">\(10\,^{\circ}\mathrm{C}\)</span> and <span class="math inline">\(11\,^{\circ}\mathrm{C}\)</span> is the same as the difference between <span class="math inline">\(25\,^{\circ}\mathrm{C}\)</span> and <span class="math inline">\(26\,^{\circ}\mathrm{C}\)</span>. The intervals are meaningful. However, <span class="math inline">\(0\,^{\circ}\mathrm{C}\)</span> does not imply the absence of temperature! Which is why measurements in Celsius and Farenheit do not coincide at zero. The lack of a natural zero for these scales means that the <em>ratios</em> between two values are not meaningful: <span class="math inline">\(4\,^{\circ}\mathrm{C}\)</span> is not twice as hot as <span class="math inline">\(2\,^{\circ}\mathrm{C}\)</span>, and <span class="math inline">\(-12\,^{\circ}\mathrm{C}\)</span> is not four times as cold as <span class="math inline">\(-3\,^{\circ}\mathrm{C}\)</span>.</p></li>
<li><p>Ratio scale. When there is an absolute value of zero to the thing being measured (to indicate absence!), attributes can be measured in a ratio scale. This combines the features of the previous scales of measurement: a number is esentially a label that follows a logical order and with differences that are meaningful. In addition to that, the ratios of variables are meaningful. For example, twenty dollars are twice as valuable as ten, and zero is the absence of value. Weight is a way of measuring mass, and zero is the absence of mass. Two hundred kilograms is twice as much as one hundred kilograms.</p></li>
</ul>
<p>It is important to understand the different scales of measurement to be able to choose the appropriate tools for each. More on this below. But first, lets bring some actual data to play with.</p>
</div>
</div>
<div id="importing-data" class="section level2">
<h2><span class="header-section-number">3.6</span> Importing data</h2>
<p>There are several different ways of importing data in R. For this example, we will use part of a dataset that was analyzed by Whalen et al. <span class="citation">(Whalen, Páez, and Carrasco <a href="#ref-Whalen2013">2013</a>)</span>.</p>
<p>At the very beginning, it is good practice to clear the workspace, to ensure that there are no extraneous items there. The workspace is where objects reside in memory during a session with R. The function for removing variables from the workspace is <code>rm()</code>. Another useful function is `<code>ls</code>, which retrieves a list of things in the workspace. So essentially we are asking R to remove all things in the workspace:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rm</span>(<span class="dt">list =</span> <span class="kw">ls</span>())</code></pre></div>
<p>Once that the workspace is empty, we can proceed to load a few packages that are useful. Packages are the basic units of reproducible code in the R multiverse. Packages allow a developer to create a self-contained unit of code that often is meant to achieve some task. For instance, there are packages in R that specialize in statistical techniques, such as <a href="https://cran.r-project.org/web/packages/cluster/index.html">cluster analysis</a>, <a href="https://cran.r-project.org/web/packages/ggplot2/index.html">visualization</a>, or <a href="https://cran.r-project.org/web/packages/dplyr/">data manipulation</a>. Some packages can be miscellaneous tools, or contain mostly datasets. Packages are a very convenient way of maintaining code, data, and documentation, and also of sharing all these resources.</p>
<p>Packages can be obtained from different sources (including making them!). One of the reasons why R has become so successful is the relative facility with which packages can be distributed. A package that I use frequently is called <code>tidyverse</code>. The <code>tidyverse</code> is a collection of functions for data manipulation, analysis, and visualization. This package can be downloaded and installed in your personal library of R packages by using the function <code>install.packages</code>, as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">install.packages</span>(<span class="st">&quot;tidyverse&quot;</span>)</code></pre></div>
<p>The function <code>install.packages</code> retrieves packages from the <a href="https://cran.r-project.org/">Comprehensive R Archive Network</a>, or CRAN for short. CRAN is a collection of sites (accessible via the internet) that carry identical materials for distribution for R.</p>
<p>Installing a package is similar to acquiring a book for your library. The book is there, but if you want to use it, you need to bring it to your workspace, so to speak. The function for retrieving a package from the library is naturally enough <code>library()</code>. For the moment, we need the following packages. If you have not done so, take a moment to install them, as illustrated in the previous chunk.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(readr)
<span class="co">#library(caret)</span>
<span class="kw">library</span>(mlogit)</code></pre></div>
<p>Ocassionally there are messages displayed when loading a package. These messages are informative (they ask you to cite them in a certain style) or may give you warnings, for instance that identically named functions exist in several packages.</p>
<p>The function that we need to read the sample dataset is <code>read_csv()</code>, which is part of the <code>tidyverse</code> package. Note that you can name the value (or output) of a function by using <code>&lt;-</code>. In this case, we wish to read an external file, and assign the results to an object called <code>mc_mode_choice</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mc_mode_choice &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;Commute Mac.csv&quot;</span>)</code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_double()
## )</code></pre>
<pre><code>## See spec(...) for full column specifications.</code></pre>
<p>It is possible to quickly examine the contents of the object by means of the function <code>head()</code>, which prints the top few rows of the object, if appropriate. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(mc_mode_choice)</code></pre></div>
<pre><code>## # A tibble: 6 x 39
##   RespondentID choice avcycle avwalk avhsr avcar timecycle timewalk
##          &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1    566872636      3       0      1     1     0      6.21     21.3
## 2    566873140      3       0      1     1     1      3.73     12.8
## 3    566874266      3       0      0     1     1 100000    100000  
## 4    566874842      2       1      1     1     0      5.83     20  
## 5    566881170      2       1      1     1     0      5.83     20  
## 6    566907438      2       0      1     1     0 100000        10  
## # ... with 31 more variables: accesshsr &lt;dbl&gt;, waitingtimehsr &lt;dbl&gt;,
## #   transfer &lt;dbl&gt;, timehsr &lt;dbl&gt;, timecar &lt;dbl&gt;, parking &lt;dbl&gt;,
## #   vehind &lt;dbl&gt;, owncycle &lt;dbl&gt;, gender &lt;dbl&gt;, work &lt;dbl&gt;, visa &lt;dbl&gt;,
## #   age &lt;dbl&gt;, solo &lt;dbl&gt;, shared &lt;dbl&gt;, family &lt;dbl&gt;, child &lt;dbl&gt;,
## #   primary_caregiver &lt;dbl&gt;, LAT &lt;dbl&gt;, LONG &lt;dbl&gt;, DAUID &lt;dbl&gt;,
## #   mhi &lt;dbl&gt;, dwell_den &lt;dbl&gt;, lum &lt;dbl&gt;, st_den &lt;dbl&gt;, inter_den &lt;dbl&gt;,
## #   SF_P_ratio &lt;dbl&gt;, side_den &lt;dbl&gt;, Shelters_SD &lt;dbl&gt;, Shelters_D &lt;dbl&gt;,
## #   Shelters_A &lt;dbl&gt;, Shelters_SA &lt;dbl&gt;</code></pre>
<p>Here we can see that what we just read is a table with several variables: an id, a variable called <code>choice</code>, some variables for time, etc. Hopefully, when reading data there is also a metadata file, a data dictionary or something that defines what the data are. For example, what does it mean for choice to be “3” or “1”? Was time measured in hours, seconds, minutes, or something else? These variables will be described below. Before that, however, we can use a different function to get further insights into the contents of the table by means of the <code>summary()</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(mc_mode_choice)</code></pre></div>
<pre><code>##   RespondentID           choice         avcycle           avwalk      
##  Min.   :566872636   Min.   :1.000   Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:567814188   1st Qu.:2.000   1st Qu.:0.0000   1st Qu.:0.0000  
##  Median :568682048   Median :2.000   Median :0.0000   Median :1.0000  
##  Mean   :570566454   Mean   :2.618   Mean   :0.2747   Mean   :0.6613  
##  3rd Qu.:574925212   3rd Qu.:3.000   3rd Qu.:1.0000   3rd Qu.:1.0000  
##  Max.   :587675235   Max.   :4.000   Max.   :1.0000   Max.   :1.0000  
##      avhsr            avcar          timecycle            timewalk        
##  Min.   :0.0000   Min.   :0.0000   Min.   :     0.29   Min.   :     1.00  
##  1st Qu.:1.0000   1st Qu.:0.0000   1st Qu.:     3.79   1st Qu.:    13.66  
##  Median :1.0000   Median :1.0000   Median :     5.83   Median :    20.00  
##  Mean   :0.9608   Mean   :0.5472   Mean   : 34014.86   Mean   : 37364.73  
##  3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:100000.00   3rd Qu.:100000.00  
##  Max.   :1.0000   Max.   :1.0000   Max.   :100000.00   Max.   :100000.00  
##    accesshsr     waitingtimehsr     transfer         timehsr         
##  Min.   : 0.00   Min.   : 0.00   Min.   :     0   Min.   :     1.00  
##  1st Qu.: 2.48   1st Qu.:10.23   1st Qu.:     0   1st Qu.:     4.75  
##  Median : 6.21   Median :10.23   Median :     0   Median :    10.00  
##  Mean   :11.06   Mean   :10.25   Mean   :  3925   Mean   :  3940.57  
##  3rd Qu.:12.42   3rd Qu.:10.23   3rd Qu.:     1   3rd Qu.:    25.00  
##  Max.   :62.11   Max.   :50.00   Max.   :100000   Max.   :100000.00  
##     timecar          parking            vehind          owncycle     
##  Min.   :     1   Min.   :0.00000   Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:     8   1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:0.0000  
##  Median :    30   Median :0.00000   Median :0.0000   Median :0.0000  
##  Mean   : 45283   Mean   :0.08358   Mean   :0.2565   Mean   :0.4513  
##  3rd Qu.:100000   3rd Qu.:0.00000   3rd Qu.:1.0000   3rd Qu.:1.0000  
##  Max.   :100000   Max.   :1.00000   Max.   :1.0000   Max.   :1.0000  
##      gender            work            visa             age       
##  Min.   :0.0000   Min.   :0.000   Min.   :0.0000   Min.   :17.00  
##  1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:1.0000   1st Qu.:20.00  
##  Median :0.0000   Median :0.000   Median :1.0000   Median :21.00  
##  Mean   :0.4012   Mean   :0.492   Mean   :0.9622   Mean   :22.08  
##  3rd Qu.:1.0000   3rd Qu.:1.000   3rd Qu.:1.0000   3rd Qu.:23.00  
##  Max.   :1.0000   Max.   :1.000   Max.   :1.0000   Max.   :60.00  
##       solo            shared          family           child       
##  Min.   :0.0000   Min.   :0.000   Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:0.0000   1st Qu.:0.0000  
##  Median :0.0000   Median :1.000   Median :0.0000   Median :0.0000  
##  Mean   :0.1272   Mean   :0.625   Mean   :0.2478   Mean   :0.2115  
##  3rd Qu.:0.0000   3rd Qu.:1.000   3rd Qu.:0.0000   3rd Qu.:0.0000  
##  Max.   :1.0000   Max.   :1.000   Max.   :1.0000   Max.   :1.0000  
##  primary_caregiver      LAT             LONG            DAUID         
##  Min.   :     0    Min.   :43.08   Min.   :-80.09   Min.   :35250031  
##  1st Qu.:100000    1st Qu.:43.25   1st Qu.:-79.92   1st Qu.:35250540  
##  Median :100000    Median :43.26   Median :-79.91   Median :35250670  
##  Mean   : 75218    Mean   :43.25   Mean   :-79.90   Mean   :35250612  
##  3rd Qu.:100000    3rd Qu.:43.26   3rd Qu.:-79.90   3rd Qu.:35250677  
##  Max.   :100000    Max.   :43.28   Max.   :-79.64   Max.   :35250970  
##       mhi           dwell_den            lum             st_den     
##  Min.   : 0.000   Min.   :    0.0   Min.   :0.0000   Min.   : 0.00  
##  1st Qu.: 4.577   1st Qu.:  488.7   1st Qu.:0.2808   1st Qu.:10.36  
##  Median : 5.491   Median :  950.0   Median :0.4501   Median :14.29  
##  Mean   : 6.168   Mean   : 1373.0   Mean   :0.4183   Mean   :13.27  
##  3rd Qu.: 7.556   3rd Qu.: 1688.6   3rd Qu.:0.5038   3rd Qu.:16.18  
##  Max.   :14.595   Max.   :45209.9   Max.   :0.9081   Max.   :25.22  
##    inter_den        SF_P_ratio        side_den      Shelters_SD     
##  Min.   :  0.00   Min.   :0.0000   Min.   : 0.00   Min.   :0.00000  
##  1st Qu.: 25.82   1st Qu.:0.2309   1st Qu.:18.19   1st Qu.:0.00000  
##  Median : 41.04   Median :0.2709   Median :22.63   Median :0.00000  
##  Mean   : 52.09   Mean   :0.2625   Mean   :24.18   Mean   :0.04433  
##  3rd Qu.: 73.08   3rd Qu.:0.3134   3rd Qu.:35.70   3rd Qu.:0.00000  
##  Max.   :645.86   Max.   :0.8808   Max.   :59.41   Max.   :1.00000  
##    Shelters_D       Shelters_A      Shelters_SA     
##  Min.   :0.0000   Min.   :0.0000   Min.   :0.00000  
##  1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.00000  
##  Median :0.0000   Median :0.0000   Median :0.00000  
##  Mean   :0.2289   Mean   :0.3576   Mean   :0.02762  
##  3rd Qu.:0.0000   3rd Qu.:1.0000   3rd Qu.:0.00000  
##  Max.   :1.0000   Max.   :1.0000   Max.   :1.00000</code></pre>
<p>This function will print a set of summary statistics for the variables in the table. The statistics are appropriate for the scale of measurement of the variable - that is, the way the variable is coded. Presently, all summary statistics are calculated for quantitative variables. We don’t know if this makes sense, until we know what the variables are supposed to measure.</p>
<p>For example, the variable <code>choice</code> measures the use of one mode of transportation. There are four values in this scale: 1 through 4, with each indicating one of “Cycle”, “Walk”, “Car”, or “HSR” (the local transit agency in Hamilton, ON, Canada, where these data were collected). Check the results of the summary. What does it mean to say that the mean of choice is 2.618? Does this number make sense?</p>
</div>
<div id="data-classes-in-r" class="section level2">
<h2><span class="header-section-number">3.7</span> Data Classes in R</h2>
<p>To understand why 2.618 of mode of transportation is not an appropriate summary measure for the variable <code>mode</code>, we need to know that R can work with different data classes, which include the following:</p>
<ul>
<li>Numerical</li>
<li>Character</li>
<li>Logical</li>
<li>Factor</li>
</ul>
<p>The ability to store information in different forms is important, because is allows R to distinguish what kind of operations are appropriate for a certain variable. Consider the following example (using indexing):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mc_mode_choice<span class="op">$</span>choice[<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span>mc_mode_choice<span class="op">$</span>choice[<span class="dv">4</span>]</code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>Lets unpack what the chunk above did. First, we call our table <code>mc_mode_choice</code>. The string sign <code>$</code> is used to reference columns in the table. Therefore, we asked R to go and look up the column <code>choice</code> in the table <code>mc_mode_choice</code>. Finally, the value between square brackets <code>[]</code> asks R to retrieve a value out of the column, in this example the first value in that column and then the fourth value. This system of referring to elements in tables is called <em>indexing</em>. Most computer languages use it, but the syntax is different. Again: <code>$</code> refers to a column, and <code>[]</code> is used to call values in that column.</p>
<p>As we can see, the difference between the two values retrieved is <span class="math inline">\(1\)</span>. But what is the meaning of “cycle” minus “walk”, for instance?</p>
<p>In reality, the variable <code>choice</code> was measured as a nominal variable: it just corresponds to a label indicating what mode was chosen by a respondent. But R does not know this. Before R can treat it as a nominal variable, the numbers need to be converted to a <em>factor</em>. Factors are the way R stores categorical variables (both nominal and ordinal). To convert the variable <code>choice</code> to a factor, we use the <code>factor()</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mc_mode_choice<span class="op">$</span>choice &lt;-<span class="st"> </span><span class="kw">factor</span>(mc_mode_choice<span class="op">$</span>choice, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Cycle&quot;</span>, <span class="st">&quot;Walk&quot;</span>, <span class="st">&quot;HSR&quot;</span>, <span class="st">&quot;Car&quot;</span>))</code></pre></div>
<p>In the chunk above, we ask R to replace the contents of <code>mc_mode_choice$choice</code> with the value (output) of the function <code>factor</code>. Factor takes the contents of <code>mc_mode_choice$choice</code> and converts to a factor with labels as indicated by the argument <code>labels =</code> (the function <code>c()</code> is used to concatenate several values).</p>
<p>Lets summarize the result, by using the <code>summary()</code> function but only for this variable:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(mc_mode_choice<span class="op">$</span>choice)</code></pre></div>
<pre><code>## Cycle  Walk   HSR   Car 
##    48   711   336   281</code></pre>
<p>Now the summary is appropriate categorical variable, and is a table of frequencies: as seen there, there were 48 respondents who chose “Cycle”, 711 who chose “Walk”, and so on. What if we tried to calculate the difference?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mc_mode_choice<span class="op">$</span>choice[<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span>mc_mode_choice<span class="op">$</span>choice[<span class="dv">4</span>]</code></pre></div>
<pre><code>## Warning in Ops.factor(mc_mode_choice$choice[1], mc_mode_choice$choice[4]):
## &#39;-&#39; not meaningful for factors</code></pre>
<pre><code>## [1] NA</code></pre>
<p>The message indicates that the operation we tried to perform is not meaningful for factors. As long as R knows the appropirate measurement scale for your variables, it will try to steer you away from doing silly things with them.</p>
<p>Other variables included in this table are for time. These variables measure the duration in minutes (actual or imputed) for trips by different modes. For example, <code>timecycle</code> is the duration of a trip by bicycle for the journey reported by the respondent.</p>
<p>Lets summarize this variable again:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(mc_mode_choice<span class="op">$</span>timecycle)</code></pre></div>
<pre><code>##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
##      0.29      3.79      5.83  34014.86 100000.00 100000.00</code></pre>
<p>Notice that the shortest trip by bicycle would be less than a minute long, whereas the maximum is <span class="math inline">\(100,000\)</span> minutes long. Wait, what? That is over <span class="math inline">\(1,600\)</span> hours long. Is that even possible? In fact, no, it is not. The reason for these values is that when the original data were coded, whenever a respondent said that cycling was not a mode that was available to them, the time was coded as a very large and distinctive value. There were no trips taking <span class="math inline">\(100,000\)</span> minutes, this is just a code for “information not available”. One problem with this manner of coding is that R does not know that the information is actually missing, but rather thinks it is a legitimate quantity. As a consequence, the mean is tens of thousands of minutes, despite the fact that half of all trips by bicycle were measured at less than 6 minutes long (see the median).</p>
<p>Next we will see a way to address this. One last thing before doing so: you can check the class an object with the function <code>class</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(mc_mode_choice<span class="op">$</span>choice)</code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(mc_mode_choice<span class="op">$</span>timecycle)</code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
</div>
<div id="more-on-indexing-and-data-manipulation" class="section level2">
<h2><span class="header-section-number">3.8</span> More on indexing and data manipulation</h2>
<p>Indexing is a way of making reference to elements in a data object. There are numerous indexing methods in R that are appropriate for specific objects. Tables such as <code>mc_mode_choice</code> (called <em>data frames</em>) can be indexed in a few different ways. For example the next three chunks are equivalent in that they call the second column (<code>choice</code>) and in that column the second element:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mc_mode_choice[<span class="dv">2</span>, <span class="dv">2</span>]</code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   choice
##   &lt;fct&gt; 
## 1 HSR</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mc_mode_choice<span class="op">$</span>choice[<span class="dv">2</span>]</code></pre></div>
<pre><code>## [1] HSR
## Levels: Cycle Walk HSR Car</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mc_mode_choice[[<span class="st">&quot;choice&quot;</span>]][<span class="dv">2</span>]</code></pre></div>
<pre><code>## [1] HSR
## Levels: Cycle Walk HSR Car</code></pre>
<p>It is also possible to index by ranges of values. For example, the next chunks retrieves rows 2 to 5 from columns 7 and 8:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mc_mode_choice[<span class="dv">2</span><span class="op">:</span><span class="dv">5</span>, <span class="dv">7</span><span class="op">:</span><span class="dv">8</span>]</code></pre></div>
<pre><code>## # A tibble: 4 x 2
##   timecycle timewalk
##       &lt;dbl&gt;    &lt;dbl&gt;
## 1      3.73     12.8
## 2 100000    100000  
## 3      5.83     20  
## 4      5.83     20</code></pre>
<p>Indexing is useful to subset data selectively. For example, we know that travel times coded as <span class="math inline">\(100,000\)</span> are actually cases where the corresponding mode was not available. Lets say that we wanted to summarize travel time by bicycle but without those cases. We can use logical statements when indexing. We could tell R to retrieve only those values that meet a certain condition. In the next chunk, we save the results of this to a new variable:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">time.Cycle.clean &lt;-<span class="st"> </span>mc_mode_choice<span class="op">$</span>timecycle[mc_mode_choice<span class="op">$</span>timecycle <span class="op">!=</span><span class="st"> </span><span class="dv">100000</span>]</code></pre></div>
<p>where <code>!=</code> is R for <em>not</em>. In other words, “find all values <em>not</em> 100000, and retrieve them”.</p>
<p>The result of this is a numeric object:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(time.Cycle.clean)</code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p>If we summarize this object now:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(time.Cycle.clean)</code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.2914  2.9141  4.3711  4.8957  5.8282 45.0000</code></pre>
<p>The summary statistics are much more sensible: the longest trip by bicycle was measured at 45 minutes, and the mean trip at less than 5 minutes.</p>
<p>Indexing is a powerful technique, but can be cumbersome (<code>mc_mode_choice$timecycle[mc_mode_choice$timecycle != 100000]</code>!). The package <code>dplyer</code> (part of the <code>tidyverse</code>) provides a grammar for data manipulation that is more intuitive. We will explore three of its elements here, namely the pipe operator (<code>%&gt;%</code>), <code>select</code>, and <code>filter</code>.</p>
<p>Suppose that we wanted to select two of the time variables, for cycling and walking, and wanted to retrieve only values other than the offending <span class="math inline">\(100,000\)</span>, and save these values in a new object called <code>time.Active.clean</code>. In the grammar of <code>dplyr</code>, this is done as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">time.Active.clean &lt;-<span class="st"> </span>mc_mode_choice <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">select</span>(<span class="kw">c</span>(<span class="st">&quot;timecycle&quot;</span>, <span class="st">&quot;timewalk&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(timecycle <span class="op">!=</span><span class="st"> </span><span class="dv">100000</span> <span class="op">&amp;</span><span class="st"> </span>timewalk <span class="op">!=</span><span class="st"> </span><span class="dv">100000</span>)</code></pre></div>
<p>In natural language this would be something like “take mc_mode_choice and select columns timecycle and timewalk; pass the result to filter and retrieve all rows that meet the conditions timecycle != 100000 AND timewalk != 100000”. The verb <code>select</code> is used to select columns from a data frame, and the verb <code>filter</code> to filter rows.</p>
<p>The alternative, using indexing would look something like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">time.Active.clean.the.hard.way &lt;-<span class="st"> </span>mc_mode_choice[mc_mode_choice<span class="op">$</span>timecycle <span class="op">!=</span><span class="st"> </span><span class="dv">100000</span> <span class="op">&amp;</span><span class="st"> </span>mc_mode_choice<span class="op">$</span>timewalk <span class="op">!=</span><span class="st"> </span><span class="dv">100000</span>, <span class="dv">7</span><span class="op">:</span><span class="dv">8</span>]</code></pre></div>
<p>The expression becomes more convoluted and not as easy to read. It is also easier to make mistakes when writing it.</p>
<p>Compare the summaries of the two data frames, to make sure that they are identical:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(time.Active.clean)</code></pre></div>
<pre><code>##    timecycle          timewalk    
##  Min.   : 0.2914   Min.   : 1.00  
##  1st Qu.: 2.9141   1st Qu.:10.00  
##  Median : 4.3711   Median :15.00  
##  Mean   : 4.5852   Mean   :16.10  
##  3rd Qu.: 5.8282   3rd Qu.:20.00  
##  Max.   :17.4845   Max.   :62.11</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(time.Active.clean.the.hard.way)</code></pre></div>
<pre><code>##    timecycle          timewalk    
##  Min.   : 0.2914   Min.   : 1.00  
##  1st Qu.: 2.9141   1st Qu.:10.00  
##  Median : 4.3711   Median :15.00  
##  Mean   : 4.5852   Mean   :16.10  
##  3rd Qu.: 5.8282   3rd Qu.:20.00  
##  Max.   :17.4845   Max.   :62.11</code></pre>
<p>The grammar of data manipulation in <code>dplyr</code> is a powerful way of working with data in an intuitive way. We will find other aspects of this, but for the time being you are welcome to consult more about <a href="https://dplyr.tidyverse.org/"><code>dplyr</code> here</a></p>
</div>
<div id="visualization" class="section level2">
<h2><span class="header-section-number">3.9</span> Visualization</h2>
<p>The last item in this section is related to visualization. Humans are very much visual creatures, and much can be learned from <em>seeing</em> the data. For example, the data frame, in essence a table, is informative in many ways, but not particularly conducive to observe trends or regularities in the data. The summary statistics are also informative, but partial, and do not convey information to the same effect as a statistical plot.</p>
<p>Take the following list of summary statistics:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(time.Active.clean)</code></pre></div>
<pre><code>##    timecycle          timewalk    
##  Min.   : 0.2914   Min.   : 1.00  
##  1st Qu.: 2.9141   1st Qu.:10.00  
##  Median : 4.3711   Median :15.00  
##  Mean   : 4.5852   Mean   :16.10  
##  3rd Qu.: 5.8282   3rd Qu.:20.00  
##  Max.   :17.4845   Max.   :62.11</code></pre>
<p>Now, compare to the following plot:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> time.Active.clean) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_area</span>(<span class="kw">aes</span>(<span class="dt">x =</span> timecycle), <span class="dt">stat =</span> <span class="st">&quot;bin&quot;</span>, <span class="dt">binwidth =</span> <span class="dv">5</span>, <span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.6</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_area</span>(<span class="kw">aes</span>(<span class="dt">x =</span> timewalk), <span class="dt">stat =</span> <span class="st">&quot;bin&quot;</span>, <span class="dt">binwidth =</span> <span class="dv">5</span>, <span class="dt">fill =</span> <span class="st">&quot;yellow&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;yellow&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.6</span>)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>The plot above was created using a package called <code>ggplot2</code>, also part of <code>tidyverse</code>. This package implements a grammar of graphics, and offers a very flexible way of creating plots in R.</p>
<p><code>ggplot2</code> works by layering a series of objects, beginning with a blank plot, to which we can add things. The command to create a plot is <code>ggplot()</code>. This command accepts different arguments. For instance, we can pass data to it in the form of a data frame. We can also indicate different <em>aesthetic</em> values, that is, the things that we wish to plot. None of this is plotted, though, until we indicate which kind of <em>geom</em> or geometric object we wish to plot. For instance, you can see above that to create the figure we used <code>geom_area</code>. This geom is essentially a smoothed histogram.</p>
<p>Lets break down these instructions.</p>
<p>First we ask <code>ggplot2</code> to create a plot that will use the data frame <code>time.Active.clean</code>. We will name this object <code>p</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">data =</span> time.Active.clean)</code></pre></div>
<p>Notice how <code>ggplot2</code> creates a blank plot, but it has yet to actually render any of the population information in there:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>We have yet to tell <code>ggplot2</code> what the x axis is, what the y axis is, what should be plotted in the x axis, and so on.</p>
<p>We layer elements on a plot by using the <code>+</code> sign. It is only when we tell the package to add some geometric element that it renders something on the plot. In the previous case, we told <code>ggplot2</code> to use the <code>geom_area</code> to create a smoothed histogram. Next, we need to indicate which <code>aes</code> (short for <em>aesthetics</em>) we wish to plot. The aesthetics map aspect of the dataset to the plot. For instance, by saying that the aesthetics include something for x, we tell <code>ggplot2</code> that that something should be mapped to the x axis (in this case one of the time variables in the data frame). The second argument is <code>stat = 'bin'</code>, which indicates that there is a statistical operation that happens, namely the data are binned for smoothing (small bins lead to less smoothing, large bins lead to more smoothing; try it!). After playing around with a few bin values, I selected 5:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p <span class="op">+</span><span class="st"> </span><span class="kw">geom_area</span>(<span class="kw">aes</span>(<span class="dt">x =</span> timecycle), <span class="dt">stat =</span> <span class="st">&quot;bin&quot;</span>, <span class="dt">binwidth =</span> <span class="dv">5</span>)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<p>To improve the appearence of the plot, we also asked that the geom be rendered using a named color (blue for the color of the line, and also blue for the fill), and that it be transparent (the argument <code>alpha</code> controls opacity; a value of zero is transparent, a value of 1 is solid):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p <span class="op">+</span><span class="st"> </span><span class="kw">geom_area</span>(<span class="kw">aes</span>(<span class="dt">x =</span> timecycle), <span class="dt">stat =</span> <span class="st">&quot;bin&quot;</span>, <span class="dt">binwidth =</span> <span class="dv">5</span>, <span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.6</span>)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p>The final plot was obtained by layering a second geom (in yellow) for a different variable (time by walking), so that we could compare them:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> time.Active.clean) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_area</span>(<span class="kw">aes</span>(<span class="dt">x =</span> timecycle), <span class="dt">stat =</span> <span class="st">&quot;bin&quot;</span>, <span class="dt">binwidth =</span> <span class="dv">5</span>, <span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.6</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_area</span>(<span class="kw">aes</span>(<span class="dt">x =</span> timewalk), <span class="dt">stat =</span> <span class="st">&quot;bin&quot;</span>, <span class="dt">binwidth =</span> <span class="dv">5</span>, <span class="dt">fill =</span> <span class="st">&quot;yellow&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;yellow&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.6</span>)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p>Notice that the x axis is labeled as “timecycle” despite the fact that the plot also includes time by walking. This can be fixed by changing the label as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> time.Active.clean) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_area</span>(<span class="kw">aes</span>(<span class="dt">x =</span> timecycle), <span class="dt">stat =</span> <span class="st">&quot;bin&quot;</span>, <span class="dt">binwidth =</span> <span class="dv">5</span>, <span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.6</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_area</span>(<span class="kw">aes</span>(<span class="dt">x =</span> timewalk), <span class="dt">stat =</span> <span class="st">&quot;bin&quot;</span>, <span class="dt">binwidth =</span> <span class="dv">5</span>, <span class="dt">fill =</span> <span class="st">&quot;yellow&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;yellow&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.6</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;Time (in minutes)&quot;</span>)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>What do we learn from this plot? Would it have been possible to learn the same from the summary statistics? Which was more effective, the plot or the summary statistics?</p>
<p>The plot above is an example of a <em>univariate</em> plot, since it is created to display the distribution of a single variable, not the way two or more variables relate. Imagine now that you would like to see how mode choice and sidewalk density at the place of residence relate. An appropriate statistical plot for two variables, one of which is nominal (<code>choice</code>) and another that is continuous (<code>side_den</code>), is the boxplot.</p>
<p>Before creating the plot, lets summarize these two variables (notice the use of the pipe operator):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mc_mode_choice <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="kw">c</span>(<span class="st">&quot;choice&quot;</span>, <span class="st">&quot;side_den&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">summary</span>()</code></pre></div>
<pre><code>##    choice       side_den    
##  Cycle: 48   Min.   : 0.00  
##  Walk :711   1st Qu.:18.19  
##  HSR  :336   Median :22.63  
##  Car  :281   Mean   :24.18  
##              3rd Qu.:35.70  
##              Max.   :59.41</code></pre>
<p>Sidewalk density is measured in <span class="math inline">\(km/km^2\)</span>.</p>
<p>Lets create the boxplot next. We begin by defining a <code>ggplot2</code> object with the data frame and aesthetics that we wish to use. In this case, we want to plot the categorical variable in the x axis and the quantitative variable in the y axis:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="dt">data =</span> mc_mode_choice, <span class="kw">aes</span>(<span class="dt">x =</span> choice, <span class="dt">y =</span> side_den)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>()</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>What do we learn from this plot? Could we have derived a similar insight from the summary statistics?</p>
<p>There are many different geoms that can be used in <code>ggplot2</code>. You can always consult the help/tutorial files by typing <code>??ggplot2</code> in the console. See:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">??ggplot2</code></pre></div>
<p>You can also check the <code>ggplot2</code> <a href="https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf">Cheat Sheet</a> for more information on how to use this package.</p>
<p>A last note. Many other visualization alternatives (for instance, Excel) provide point-and-click functions for creating plots. In contrast, ggplot2 in R requires that the plot be created by meticulously instructing the package what to do. While this is more laborious, it also means that you have complete control over the creation of plots, which in turn allows you to create more flexible and creative visuals.</p>
</div>
<div id="exercise" class="section level2">
<h2><span class="header-section-number">3.10</span> Exercise</h2>
<div id="questions" class="section level3">
<h3><span class="header-section-number">3.10.1</span> Questions</h3>
<ol style="list-style-type: decimal">
<li><p>Define “model”.</p></li>
<li><p>Why are models on a 1-to-1 scale undesirable?</p></li>
<li><p>Invoke dataset <code>Mode</code> from package <code>mlogit</code>. To do this you need to first load the package. Once you have done so, usage of datasets is as follows:</p></li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(<span class="st">&quot;Mode&quot;</span>)</code></pre></div>
<p>This is a dataset with choices about mode of transportation.</p>
<ol start="4" style="list-style-type: decimal">
<li><p>Describe this dataset. How many variables are there and of which type (i.e., categorical/quantitative)?</p></li>
<li><p>How many different modes of transportation are in this data set? What is the most popular mode? What is the least popular mode?</p></li>
<li><p>In general, what is the most expensive mode? The least expensive?</p></li>
<li><p>Create a plot showing the univariate distributions of time by car and time by bus. Discuss.</p></li>
<li><p>How do choices relate to cost by the different modes?</p></li>
</ol>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-wickham2016r">
<p>Wickham, Hadley, and Garrett Grolemund. 2016. <em>R for Data Science: Import, Tidy, Transform, Visualize, and Model Data</em>. “ O’Reilly Media, Inc.”</p>
</div>
<div id="ref-Tuckey1977">
<p>Tuckey, JW. 1977. <em>Exploratory Data Analysis</em>. Reading, Massachussets: Addison-Wesley Publishing Company.</p>
</div>
<div id="ref-Bhat1998comparison">
<p>Bhat, C. R., and V. Pulugurta. 1998. “A Comparison of Two Alternative Behavioral Choice Mechanisms for Household Auto Ownership Decisions.” Journal Article. <em>Transportation Research Part B</em> 32 (1): 61–75.</p>
</div>
<div id="ref-Whalen2013">
<p>Whalen, Kate E., Antonio Páez, and Juan A. Carrasco. 2013. “Mode Choice of University Students Commuting to School and the Role of Active Travel.” Journal Article. <em>Journal of Transport Geography</em> 31: 132–42. doi:<a href="https://doi.org/http://dx.doi.org/10.1016/j.jtrangeo.2013.06.008">http://dx.doi.org/10.1016/j.jtrangeo.2013.06.008</a>.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="preliminaries-installing-r-and-rstudio.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chapter-2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/01-Data-and-Stuff.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
